(* parse_checked rejects a fixture the Go grammar cannot parse, so a fixture
   typo is a test failure and never a silent zero. *)
let parse_checked (path, source) =
  let file = Source.parse path source in
  if Source.Node.has_error file.root then begin
    Printf.eprintf "Invalid fixture %s:\n%s\n" path source;
    failwith (path ^ ": invalid fixture syntax")
  end;
  file

let findings ?(declared = []) files =
  CS21.collect ~declared (List.map parse_checked files)
  |> List.filter (fun (finding : Source.finding) -> finding.rule = "CS-21")

let count ?(declared = []) label expected files =
  let actual = findings ~declared files in
  if List.length actual <> expected then begin
    List.iter (fun (finding : Source.finding) ->
      Printf.eprintf "%s:%d %s %s\n" finding.path finding.line finding.rule finding.message) actual;
    failwith (Printf.sprintf "%s: expected %d findings, got %d" label expected (List.length actual))
  end

(* role_named_file_mixing_types *)
let test_mixes () =
  count "a role file holding two types is one offense" 1
    ["fixture/options.go", {|package fixture
type ClockOption struct{}
type SinkOption struct{}
|}];
  count "a role file holding one type is not this offense" 0
    ["fixture/options.go", {|package fixture
type ClockOption struct{ Interval int }
|}];
  count "a role file holding a type and its methods is not this offense" 0
    ["fixture/errors.go", {|package fixture
type NotFoundError struct{ Name string }
func (e NotFoundError) Error() string { return e.Name }
|}]

(* method_outside_its_type_files *)
let test_away () =
  count "a method away from its type's file is one offense" 1
    [ "fixture/server.go", {|package fixture
type Server struct{ addr string }
|};
      "fixture/handlers.go", {|package fixture
func (s *Server) Do() string { return s.addr }
|} ];
  count "a method in its type's declaring file is not this offense" 0
    ["fixture/server.go", {|package fixture
type Server struct{ addr string }
func (s *Server) Do() string { return s.addr }
|}];
  count "a method in a file named for its type is not this offense" 0
    [ "fixture/server.go", {|package fixture
type Server struct{ addr string }
|};
      "fixture/server_http.go", {|package fixture
func (s *Server) Serve() string { return s.addr }
|} ];
  count "a method whose receiver type is unknown here is not this offense" 0
    ["fixture/handlers.go", {|package fixture
func (external Thing) Do() string { return "" }
|}]

(* generated_layout_by_role *)
let test_generated_layout () =
  let generated_models = {|// Code generated by sqlc. DO NOT EDIT.

package storedb

type Row struct { ID int }
|} in
  count "a generated role-named file with no declared layout is one offense" 1
    ["fixture/storedb/models.go", generated_models];
  count "a generated role-named file in a declared layout directory is not this offense" 0
    ~declared:["fixture/storedb"] ["fixture/storedb/models.go", generated_models];
  count "a generated file named for a type is not a role-named offense" 0
    ["fixture/storedb/row.go", generated_models]

let () =
  test_mixes ();
  test_away ();
  test_generated_layout ();
  print_endline "CS-21 house rule OCaml tests passed"
