(* Copyright 2026 Candace Labs *)

let expect message condition = if not condition then failwith message

let rules path source =
  Placement.collect [Source.parse path source] |> List.map (fun (finding : Source.finding) -> finding.rule)

let count rule findings = List.length (List.filter (( = ) rule) findings)

let goroutines () =
  let spawn = {|package p
func Run() {
  go work()
  go func() { for { work() } }()
}
func work() {}
|} in
  expect "unowned goroutines in a service missed" (count "CS-15" (rules "services/example/run.go" spawn) = 2);
  expect "unowned goroutines in runtime/ missed" (count "CS-15" (rules "runtime/run.go" spawn) = 2);
  expect "unowned goroutines in a test exempted" (count "CS-15" (rules "services/example/run_test.go" spawn) = 2);
  let owned = rules "services/example/owned.go" {|package p
func Joined() {
  var group sync.WaitGroup
  group.Add(1)
  go func() { defer group.Done(); work() }()
  group.Wait()
}
func Cancelled(ctx context.Context) {
  go func() { <-ctx.Done(); work() }()
  go serve(ctx)
  go serve(requestContext)
}
func Signalled() error {
  done := make(chan error, 1)
  go func() { done <- work() }()
  return <-done
}
func Selected(stop chan struct{}) {
  finished := make(chan struct{})
  go func() { defer close(finished); work() }()
  select {
  case <-finished:
  case <-stop:
  }
}
func Ranged() {
  results := make(chan int)
  go func() { results <- 1; close(results) }()
  for range results {}
}
|} in
  expect "a channel handed to a waiter counted as unowned"
    (rules "services/example/waited_test.go" {|package p
var _ = It("joins", func() {
  done := make(chan struct{})
  go func() { defer close(done); work() }()
  Eventually(done).Should(BeClosed())
})
|} = []);
  expect "a channel returned to the caller counted as unowned"
    (rules "services/example/handoff.go" {|package p
func Start() chan struct{} {
  done := make(chan struct{})
  go func() { defer close(done); work() }()
  return done
}
|} = []);
  expect "a goroutine in a spec literal escaped the rule"
    (count "CS-15" (rules "services/example/leak_test.go" {|package p
var _ = It("leaks", func() {
  go func() { for { work() } }()
})
|}) = 1);
  expect ("owned goroutines reported: " ^ string_of_int (count "CS-15" owned)) (owned = []);
  expect "a channel nobody receives from counted as a join"
    (count "CS-15" (rules "services/example/leak.go" {|package p
func Leak() {
  done := make(chan error, 1)
  go func() { done <- work() }()
}
|}) = 1);
  expect "comments and strings reported"
    (rules "services/example/doc.go" {|package p
// go work()
const example = "go work()"
|} = []);
  expect "generated code reported"
    (rules "services/example/gen.go" ("// Code generated by fixture. DO NOT EDIT.\n" ^ spawn) = [])

let boundaries () =
  let crossings = {|package p
import (
  network "net"
  "net/http"
  "google.golang.org/grpc"
)
func Open() {
  _, _ = network.Listen("tcp", ":0")
  _, _ = network.Dial("tcp", "peer:1")
  _ = http.ListenAndServe(":0", nil)
  _, _ = grpc.NewClient("peer:1")
  _ = network.Dialer{}
  _ = &network.ListenConfig{}
}
|} in
  expect "boundary crossings outside ipc missed" (count "CS-16" (rules "services/example/open.go" crossings) = 6);
  expect "boundary crossings in ipc/ reported" (rules "ipc/net/network.go" crossings = []);
  expect "boundary crossings in a test exempted" (count "CS-16" (rules "services/example/open_test.go" crossings) = 6);
  expect "non-boundary calls reported"
    (rules "services/example/address.go" {|package p
import (
  "net"
  "net/http"
  "google.golang.org/grpc"
)
func Parse() {
  _, _, _ = net.SplitHostPort("a:1")
  _ = http.NewServeMux()
  _ = grpc.WithBlock()
  _ = net.IPv4len
  _ = server.ListenAndServe()
}
|} = []);
  expect "an unrelated package spelled net reported"
    (rules "services/example/other.go" {|package p
import net "example.invalid/net"
func Open() { _, _ = net.Listen("tcp", ":0") }
|} = [])

let databases () =
  let pools = {|package p
import (
  "github.com/jackc/pgx/v5"
  "github.com/jackc/pgx/v5/pgxpool"
  pool "github.com/jackc/pgx/v5/pgxpool"
)
func Open() {
  _, _ = pgxpool.New(ctx, url)
  _, _ = pool.NewWithConfig(ctx, config)
  _, _ = pgx.Connect(ctx, url)
  _, _ = pgx.ConnectConfig(ctx, config)
}
|} in
  expect "pool and connection creation in a service missed" (count "CS-16-DB" (rules "services/example/store.go" pools) = 4);
  expect "pool and connection creation in an app missed" (count "CS-16-DB" (rules "app/example/cmd/main.go" pools) = 4);
  expect "pool creation elsewhere under ipc/ missed" (count "CS-16-DB" (rules "ipc/net/pool.go" pools) = 4);
  expect "the PostgreSQL capability itself reported" (rules "ipc/db/csfpg/database.go" pools = []);
  expect "test-file pools missed" (count "CS-16-DB" (rules "services/example/store_test.go" pools) = 4);
  expect "pool configuration and use reported"
    (rules "services/example/use.go" {|package p
import (
  "github.com/jackc/pgx/v5"
  "github.com/jackc/pgx/v5/pgxpool"
)
func Use(database *pgxpool.Pool) {
  _, _ = pgxpool.ParseConfig(url)
  _, _ = pgx.ParseConfig(url)
  _, _ = database.Begin(ctx)
  _ = pgx.Identifier{"x"}
}
|} = []);
  expect "net listen inside the PostgreSQL capability exempt from the network part"
    (rules "ipc/db/csfpg/listen.go" {|package p
import "net"
func Open() { _, _ = net.Listen("tcp", ":0") }
|} = [])

let environment () =
  let reads = {|package p
import (
  environ "os"
)
func Load() {
  _ = environ.Getenv("A")
  _, _ = environ.LookupEnv("B")
  _ = environ.Environ()
  load(environ.LookupEnv)
}
|} in
  expect "environment reads in a service missed" (count "CS-17" (rules "services/example/load.go" reads) = 4);
  expect "environment reads in pkg/ missed" (count "CS-17" (rules "pkg/example/load.go" reads) = 4);
  expect "environment reads in a binary's main package missed" (count "CS-17" (rules "app/example/main.go" reads) = 4);
  expect "the config capability reported" (rules "runtime/config/environment.go" reads = []);
  expect "a binary's config package reported" (rules "app/example/config/config.go" reads = []);
  expect "a nested config directory outside app/ reported as allowed"
    (count "CS-17" (rules "services/example/config/config.go" reads) = 4);
  expect "test environment reads exempted" (count "CS-17" (rules "services/example/load_test.go" reads) = 4);
  expect "the config capability's own specs reported" (rules "runtime/config/environment_test.go" reads = []);
  expect "non-environment os calls reported"
    (rules "services/example/files.go" {|package p
import "os"
func Open() { _, _ = os.Open("x"); _ = os.Setenv("A", "b"); _, _ = os.Hostname() }
|} = []);
  expect "an unrelated package spelled os reported"
    (rules "services/example/other.go" {|package p
import os "example.invalid/os"
func Load() { _ = os.Getenv("A") }
|} = [])

let processes () =
  let launches = {|package p
import (
  runner "os/exec"
  "os"
  "syscall"
  "github.com/creack/pty"
)
func Launch() {
  _ = runner.Command("git")
  _, _ = os.StartProcess("/bin/true", nil, nil)
  _ = syscall.Exec("/bin/true", nil, nil)
  _, _ = syscall.ForkExec("/bin/true", nil, nil)
  _, _ = pty.Start(nil)
}
|} in
  (* Two imports (os/exec, pty) and three fork/exec calls; the aliased
     exec.Command is covered by its import. *)
  expect "process crossings outside ipc/proc missed" (count "CS-16" (rules "services/example/launch.go" launches) = 5);
  expect "process crossings in pkg/ missed" (count "CS-16" (rules "pkg/example/launch.go" launches) = 5);
  expect "the gateway itself reported" (rules "ipc/proc/launcher.go" launches = []);
  expect "another ipc package exempted from the process rule"
    (count "CS-16" (rules "ipc/docker/containers.go" launches) = 5);
  expect "tests exempted from the process rule" (count "CS-16" (rules "services/example/launch_test.go" launches) = 5);
  expect "the gateway's own specs reported" (rules "ipc/proc/launcher_unit_test.go" launches = []);
  expect "non-process os and syscall calls reported"
    (rules "services/example/files.go" {|package p
import (
  "os"
  "syscall"
)
func Read() {
  _, _ = os.ReadFile("x")
  _ = syscall.Kill(1, syscall.SIGTERM)
  _ = os.Getpid()
}
|} = [])

let directories () =
  let terms = Placement.ontology_terms {|# comment
term runtime "Runtime" "x";
term ipc "IPC" "x";
term net "Socket" "x";
term http "HTTP" "x";
term config "Config" "x";
term service "Service" "x";
term app "App" "x";
term pkg "Pure library" "x";
term core "CPU core" "x";
|} in
  expect "terms not read" (List.length terms = 9);
  let found = Placement.directories ~terms [
    "runtime/scope.go"; "runtime/config/environment.go";
    "ipc/net/network.go"; "ipc/net/http/listener.go";
    "ipc/net/carrier/pigeon.go";
    "services/warden/anything/goes.go";
    "services/example/internal/engine/run.go";
    "pkg/core/core.go"; "pkg/eventually/eventually.go";
    "internal/runtime/shim.go";
    "xetcas/go/a.go"; "xetcas/go/b/b.go";
    "app/csf/cmd/main.go";
    "README.md"; "vendor/whatever/x.go"; "pkg/vendor/x.go";
    "research/whatever/x.go";
  ] |> List.map (fun (finding : Source.finding) -> finding.path) in
  expect ("unexpected directory findings: " ^ String.concat ", " found)
    (found = ["ipc/net/carrier"; "pkg/core"; "services/example/internal/engine"; "xetcas"]);
  expect "an empty ontology reported everything" (Placement.directories ~terms:[] ["x/y.go"] = [])

let () =
  goroutines ();
  boundaries ();
  databases ();
  environment ();
  processes ();
  directories ();
  print_endline "House lint placement rule tests passed"
