open Source

external python_language : unit -> nativeint = "candace_tree_sitter_python"
let parser = lazy (Tree_sitter.Parser.create (Tree_sitter.Language.of_address (python_language ())))
let rule = "PY-MAGIC-STRING"

let significant node = children node |> List.filter (fun child -> kind child <> "comment")
let test_path path =
  let name = Filename.basename path in
  String.starts_with ~prefix:"test_" name || Filename.check_suffix name "_test.py" ||
  List.mem "tests" (String.split_on_char '/' path)
let selected_path path =
  Filename.check_suffix path ".py" && not (Source.excluded path) &&
  not (String.starts_with ~prefix:"third_party/" path) && not (test_path path)

let contains source needle =
  let rec search offset = offset + String.length needle <= String.length source &&
    (String.sub source offset (String.length needle) = needle || search (offset + 1)) in
  search 0
let generated source = String.split_on_char '\n' source |> List.take 20 |> List.exists (fun line ->
  let line = String.trim line |> String.lowercase_ascii in
  String.starts_with ~prefix:"#" line &&
  (String.starts_with ~prefix:"# @generated" line ||
   String.starts_with ~prefix:"# generated by " line ||
   (contains line "generated" && contains line "do not edit")))

let parse path source : Source.file =
  let source = if String.ends_with ~suffix:"\n" source then source else source ^ "\n" in
  let tree = Tree_sitter.Parser.parse_string (Lazy.force parser) source in
  {path; source; tree; root = Tree_sitter.Tree.root_node tree}
let syntax_errors file =
  if not (Node.has_error file.root) then [] else
  let errors = descendants file.root |> List.filter_map (fun node ->
    if Node.is_error node || Node.is_missing node then
      Some (issue file node "PARSE" "Python grammar could not parse this syntax; scan is incomplete")
    else None) in
  if errors <> [] then errors else
    [issue file file.root "PARSE" "Python grammar found missing syntax; scan is incomplete"]

let ascii_letter = function 'a' .. 'z' | 'A' .. 'Z' -> true | _ -> false
let identifier_value value =
  String.length value > 0 && (ascii_letter value.[0] || value.[0] = '_') &&
  (String.length value > 1 || ascii_letter value.[0]) &&
  String.for_all (fun char -> ascii_letter char ||
    match char with '0' .. '9' | '_' | '-' | '.' | ':' | '/' -> true | _ -> false) value
let constant_name name =
  String.exists (function 'A' .. 'Z' -> true | _ -> false) name &&
  String.for_all (function 'A' .. 'Z' | '0' .. '9' | '_' -> true | _ -> false) name
let named_constant file node = match field node "left", field node "right" with
  | Some target, Some value when kind target = "identifier" -> constant_name (text file target) &&
      List.mem (kind value) ["string"; "concatenated_string"; "dictionary"; "list"; "tuple"; "set"]
  | _ -> false

(* The grammar owns literal boundaries. Decode only ASCII escapes relevant to
   token-shaped values; Unicode names and non-ASCII values are outside this
   advisory locator. An unsupported escape never becomes a fabricated value. *)
let hex_escape source offset count =
  if offset + count > String.length source then invalid_arg "truncated Python hexadecimal escape";
  let digits = String.sub source offset count in
  if not (String.for_all (function '0' .. '9' | 'a' .. 'f' | 'A' .. 'F' -> true | _ -> false) digits)
  then invalid_arg "invalid Python hexadecimal escape";
  let value = int_of_string ("0x" ^ digits) in
  if count = 8 && value > 0x10ffff then invalid_arg "Python Unicode escape exceeds U+10FFFF";
  value
let escaped_ascii source =
  let output = Buffer.create (String.length source) in
  let length = String.length source in
  let rec append code next = match code with
    | Some code when code >= 0 && code < 128 -> Buffer.add_char output (Char.chr code); decode next
    | _ -> None
  and decode offset =
    if offset = length then Some (Buffer.contents output) else
    if source.[offset] <> '\\' then begin Buffer.add_char output source.[offset]; decode (offset + 1) end
    else if offset + 1 = length then None else
    match source.[offset + 1] with
    | 'x' | 'u' | 'U' as marker ->
        let count = if marker = 'x' then 2 else if marker = 'u' then 4 else 8 in
        append (Some (hex_escape source (offset + 2) count)) (offset + 2 + count)
    | '0' .. '7' ->
        let ending = ref (offset + 1) in
        while !ending < min length (offset + 4) && source.[!ending] >= '0' && source.[!ending] <= '7' do incr ending done;
        let digits = String.sub source (offset + 1) (!ending - offset - 1) in
        append (int_of_string_opt ("0o" ^ digits)) !ending
    | '\n' -> decode (offset + 2)
    | '\r' when offset + 2 < length && source.[offset + 2] = '\n' -> decode (offset + 3)
    | char ->
        let code = match char with
          | '\\' | '\'' | '"' -> Some (Char.code char)
          | 'a' -> Some 7 | 'b' -> Some 8 | 'f' -> Some 12 | 'n' -> Some 10
          | 'r' -> Some 13 | 't' -> Some 9 | 'v' -> Some 11 | _ -> None in
        append code (offset + 2) in
  decode 0

(* Tree-sitter accepts malformed hexadecimal escapes as string_content. Check
   these lexical errors even in declarations exempt from advisory findings.
   Raw strings preserve escapes; bytes do not interpret Unicode escapes. *)
let validate_escapes bytes source =
  let rec visit offset =
    if offset + 1 < String.length source then
      if source.[offset] <> '\\' then visit (offset + 1) else
      let marker = source.[offset + 1] in
      let count = if marker = 'x' then 2 else if not bytes && marker = 'u' then 4
        else if not bytes && marker = 'U' then 8 else 0 in
      if count = 0 then visit (offset + 2) else begin
        ignore (hex_escape source (offset + 2) count); visit (offset + 2 + count)
      end in
  visit 0
let literal_errors file = descendants file.root |> List.filter_map (fun node ->
  if kind node <> "string" then None else
  let parts = significant node in
  match List.find_opt (fun part -> kind part = "string_start") parts with
  | None -> None
  | Some first ->
      let prefix = text file first |> String.lowercase_ascii in
      if String.contains prefix 'r' then None else
      try
        parts |> List.filter (fun part -> kind part = "string_content")
        |> List.iter (fun part -> validate_escapes (String.contains prefix 'b') (text file part));
        None
      with Invalid_argument message -> Some (issue file node "PARSE" message))

let string_value file node =
  let parts = significant node in
  match List.find_opt (fun node -> kind node = "string_start") parts,
        List.find_opt (fun node -> kind node = "string_end") parts with
  | Some first, Some last when not (List.exists (fun node -> kind node = "interpolation") parts) ->
      let prefix = text file first |> String.lowercase_ascii in
      if String.contains prefix 'b' then None else
      let offset = Node.end_byte first in
      let inner = String.sub file.source offset (Node.start_byte last - offset) in
      if String.contains prefix 'r' then Some inner else escaped_ascii inner
  | _ -> None
let literal_value file node =
  let parts = if kind node = "concatenated_string" then significant node else [node] in
  List.fold_left (fun value part -> match value, string_value file part with
    | Some prefix, Some suffix -> Some (prefix ^ suffix) | _ -> None) (Some "") parts

let string_node node = List.mem (kind node) ["string"; "concatenated_string"]
let docstring file node = kind node = "expression_statement" &&
  match significant node with
  | [child] when string_node child -> descendants child |> List.for_all (fun part ->
      if kind part <> "string_start" then true else
      let prefix = text file part |> String.lowercase_ascii in
      not (String.contains prefix 'f' || String.contains prefix 'b'))
  | _ -> false
let body_children file node = match significant node with
  | first :: rest when docstring file first -> rest
  | children -> children
let message_methods = ["debug"; "info"; "warning"; "warn"; "error"; "exception"; "critical"; "fatal"]
let message_position callee index =
  let name = List.hd (List.rev (String.split_on_char '.' callee)) in
  callee = "print" ||
  (index = 0 && (List.mem name message_methods || String.ends_with ~suffix:"Error" name ||
                 name = "Exception" || name = "SystemExit")) ||
  (index = 1 && name = "log")

let findings file =
  let rec visit active node = match kind node with
    | "function_definition" | "lambda" ->
        Option.fold ~none:[] ~some:(fun body ->
          if kind body = "block" then body_children file body |> List.concat_map (visit true)
          else visit true body) (field node "body")
    | "class_definition" -> Option.fold ~none:[] ~some:(visit false) (field node "body")
    | "import_statement" | "import_from_statement" | "future_import_statement" -> []
    | "assignment" when active && named_constant file node -> nested_functions node
    | "call" when active -> call node
    | "string" | "concatenated_string" when active -> literal node
    | _ -> significant node |> List.concat_map (visit active)
  and nested_functions node = significant node |> List.concat_map (fun child ->
    if List.mem (kind child) ["function_definition"; "lambda"; "class_definition"] then visit true child
    else if string_node child then embedded child
    else nested_functions child)
  and embedded node = significant node |> List.concat_map (fun child ->
    if kind child = "interpolation" then visit true child else embedded child)
  and literal node = match literal_value file node with
    | Some value when identifier_value value ->
        [issue file node rule (Printf.sprintf
          "unnamed semantic string literal %S: name a constant or generated enum in its owning module" value)]
    | _ -> embedded node
  and message node = if string_node node then embedded node else visit true node
  and argument callee index node =
    if kind node = "keyword_argument" then
      let name = Option.value (field_text file node "name") ~default:"" in
      let inspect = if name = "msg" && (message_position callee 0 || message_position callee 1)
        then message else visit true in
      Option.fold ~none:[] ~some:inspect (field node "value")
    else if message_position callee index then message node else visit true node
  and call node =
    let callee = Option.value (field_text file node "function") ~default:"" in
    let target = Option.fold ~none:[] ~some:(visit true) (field node "function") in
    target @ Option.fold ~none:[] ~some:(fun arguments ->
      significant arguments |> List.mapi (argument callee) |> List.concat) (field node "arguments") in
  visit false file.root

(* CS-20: a scan reports its count, findings and errors as one named record,
   never as a bare triple. *)
type scan = { count : int; findings : Source.finding list; errors : Source.finding list }

let inspect root path =
  let source = Checker.read_file (Checker.checked_path root path) in
  if generated source then { count = 0; findings = []; errors = [] } else
  if not (String.is_valid_utf_8 source) then
    { count = 1; findings = [];
      errors = [{path; line=1; rule="SCAN"; message="Python source is not UTF-8; scan is incomplete"}] }
  else
    let file = parse path source in
    let errors = syntax_errors file @ literal_errors file in
    { count = 1; findings = (if errors = [] then findings file else []); errors }
let check root paths =
  paths |> List.filter selected_path |> List.sort_uniq String.compare
  |> List.fold_left (fun accumulated path ->
    let next = try inspect root path with
      | Sys_error message | Invalid_argument message | Failure message ->
          { count = 1; findings = []; errors = [{path; line=1; rule="SCAN"; message}] }
      | Unix.Unix_error (error, operation, _) ->
          { count = 1; findings = [];
            errors = [{path; line=1; rule="SCAN"; message=operation ^ ": " ^ Unix.error_message error}] } in
    { count = accumulated.count + next.count;
      findings = accumulated.findings @ next.findings;
      errors = accumulated.errors @ next.errors })
    { count = 0; findings = []; errors = [] }
