let expect message condition = if not condition then failwith message
let write root name source =
  Out_channel.with_open_text (Filename.concat root name) (fun channel -> output_string channel source)
let lines findings = List.map (fun (finding : Source.finding) -> finding.line) findings
let count_of scan = scan.Python_magic.count
let findings_of scan = scan.Python_magic.findings
let errors_of scan = scan.Python_magic.errors
let empty = { Python_magic.count = 0; Python_magic.findings = []; Python_magic.errors = [] }
let check_source root source =
  write root "fixture.py" source;
  let scan = Python_magic.check root ["fixture.py"] in
  expect "production source count changed" (count_of scan = 1);
  expect "valid Python fixture failed parsing" (errors_of scan = []);
  List.iter (fun (finding : Source.finding) ->
    expect "wrong rule or source path" (finding.rule = "PY-MAGIC-STRING" && finding.path = "fixture.py")) (findings_of scan);
  findings_of scan

let semantic_cases root =
  let findings = check_source root {|def select(record, state):
    phase = "queued"
    if state == "ready":
        return record["status"]
    emit("dispatch", format="compact")
    return {"kind": "completed"}
|} in
  expect "semantic contexts or exact lines missed" (lines findings = [2; 3; 4; 5; 5; 6; 6]);
  expect "diagnostic does not recommend an owned name"
    (List.for_all (fun (finding : Source.finding) ->
      Python_magic.contains finding.message "name a constant or generated enum") findings);
  let findings = check_source root {|async def modes():
    value = r"raw_mode"
    await emit('''triple_mode''')
    value = "\u0072eady"
    value = "\x72eady"
    value = "\162eady"
    return "part_" "two"
|} in
  expect "raw, triple, escaped or concatenated strings missed" (lines findings = [2; 3; 4; 5; 6; 7]);
  let findings = check_source root {|class Handler:
    kind = "declaration"
    def dispatch(self):
        return "method_result"
lookup = lambda record: record["lambda_key"]
|} in
  expect "methods or lambdas missed" (lines findings = [4; 5])

let exemptions root =
  expect "declarations, docs, constants or human text reported" (check_source root {|"""Module documentation."""
from enum import Enum
MODULE_VALUE = "module_value"
module_setting = "module_setting"
class Mode(Enum):
    READY = "ready"
    class_setting = "class_setting"
def explain():
    """function_docstring"""
    from importlib import import_module
    STATUS = "local_constant"
    CONFIG: str = "annotated_constant"
    print("Done")
    logger.info("starting")
    logger.warning(msg="warning")
    logging.log(20, "notice")
    logger.log(level=20, msg="notice")
    separator = ":"
    joined = "_".join(parts)
    empty = ""
    newline = "\n"
    raw_escape = r"\n"
    binary = b"payload"
    raise RuntimeError("failed")
    return "human readable message"
|} = []);
  let findings = check_source root {|def report():
    logger.info("starting", extra={"phase": "queued"})
    print({"kind": "result"})
    logger.info(build("semantic_argument"))
    return "still_semantic"
|} in
  expect "message exemption hid payloads or rest of function" (lines findings = [2; 2; 3; 3; 4; 5]);
  let findings = check_source root {|def dynamic(record, prefix):
    value = f"{prefix}_dynamic_suffix"
    value = f"{record['semantic_key']}"
    logger.info(f"{record['logged_key']}")
    return f"static_token"
|} in
  expect "dynamic text boundary or interpolation traversal changed" (lines findings = [3; 4; 5]);
  let findings = check_source root {|def callbacks(record):
    f"{record['first_key']}"
    HANDLER = lambda item: item["lambda_key"]
    OPTIONS = {"constant_key": lambda item: item["nested_key"]}
    TOKEN = make("call_argument")
    DYNAMIC = f"{record['constant_expression']}"
|} in
  expect "docstring or constant exemption hid executable expressions" (lines findings = [2; 3; 4; 5; 6])

let corpus_cases root =
  let ignored = ["test_fixture.py"; "fixture_test.py"; "tests/missing.py";
    "vendor/missing.py"; "pkg/vendor/missing.py"; "research/missing.py";
    "third_party/missing.py"; "fixture.ml"] in
  expect "ignored inputs were opened or empty Python corpus failed"
    (Python_magic.check root ignored = empty);
  expect "empty Python corpus failed" (Python_magic.check root [] = empty);
  write root "generated.py" "# Generated by a fixture. DO NOT EDIT!\r\nnot python syntax (\n";
  expect "generated file was parsed or counted" (Python_magic.check root ["generated.py"] = empty);
  write root "fixture.py" "def one():\n    return 'unique'\n";
  let scan = Python_magic.check root ["fixture.py"; "fixture.py"] in
  expect "duplicate inventory doubled findings" (count_of scan = 1 && lines (findings_of scan) = [2] && errors_of scan = []);
  let scan = Python_magic.check root ["missing.py"] in
  expect "unreadable source passed" (count_of scan = 1 && errors_of scan <> []);
  let scan = Python_magic.check root ["../outside.py"] in
  expect "inventory escaped checkout" (errors_of scan <> [])

let error_cases root =
  List.iter (fun source ->
    write root "broken.py" source;
    let scan = Python_magic.check root ["broken.py"] in
    expect "invalid Python syntax passed" (count_of scan = 1 && findings_of scan = [] && errors_of scan <> []))
    ["def broken(:\n    return 'pending'\n";
     "def broken():\n    return ('pending'\n";
     "def broken():\n    return '''unterminated\n"];
  List.iter (fun literal ->
    write root "broken.py" ("VALUE = " ^ literal ^ "\n");
    expect "invalid escape in exempt declaration passed" (errors_of (Python_magic.check root ["broken.py"]) <> []))
    [{|"\xGG"|}; {|"\u12"|}; {|"\U00110000"|}; {|b"\xGG"|}];
  expect "raw or byte Unicode escapes were rejected"
    (check_source root {|def escapes():
    raw = r"\xGG"
    binary = b"\u12"
    valid = "\u00e9"
|} = []);
  write root "broken.py" "def broken(:\n";
  write root "fixture.py" "def one():\n    return 'unique'\n";
  let scan = Python_magic.check root ["broken.py"; "fixture.py"] in
  expect "syntax error suppressed other file findings" (count_of scan = 2 && lines (findings_of scan) = [2] && errors_of scan <> []);
  write root "invalid_utf8.py" "# \255\n";
  expect "invalid UTF-8 passed" (errors_of (Python_magic.check root ["invalid_utf8.py"]) <> []);
  Unix.symlink "fixture.py" (Filename.concat root "link.py");
  expect "source symlink bypassed shared path boundary" (errors_of (Python_magic.check root ["link.py"]) <> [])

let () =
  let root = Filename.temp_file "house-lint-python-" "" in
  Sys.remove root;
  Unix.mkdir root 0o700;
  Fun.protect ~finally:(fun () ->
    Sys.readdir root |> Array.iter (fun name -> Sys.remove (Filename.concat root name)); Unix.rmdir root)
    (fun () -> semantic_cases root; exemptions root; corpus_cases root; error_cases root);
  print_endline "Python magic-string native tests passed"
