let expect message condition = if not condition then failwith message
let findings ?(path="go/example.go") source = Shared_state.collect [Source.parse path source]
let warns message source = expect message (findings source <> [])
let accepts message source = expect message (findings source = [])

let () =
  warns "write through captured pointer missed" {|package p
func use(thingy **int) {
  go func() { *thingy = nil }()
  consume(*thingy)
}|};
  warns "parent clearing captured slot missed" {|package p
func use(thingy **int) {
  go func() { consume(*thingy) }()
  *thingy = nil
}|};
  warns "field mutation missed" {|package p
func use(state *State) {
  go func() { state.Value++ }()
  consume(state.Value)
}|};
  warns "slice mutation missed" {|package p
func use(values []int) {
  go func() { values[0] = 1 }()
  consume(values[0])
}|};
  warns "different locks were accepted" {|package p
import "sync"
func use(thingy **int) {
  var first, second sync.Mutex
  go func() { first.Lock(); *thingy = nil; first.Unlock() }()
  second.Lock(); consume(*thingy); second.Unlock()
}|};
  warns "only one side locking was accepted" {|package p
import "sync"
func use(thingy **int) {
  var mu sync.Mutex
  go func() { mu.Lock(); *thingy = nil; mu.Unlock() }()
  consume(*thingy)
}|};
  warns "write under read lock was accepted" {|package p
import "sync"
func use(thingy **int) {
  var mu sync.RWMutex
  go func() { mu.RLock(); *thingy = nil; mu.RUnlock() }()
  mu.RLock(); consume(*thingy); mu.RUnlock()
}|};
  warns "conditional lock was treated as unconditional" {|package p
import "sync"
func use(thingy **int, enabled bool) {
  var mu sync.Mutex
  go func() { if enabled { mu.Lock() }; *thingy = nil }()
  mu.Lock(); consume(*thingy); mu.Unlock()
}|};
  warns "conditional unlock was treated as still locked" {|package p
import "sync"
func use(thingy **int, enabled bool) {
  var mu sync.Mutex
  go func() { mu.Lock(); if enabled { mu.Unlock() }; *thingy = nil }()
  mu.Lock(); consume(*thingy); mu.Unlock()
}|};
  accepts "same mutex sections warned" {|package p
import locks "sync"
func use(thingy **int) {
  var mu locks.Mutex
  go func() { mu.Lock(); defer mu.Unlock(); *thingy = nil }()
  mu.Lock(); consume(*thingy); mu.Unlock()
}|};
  accepts "read lock matching exclusive write lock warned" {|package p
import "sync"
func use(thingy **int, mu *sync.RWMutex) {
  go func() { mu.Lock(); *thingy = nil; mu.Unlock() }()
  mu.RLock(); consume(*thingy); mu.RUnlock()
}|};
  accepts "joined worker warned" {|package p
import "sync"
func use(thingy **int, enabled bool) {
  var workers sync.WaitGroup
  if enabled {
    workers.Add(1)
    go func() { defer workers.Done(); *thingy = nil }()
  }
  workers.Wait()
  consume(*thingy)
}|};
  warns "wait before launch discharged later accesses" {|package p
import "sync"
func use(thingy **int) {
  var workers sync.WaitGroup
  workers.Wait()
  workers.Add(1)
  go func() { defer workers.Done(); *thingy = nil }()
  consume(*thingy)
}|};
  warns "conditional wait treated as unconditional" {|package p
import "sync"
func use(thingy **int, enabled bool) {
  var workers sync.WaitGroup
  workers.Add(1)
  go func() { defer workers.Done(); *thingy = nil }()
  if enabled { workers.Wait() }
  consume(*thingy)
}|};
  warns "Done before write discharged unfinished work" {|package p
import "sync"
func use(thingy **int) {
  var workers sync.WaitGroup
  workers.Add(1)
  go func() { workers.Done(); *thingy = nil }()
  workers.Wait()
  consume(*thingy)
}|};
  accepts "immutable reads warned" {|package p
func use(thingy **int) {
  go func() { consume(*thingy) }()
  consume(*thingy)
}|};
  accepts "blank identifier treated as shared memory" {|package p
func use() { go func() { _ = work() }(); _ = work() }
|};
  accepts "sole user warned" {|package p
func use(thingy **int) { go func() { *thingy = nil }() }
|};
  accepts "local closure variable confused with capture" {|package p
func use(thingy **int) {
  go func() { var thingy *int; thingy = nil }()
  consume(*thingy)
}|};
  accepts "ordinary synchronous call warned" {|package p
func use(thingy **int) {
  func() { *thingy = nil }()
  consume(*thingy)
}|};
  let generated = "// Code generated by fixture. DO NOT EDIT.\npackage p\nfunc use(p **int) { go func(){ *p = nil }(); consume(*p) }\n" in
  expect "generated file entered check" (findings generated = []);
  expect "excluded research entered check" (findings ~path:"research/example.go"
    {|package p; func use(p **int) { go func(){ *p = nil }(); consume(*p) }|} = []);
  let result = findings "package p\nfunc use(p **int) {\n go func(){ *p = nil }()\n consume(*p)\n}\n" in
  expect "diagnostic does not identify the write" (List.exists (fun (finding : Source.finding) ->
    finding.rule = "GOROUTINE-SHARED-STATE" && finding.path = "go/example.go" && finding.line = 3) result);
  print_endline "Shared goroutine state review tests passed"
