(* Copyright 2026 Candace Labs *)

let expect message condition = if not condition then failwith message

let parse (path, source) =
  let file = Source.parse path source in
  if Source.Node.has_error file.root then failwith (path ^ ": invalid fixture syntax");
  file

let modules = ["other", "github.com/example/other"; ".", "github.com/example/public"]

let findings rule sources =
  Test_layout.collect ~modules (List.map parse sources)
  |> List.filter (fun (finding : Source.finding) -> finding.rule = rule)

let count label rule expected sources =
  let actual = findings rule sources in
  if List.length actual <> expected then begin
    List.iter (fun (finding : Source.finding) ->
      Printf.eprintf "%s:%d %s %s\n" finding.path finding.line finding.rule finding.message) actual;
    failwith (Printf.sprintf "%s: expected %d %s findings, got %d" label expected rule (List.length actual))
  end

let mock_header = "// Code generated by MockGen. DO NOT EDIT.\n"

let store = "pkg/store/store.go", {|package store
type IStore interface { Get(key string) (string, error) }
type IClock interface { Now() int64 }
type Number interface { ~int | ~int64 }
type iPrivate interface { hidden() }
|}

let mockgen () =
  count "an exported interface with no directive" "CS-18-MOCKGEN" 2 [store];
  count "source-mode directive plus its tracked MockGen output" "CS-18-MOCKGEN" 0 [store;
    "pkg/store/mock_generate_test.go", {|package store_test
//go:generate go run go.uber.org/mock/mockgen@v0.6.0 -source=store.go -destination=mock_store_test.go -package=store_test
|};
    "pkg/store/mock_store_test.go", mock_header ^ "package store_test\ntype MockIStore struct{}\n"];
  count "package-mode directive in a consumer, resolved through the module table" "CS-18-MOCKGEN" 1 [store;
    "services/reader/mock_generate_test.go", {|package reader_test
//go:generate mockgen -destination=mock_store_test.go -package=reader_test github.com/example/public/pkg/store IStore
|};
    "services/reader/mock_store_test.go", mock_header ^ "package reader_test\n"];
  count "a relative -source in another directory" "CS-18-MOCKGEN" 0 [store;
    "services/reader/reader_suite_test.go", {|package reader_test
//go:generate go run go.uber.org/mock/mockgen@v0.6.0 -source ../../pkg/store/store.go -destination mocks/store.gen.go
|};
    "services/reader/mocks/store.gen.go", mock_header ^ "package mocks\n"];
  (* Anti-gaming: the directive alone, a directive whose output is a
     handwritten file, a plain comment mentioning mockgen, and a directive
     naming a different interface all leave the interface unmocked. *)
  count "a directive with no committed output" "CS-18-MOCKGEN" 2 [store;
    "pkg/store/generate.go", "package store\n//go:generate mockgen -source=store.go -destination=mock_store_test.go\n"];
  count "a directive whose destination is handwritten" "CS-18-MOCKGEN" 2 [store;
    "pkg/store/generate.go", "package store\n//go:generate mockgen -source=store.go -destination=mock_store_test.go\n";
    "pkg/store/mock_store_test.go", "package store_test\n// Code generated by hand, honestly.\ntype MockIStore struct{}\n"];
  count "a plain comment is not a directive" "CS-18-MOCKGEN" 2 [store;
    "pkg/store/generate.go", "package store\n// go:generate mockgen -source=store.go -destination=mock_store_test.go\n";
    "pkg/store/mock_store_test.go", mock_header ^ "package store_test\n"];
  count "a package-mode directive covers only the names it lists" "CS-18-MOCKGEN" 2 [store;
    "pkg/store/generate.go", "package store\n//go:generate mockgen -destination=mock_test.go . IStoreReader\n";
    "pkg/store/mock_test.go", mock_header ^ "package store_test\n"];
  count "test files and package main declare no mockable contract" "CS-18-MOCKGEN" 0 [
    "pkg/store/fixture_test.go", "package store_test\ntype IFixture interface { Run() }\n";
    "app/tool/main.go", "package main\ntype IStep interface { Run() }\n"]

let crossings () =
  let crossing = {|package reader_test
import (
  network "net"
  "net/http"
  "net/http/httptest"
  "os/exec"
  "database/sql"
  "github.com/jackc/pgx/v5/pgxpool"
  "github.com/jackc/pgx/v5"
  "github.com/testcontainers/testcontainers-go/modules/postgres"
)
func open() {
  _, _ = network.Listen("tcp", ":0")
  _ = network.Dialer{}
  _ = http.ListenAndServe(":0", nil)
  _ = httptest.NewServer(nil)
  _ = exec.Command("psql")
  _, _ = sql.Open("pgx", url)
  _, _ = pgxpool.New(ctx, url)
  _, _ = pgx.Connect(ctx, url)
}
|} in
  count "every crossing in an external test" "CS-18-CROSSING" 9 ["services/reader/reader_test.go", crossing];
  count "an in-package test crosses too" "CS-18-CROSSING" 9 ["services/reader/internal_test.go",
    "package reader" ^ String.sub crossing 19 (String.length crossing - 19)];
  count "production code belongs to CS-16, not CS-18" "CS-18-CROSSING" 0 ["services/reader/reader.go", crossing];
  count "the labelled acceptance suite" "CS-18-CROSSING" 0 ["services/reader/acceptance_test.go",
    "//go:build acceptance && linux\n\n" ^ crossing];
  count "mocks, pgmem, recorders and parsing make no crossing" "CS-18-CROSSING" 0 ["services/reader/reader_test.go", {|package reader_test
import (
  "net"
  "net/http/httptest"
  "database/sql"
  "github.com/jackc/pgx/v5/pgxpool"
  "github.com/candacelabs/csf/pkg/pgmem"
)
func open() {
  _ = net.ParseIP("203.0.113.1")
  _ = httptest.NewRecorder()
  _, _ = pgxpool.ParseConfig(url)
  _, _ = sql.Open("pgmem", url)
  _ = pgmem.MustNew()
}
|}];
  (* Anti-gaming: a negated tag, a tag-shaped plain comment, an `integration`
     tag and an aliased import are not a way out. *)
  List.iter (fun (label, header) ->
    count label "CS-18-CROSSING" 9 ["services/reader/reader_test.go", header ^ crossing])
    ["a negated acceptance tag", "//go:build !acceptance\n\n";
     "a plain comment naming acceptance", "// acceptance suite\n\n";
     "an integration tag is not the acceptance label", "//go:build integration\n\n"];
  count "an aliased import is still resolved" "CS-18-CROSSING" 1 ["services/reader/reader_test.go", {|package reader_test
import pool "github.com/jackc/pgx/v5/pgxpool"
func open() { _, _ = pool.NewWithConfig(ctx, config) }
|}]

let external_suites () =
  let api = "pkg/widget/widget.go", "package widget\nfunc Render() string { return \"\" }\n" in
  count "exported API with no external package" "CS-18-EXTERNAL" 1 [api];
  count "exported API with only in-package tests" "CS-18-EXTERNAL" 1 [api;
    "pkg/widget/widget_internal_test.go", "package widget\nfunc TestRender(t *testing.T) {}\n"];
  count "an external package with a Test function" "CS-18-EXTERNAL" 0 [api;
    "pkg/widget/widget_test.go", "package widget_test\nfunc TestRender(t *testing.T) {}\n"];
  count "an external package with a Ginkgo spec" "CS-18-EXTERNAL" 0 [api;
    "pkg/widget/widget_suite_test.go", "package widget_test\nvar _ = Describe(\"widget\", func() {})\n"];
  count "no exported API, no requirement" "CS-18-EXTERNAL" 0 [
    "pkg/hidden/hidden.go", "package hidden\nfunc render() string { return \"\" }\n";
    "app/tool/main.go", "package main\nfunc Run() {}\n"];
  count "exported types, values and methods are API" "CS-18-EXTERNAL" 3 [
    "pkg/a/a.go", "package a\ntype Widget struct{}\n";
    "pkg/b/b.go", "package b\nconst (\n  hidden = 1\n  Limit = 2\n)\n";
    "pkg/c/c.go", "package c\ntype widget struct{}\nfunc (w widget) Render() {}\n"];
  (* Anti-gaming: an empty external package file, an external package in
     another directory, and a production file declaring `_test` do not count. *)
  count "an external package with no spec" "CS-18-EXTERNAL" 1 [api;
    "pkg/widget/widget_test.go", "package widget_test\nimport _ \"testing\"\n"];
  count "an external package elsewhere" "CS-18-EXTERNAL" 1 [api;
    "pkg/other/widget_test.go", "package widget_test\nfunc TestRender(t *testing.T) {}\n"];
  let found = findings "CS-18-EXTERNAL" [api; "pkg/widget/a.go", "package widget\n\n\nfunc helper() {}\n"] in
  expect "reported at the first file that exports API, on its package clause"
    (List.map (fun (finding : Source.finding) -> finding.path, finding.line) found = ["pkg/widget/widget.go", 1])

let paths () =
  expect "relative directive paths" (Test_layout.join "services/reader" "../../pkg/store/store.go" = "pkg/store/store.go");
  expect "root-relative directive paths" (Test_layout.join "." "./x.go" = "x.go");
  expect "module resolution" (Test_layout.package_directory modules "x" "github.com/example/public/pkg/store" = Some "pkg/store");
  expect "unknown modules resolve nowhere" (Test_layout.package_directory modules "x" "io" = None)

let () =
  mockgen ();
  crossings ();
  external_suites ();
  paths ();
  print_endline "House lint test-layout rule tests passed"
