// Code generated by csfc from csf/compiler/testdata/golden/slice_planner/slice_planner.csf; DO NOT EDIT.
//
// dispatch_waiting: the ordered decision a dispatch pass makes about one queued
// slice: depends_on, held, contends, paused, rate, capacity, next_pass.

package dispatch

// WaitingReason is one decision a dispatch pass makes about a queued slice.
type WaitingReason string

// The reasons a queued slice does not run, in the order the pass checks them.
const (
	WaitingDependsOn WaitingReason = "depends_on"
	WaitingHeld      WaitingReason = "held"
	WaitingContends  WaitingReason = "contends"
	WaitingPaused    WaitingReason = "paused"
	WaitingRate      WaitingReason = "rate"
	WaitingCapacity  WaitingReason = "capacity"
	WaitingNextPass  WaitingReason = "next_pass"
)

// WaitingReasons is the closed set, in the order the pass checks them.
var WaitingReasons = []WaitingReason{
	WaitingDependsOn,
	WaitingHeld,
	WaitingContends,
	WaitingPaused,
	WaitingRate,
	WaitingCapacity,
	WaitingNextPass,
}

// DecideWaiting is the ordered decision: the first reason whose condition
// holds, and next_pass when none does. It is the generated shape of the
// dispatch pass's waiting switch, so the order lives here and not in a
// hand-written switch.
func DecideWaiting(hasPredecessor, held, hasContender, paused, throttled, atCapacity bool) WaitingReason {
	switch {
	case hasPredecessor:
		return WaitingDependsOn
	case held:
		return WaitingHeld
	case hasContender:
		return WaitingContends
	case paused:
		return WaitingPaused
	case throttled:
		return WaitingRate
	case atCapacity:
		return WaitingCapacity
	default:
		return WaitingNextPass
	}
}
