load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "net",
    srcs = ["network.go"],
    importpath = "github.com/candacelabs/csf/ipc/net",
    visibility = ["//visibility:public"],
)

go_test(
    name = "net_test",
    srcs = [
        "net_suite_test.go",
        "network_test.go",
    ],
    deps = [
        ":net",
        "@com_github_onsi_ginkgo_v2//:ginkgo",
        "@com_github_onsi_gomega//:gomega",
    ],
)
