// Copyright 2026 Candace Labs

package dreamer

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"log/slog"
	"net/http"
	"slices"
	"strings"
	"sync/atomic"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/google/uuid"
	"google.golang.org/protobuf/proto"

	"github.com/candacelabs/csf/csf"
	"github.com/candacelabs/csf/io/inproc"
	grammar "github.com/candacelabs/csf/pkg/cron"
	pb "github.com/candacelabs/csf/proto/candace/brainspine/v1"
	dispatchv1 "github.com/candacelabs/csf/proto/candace/dispatch/v1"
	"github.com/candacelabs/csf/runtime"
	cronservice "github.com/candacelabs/csf/services/cron"
	"github.com/candacelabs/csf/services/dispatch"
	"github.com/candacelabs/csf/services/harness"
)

// IDispatcher is what the dreamer needs of the slice dispatcher: its
// snapshot and graph, AddSlice, and Release for its own visibility holds.
// *dispatch.DispatchService satisfies it.
//
//go:generate go run go.uber.org/mock/mockgen@v0.6.0 -source=dreamer.go -destination=mocks/mock_dreamer.go -package=mocks
type IDispatcher interface {
	CurrentSnapshot(ctx context.Context, input dispatch.SnapshotInput) (dispatch.Snapshot, error)
	List(ctx context.Context, request *dispatchv1.ListSlicesRequest) (*dispatchv1.ListSlicesResponse, error)
	AddSlice(ctx context.Context, input dispatch.AddSliceInput) (dispatch.SliceView, error)
	Release(ctx context.Context, input dispatch.SliceControlInput) (dispatch.Snapshot, error)
}

// IBacklog opens the ticket a generated slice delivers, in CSF's own
// repository. *GitHubBacklog satisfies it.
type IBacklog interface {
	OpenIssue(ctx context.Context, title string, body string) (string, error)
}

// RecordSink receives every record, on the dreamer's goroutine.
type RecordSink func(record Record) error

// SnapshotSink receives every snapshot the dreamer publishes.
type SnapshotSink func(snapshot Snapshot) error

const (
	// TriggerDream is the dreamer's pass, every DreamInterval.
	TriggerDream = "dreamer.dream"
	// TriggerStrategy recomputes the held-out comparison and the strategy
	// once a day; the strategy changes at most once a week, when a week
	// completes.
	TriggerStrategy = "dreamer.strategy"
	// DreamInterval is the cadence of the passes: a slice the dreamer adds is
	// on the Workbench queue for one interval before the next pass releases
	// it to the dispatcher.
	DreamInterval    = 3 * time.Minute
	strategyInterval = 24 * time.Hour
	// SnapshotFile is where the binary writes every published snapshot, under
	// the harness state directory, for the Workbench.
	SnapshotFile = "dreamer.json"
	// RecordFile is where the binary appends every record.
	RecordFile = "dreamer.jsonl"
	// VisibilityHold is the reason the dreamer holds every slice it adds. The
	// next pass releases a slice held with exactly this reason; an operator's
	// hold replaces the reason, and the dreamer never releases it.
	VisibilityHold = "dreamer: shown on the Workbench queue for one dreamer pass before the dispatcher may launch it"
	// ProvenancePrefix opens the provenance source of every slice the
	// dreamer adds.
	ProvenancePrefix = "dreamer"

	ownerName          = "dreamer"
	decisionsShown     = 20
	rankedShown        = 10
	sliceIDFormat      = "dream-%s-%s"
	branchFormat       = "dev/%s"
	provenanceFormat   = "%s: %s, rank %d of %d, score %.3g"
	sliceIDHashBytes   = 4
	maxReasonBytes     = 4096
	briefHeaderFormat  = "# %s\n\nGenerated by the dreamer from the %s source: rank %d of %d, score %.3g = frequency %.3g per week × fixability %.3g × exploration %.3g.\n\nFrequency: %s.\n\nFixability: %s.\n"
	briefEvidence      = "\n## Evidence\n\n"
	briefAcceptance    = "\n## Acceptance\n\n"
	briefItemFormat    = "- %s\n"
	briefJoin          = "\n\n"
	issueFooterFormat  = "\n\nOpened by the dreamer for slice `%s`; its decision record names the inputs of the rank.\n"
	sourceErrorFormat  = "%s: %v"
	assignmentIDFormat = "dreamer#%s"
)

// The errors the service reports.
var (
	ErrInvalidOption  = errors.New("dreamer: invalid option")
	ErrNoDispatcher   = errors.New("dreamer: a dispatcher is required")
	ErrNoRecipe       = errors.New("dreamer: a recipe with a workspace is required")
	ErrNotStarted     = errors.New("dreamer: not started")
	ErrInvalidControl = errors.New("dreamer: invalid control")
)

// Option configures a [Dreamer].
type Option func(dreamer *Dreamer) error

// WithDispatcher grants the slice dispatcher the dreamer reads and adds
// through. Required.
func WithDispatcher(dispatcher IDispatcher) Option {
	return func(dreamer *Dreamer) error {
		if dispatcher == nil {
			return ErrNoDispatcher
		}
		dreamer.dispatcher = dispatcher
		return nil
	}
}

// WithRecipe is the recipe every generated slice starts from: its agent,
// model and workspace. Its task, when set, opens every brief. Required.
func WithRecipe(recipe *pb.AgentAssignmentRecipe) Option {
	return func(dreamer *Dreamer) error {
		if recipe.GetWorkspace() == nil {
			return ErrNoRecipe
		}
		dreamer.recipe = proto.Clone(recipe).(*pb.AgentAssignmentRecipe)
		return nil
	}
}

// WithBacklog grants the ticket capability a generated slice without a ticket
// opens one through. Without it such a candidate is skipped.
func WithBacklog(backlog IBacklog) Option {
	return func(dreamer *Dreamer) error {
		if backlog == nil {
			return fmt.Errorf("%w: nil backlog", ErrInvalidOption)
		}
		dreamer.backlog = backlog
		return nil
	}
}

// WithSource registers one source of work.
func WithSource(source Source) Option {
	return func(dreamer *Dreamer) error {
		if source.Name == "" || source.Find == nil {
			return fmt.Errorf("%w: a source needs a name and a find function", ErrInvalidOption)
		}
		dreamer.sources = append(dreamer.sources, source)
		return nil
	}
}

// WithComparison grants the held-out comparison Strategize runs.
func WithComparison(compare func(ctx context.Context) (Comparison, error)) Option {
	return func(dreamer *Dreamer) error {
		if compare == nil {
			return fmt.Errorf("%w: nil comparison", ErrInvalidOption)
		}
		dreamer.compare = compare
		return nil
	}
}

// WithHistory replays the records an earlier process wrote, oldest first:
// the pause, the strategy, the slices added and the tickets opened.
func WithHistory(records []Record) Option {
	return func(dreamer *Dreamer) error {
		dreamer.history = append(dreamer.history, records...)
		return nil
	}
}

// WithRecordSink receives every record.
func WithRecordSink(sink RecordSink) Option {
	return func(dreamer *Dreamer) error {
		if sink == nil {
			return fmt.Errorf("%w: nil record sink", ErrInvalidOption)
		}
		dreamer.records = sink
		return nil
	}
}

// WithSnapshotSink receives every published snapshot.
func WithSnapshotSink(sink SnapshotSink) Option {
	return func(dreamer *Dreamer) error {
		if sink == nil {
			return fmt.Errorf("%w: nil snapshot sink", ErrInvalidOption)
		}
		dreamer.sink = sink
		return nil
	}
}

// WithClock replaces the clock.
func WithClock(clock harness.IClock) Option {
	return func(dreamer *Dreamer) error {
		if clock == nil {
			return fmt.Errorf("%w: nil clock", ErrInvalidOption)
		}
		dreamer.clock = clock
		return nil
	}
}

// WithLogger receives the service's records.
func WithLogger(logger *slog.Logger) Option {
	return func(dreamer *Dreamer) error {
		if logger == nil {
			return fmt.Errorf("%w: nil logger", ErrInvalidOption)
		}
		dreamer.logger = logger
		return nil
	}
}

// Outcome is how a pass ended.
type Outcome string

// The outcomes of a pass.
const (
	OutcomePaused           Outcome = "paused"
	OutcomeDispatcherPaused Outcome = "dispatcher_paused"
	OutcomeLimited          Outcome = "limited"
	OutcomeFull             Outcome = "full"
	OutcomeFilled           Outcome = "filled"
	OutcomeDry              Outcome = "dry"
)

// Added is one slice a pass added.
type Added struct {
	SliceID   string     `json:"slice_id"`
	Source    SourceName `json:"source"`
	Key       string     `json:"key"`
	Rank      int        `json:"rank"`
	Score     float64    `json:"score"`
	TicketURL string     `json:"ticket_url"`
	Title     string     `json:"title"`
}

// Decision is one pass: what it read, why it did what it did, and what it
// added and released.
type Decision struct {
	Outcome  Outcome          `json:"outcome"`
	Reason   string           `json:"reason"`
	Target   Target           `json:"target"`
	Limits   []dispatch.Limit `json:"limits,omitempty"`
	Explore  float64          `json:"explore"`
	Ranked   []Ranked         `json:"ranked,omitempty"`
	Total    int              `json:"candidates"`
	Added    []Added          `json:"added,omitempty"`
	Released []string         `json:"released,omitempty"`
	// Findings are the sources that failed and anything skipped, each with
	// why.
	Findings []string `json:"findings,omitempty"`
}

// ControlAction is a pause or a resume of the dreamer.
type ControlAction string

// The controls.
const (
	ControlPause  ControlAction = "pause"
	ControlResume ControlAction = "resume"
)

// Control is one recorded control.
type Control struct {
	Action ControlAction `json:"action"`
	Reason string        `json:"reason"`
}

// RecordKind says which part of a record is set.
type RecordKind string

// The record kinds.
const (
	RecordDecision RecordKind = "decision"
	RecordControl  RecordKind = "control"
	RecordStrategy RecordKind = "strategy"
)

// Record is one typed record the dreamer writes: a pass's decision, a
// control, or a strategy with the comparison it followed.
type Record struct {
	At       time.Time   `json:"at"`
	Kind     RecordKind  `json:"kind"`
	Decision *Decision   `json:"decision,omitempty"`
	Control  *Control    `json:"control,omitempty"`
	Strategy *Comparison `json:"strategy,omitempty"`
}

// Snapshot is what the Workbench shows of the dreamer: whether it is paused,
// the strategy and its comparison, how many slices each source generated,
// and the latest decisions, newest first.
type Snapshot struct {
	At          time.Time          `json:"at"`
	Paused      bool               `json:"paused"`
	PauseReason string             `json:"pause_reason,omitempty"`
	Explore     float64            `json:"explore"`
	Strategy    *Comparison        `json:"strategy,omitempty"`
	Generated   map[SourceName]int `json:"generated"`
	Decisions   []Record           `json:"decisions"`
}

// state is the dreamer's own, held by its owner goroutine.
type state struct {
	paused    string
	strategy  *Comparison
	added     map[string]Added
	decisions []Record
}

// command is one unit of work the owner runs.
type command func(ctx context.Context, current *state)

// Dreamer is the service. One goroutine owns its state and runs every pass,
// control and strategy in turn; the latest snapshot is published for reads.
type Dreamer struct {
	dispatcher IDispatcher
	recipe     *pb.AgentAssignmentRecipe
	backlog    IBacklog
	sources    []Source
	compare    func(ctx context.Context) (Comparison, error)
	history    []Record
	records    RecordSink
	sink       SnapshotSink
	clock      harness.IClock
	logger     *slog.Logger
	commands   *inproc.Queue[command]
	stopped    chan struct{}
	latest     atomic.Pointer[Snapshot]
}

var _ runtime.IService = (*Dreamer)(nil)

// NewDreamer validates the whole option set before building the service.
// [WithDispatcher] and [WithRecipe] are required.
func NewDreamer(options ...Option) (*Dreamer, error) {
	dreamer := &Dreamer{
		clock:    harness.SystemClock{},
		logger:   slog.New(slog.DiscardHandler),
		commands: inproc.NewQueue[command](),
		stopped:  make(chan struct{}),
	}
	for _, option := range options {
		if option == nil {
			return nil, fmt.Errorf("%w: nil option", ErrInvalidOption)
		}
		if err := option(dreamer); err != nil {
			return nil, err
		}
	}
	if dreamer.dispatcher == nil {
		return nil, ErrNoDispatcher
	}
	if dreamer.recipe == nil {
		return nil, ErrNoRecipe
	}
	return dreamer, nil
}

// Start replays the history and starts the owner goroutine on the scope.
func (dreamer *Dreamer) Start(scope *runtime.Scope) error {
	current := &state{added: map[string]Added{}}
	for _, record := range dreamer.history {
		current.replay(record)
	}
	dreamer.publish(current)
	return scope.GoOwner(ownerName, func(ctx context.Context) error {
		defer close(dreamer.stopped)
		for {
			next, err := dreamer.commands.Pop(ctx)
			if err != nil {
				dreamer.commands.Close()
				return nil
			}
			next(ctx, current)
		}
	})
}

// replay applies one earlier record.
func (current *state) replay(record Record) {
	switch record.Kind {
	case RecordControl:
		if record.Control.Action == ControlPause {
			current.paused = record.Control.Reason
		} else {
			current.paused = ""
		}
	case RecordStrategy:
		current.strategy = record.Strategy
	case RecordDecision:
		for _, added := range record.Decision.Added {
			current.added[added.SliceID] = added
		}
	}
	if record.Kind != RecordStrategy {
		current.decisions = append([]Record{record}, current.decisions...)
		current.decisions = current.decisions[:min(len(current.decisions), decisionsShown)]
	}
}

// command runs work on the owner and waits for its result.
func (dreamer *Dreamer) command(ctx context.Context, work func(ctx context.Context, current *state) error) error {
	reply := make(chan error, 1)
	if err := dreamer.commands.Push(func(ctx context.Context, current *state) { reply <- work(ctx, current) }); err != nil {
		return ErrNotStarted
	}
	select {
	case err := <-reply:
		return err
	case <-ctx.Done():
		return context.Cause(ctx)
	case <-dreamer.stopped:
		return ErrNotStarted
	}
}

// record hands one record to the sink and keeps it in the state.
func (dreamer *Dreamer) record(current *state, record Record) {
	current.replay(record)
	if dreamer.records != nil {
		if err := dreamer.records(record); err != nil {
			dreamer.logger.Warn("dreamer: record not written", "kind", record.Kind, "error", err)
		}
	}
	dreamer.publish(current)
}

// publish stores the snapshot for reads and hands it to the sink.
func (dreamer *Dreamer) publish(current *state) {
	snapshot := Snapshot{
		At: dreamer.clock.Now(), Paused: current.paused != "", PauseReason: current.paused,
		Explore: current.explore(), Strategy: current.strategy, Generated: map[SourceName]int{},
		Decisions: slices.Clone(current.decisions),
	}
	for _, added := range current.added {
		snapshot.Generated[added.Source]++
	}
	dreamer.latest.Store(&snapshot)
	if dreamer.sink != nil {
		if err := dreamer.sink(snapshot); err != nil {
			dreamer.logger.Warn("dreamer: snapshot not published", "error", err)
		}
	}
}

// explore is the strategy's exploration weight, 1 before any strategy.
func (current *state) explore() float64 {
	if current.strategy == nil {
		return 1
	}
	return current.strategy.Explore
}

// CurrentSnapshot reports the latest published snapshot.
func (dreamer *Dreamer) CurrentSnapshot(_ context.Context, _ SnapshotInput) (Snapshot, error) {
	snapshot := dreamer.latest.Load()
	if snapshot == nil {
		return Snapshot{}, ErrNotStarted
	}
	return *snapshot, nil
}

// SnapshotInput asks for the dreamer's snapshot; it has no fields.
type SnapshotInput struct{}

// ControlInput is a pause or a resume of the dreamer.
type ControlInput struct {
	Reason string `json:"reason" jsonschema:"why, recorded with the control"`
}

// Pause stops every pass from adding or releasing anything until Resume.
func (dreamer *Dreamer) Pause(ctx context.Context, input ControlInput) (Snapshot, error) {
	return dreamer.control(ctx, Control{Action: ControlPause, Reason: input.Reason})
}

// Resume lets the passes act again.
func (dreamer *Dreamer) Resume(ctx context.Context, input ControlInput) (Snapshot, error) {
	return dreamer.control(ctx, Control{Action: ControlResume, Reason: input.Reason})
}

func (dreamer *Dreamer) control(ctx context.Context, control Control) (Snapshot, error) {
	control.Reason = strings.TrimSpace(control.Reason)
	if control.Reason == "" || len(control.Reason) > maxReasonBytes {
		return Snapshot{}, fmt.Errorf("%w: a reason of 1 to %d bytes is required", ErrInvalidControl, maxReasonBytes)
	}
	err := dreamer.command(ctx, func(_ context.Context, current *state) error {
		dreamer.record(current, Record{At: dreamer.clock.Now(), Kind: RecordControl, Control: &control})
		dreamer.logger.Info("dreamer: control", "action", control.Action, "reason", control.Reason)
		return nil
	})
	if err != nil {
		return Snapshot{}, err
	}
	return dreamer.CurrentSnapshot(ctx, SnapshotInput{})
}

// DreamInput asks for one pass now; it has no fields.
type DreamInput struct{}

// Dream is one pass; it returns the decision it recorded.
func (dreamer *Dreamer) Dream(ctx context.Context, _ DreamInput) (Decision, error) {
	var decision Decision
	err := dreamer.command(ctx, func(ctx context.Context, current *state) error {
		var err error
		decision, err = dreamer.pass(ctx, current)
		if err != nil {
			return err
		}
		if current.repeats(decision) {
			return nil
		}
		dreamer.record(current, Record{At: dreamer.clock.Now(), Kind: RecordDecision, Decision: &decision})
		dreamer.logger.Info("dreamer: pass", "outcome", decision.Outcome, "ready", decision.Target.Ready, "target", decision.Target.Target, "added", len(decision.Added), "released", len(decision.Released))
		return nil
	})
	return decision, err
}

// repeats reports whether a pass changed nothing the newest decision does
// not already say, so an idle dreamer does not grow its record every pass.
func (current *state) repeats(decision Decision) bool {
	for _, record := range current.decisions {
		if record.Kind != RecordDecision {
			continue
		}
		previous := record.Decision
		return previous.Outcome == decision.Outcome && previous.Reason == decision.Reason &&
			previous.Target.Ready == decision.Target.Ready && previous.Target.Target == decision.Target.Target &&
			len(decision.Added)+len(decision.Released)+len(decision.Findings) == 0
	}
	return false
}

// pass is one pass on the owner.
func (dreamer *Dreamer) pass(ctx context.Context, current *state) (Decision, error) {
	decision := Decision{Explore: current.explore()}
	if current.paused != "" {
		decision.Outcome, decision.Reason = OutcomePaused, "the dreamer is paused: "+current.paused
		return decision, nil
	}
	snapshot, err := dreamer.dispatcher.CurrentSnapshot(ctx, dispatch.SnapshotInput{})
	if err != nil {
		return decision, err
	}
	if snapshot.Paused {
		decision.Outcome, decision.Reason = OutcomeDispatcherPaused, "the dispatcher is paused: "+snapshot.PauseReason
		return decision, nil
	}
	for _, view := range snapshot.Held {
		if _, own := current.added[view.SliceID]; !own || view.Held != VisibilityHold {
			continue
		}
		if _, err := dreamer.dispatcher.Release(ctx, dispatch.SliceControlInput{SliceID: view.SliceID, Reason: "dreamer: shown on the Workbench queue for one pass; the dispatcher may launch it"}); err != nil {
			decision.Findings = append(decision.Findings, fmt.Sprintf(sourceErrorFormat, view.SliceID, err))
			continue
		}
		decision.Released = append(decision.Released, view.SliceID)
	}
	if len(decision.Released) > 0 {
		if snapshot, err = dreamer.dispatcher.CurrentSnapshot(ctx, dispatch.SnapshotInput{}); err != nil {
			return decision, err
		}
	}
	graph, err := dreamer.dispatcher.List(ctx, &dispatchv1.ListSlicesRequest{})
	if err != nil {
		return decision, err
	}
	durations, outcomes := measureGraph(graph.GetNodes(), current.added)
	decision.Target = DeriveTarget(snapshot, durations, DreamInterval, VisibilityHold)
	if binding := zeroLimits(snapshot.Limits); len(binding) > 0 {
		decision.Outcome, decision.Limits = OutcomeLimited, binding
		decision.Reason = fmt.Sprintf("%d of the dispatcher's limits admit no launch now, so nothing is added", len(binding))
		return decision, nil
	}
	if decision.Target.Ready >= decision.Target.Target {
		decision.Outcome, decision.Reason = OutcomeFull, "the ready frontier is as long as the admission can use"
		return decision, nil
	}
	world := World{Now: dreamer.clock.Now(), Slices: graph.GetNodes()}
	candidates := dreamer.gather(ctx, world, &decision)
	ranked := Rank(candidates, outcomes, decision.Explore)
	decision.Total = len(ranked)
	decision.Ranked = ranked[:min(len(ranked), rankedShown)]
	ready := decision.Target.Ready
	for _, entry := range ranked {
		if ready >= decision.Target.Target {
			break
		}
		added, err := dreamer.add(ctx, entry, len(ranked))
		if err != nil {
			decision.Findings = append(decision.Findings, fmt.Sprintf(sourceErrorFormat, entry.Key, err))
			continue
		}
		current.added[added.SliceID] = added
		decision.Added = append(decision.Added, added)
		ready++
	}
	decision.Outcome, decision.Reason = OutcomeFilled, fmt.Sprintf("added %d of the %d the frontier was short", len(decision.Added), decision.Target.Target-decision.Target.Ready)
	if len(ranked) == 0 {
		decision.Outcome, decision.Reason = OutcomeDry, "no source found work that is not already in the graph"
	}
	return decision, nil
}

// gather asks the primary sources, then the fallbacks when the primaries
// found nothing, and drops what the graph already holds: the same slice, or
// another slice delivering the same ticket.
func (dreamer *Dreamer) gather(ctx context.Context, world World, decision *Decision) []Candidate {
	existing, tickets := map[string]bool{}, map[string]bool{}
	for _, node := range world.Slices {
		existing[node.GetSlice().GetSliceId()] = true
		tickets[node.GetSlice().GetRecipe().GetTicketUrl()] = true
	}
	for _, fallback := range []bool{false, true} {
		var found []Candidate
		for _, source := range dreamer.sources {
			if source.Fallback != fallback {
				continue
			}
			candidates, err := source.Find(ctx, world)
			if err != nil {
				decision.Findings = append(decision.Findings, fmt.Sprintf(sourceErrorFormat, source.Name, err))
				continue
			}
			for _, candidate := range candidates {
				if existing[SliceID(candidate)] || (candidate.TicketURL != "" && tickets[candidate.TicketURL]) {
					continue
				}
				found = append(found, candidate)
			}
		}
		if len(found) > 0 {
			return found
		}
	}
	return nil
}

// SliceID is the slice a candidate becomes: its source and a digest of its
// key, so the same work is never added twice.
func SliceID(candidate Candidate) string {
	digest := sha256.Sum256([]byte(candidate.Key))
	return fmt.Sprintf(sliceIDFormat, candidate.Source, hex.EncodeToString(digest[:sliceIDHashBytes]))
}

// add opens the candidate's ticket when it has none and adds its slice held
// for visibility, with its source and rank as the provenance.
func (dreamer *Dreamer) add(ctx context.Context, entry Ranked, total int) (Added, error) {
	id := SliceID(entry.Candidate)
	brief := Brief(entry, total)
	ticket := entry.TicketURL
	if ticket == "" {
		if dreamer.backlog == nil {
			return Added{}, errors.New("no ticket and no backlog to open one in")
		}
		opened, err := dreamer.backlog.OpenIssue(ctx, entry.Title, brief+fmt.Sprintf(issueFooterFormat, id))
		if err != nil {
			return Added{}, err
		}
		ticket = opened
	}
	recipe := proto.Clone(dreamer.recipe).(*pb.AgentAssignmentRecipe)
	recipe.AssignmentId = uuid.NewSHA1(uuid.NameSpaceOID, fmt.Appendf(nil, assignmentIDFormat, id)).String()
	recipe.TicketUrl = ticket
	recipe.Task = strings.TrimSpace(strings.Join([]string{recipe.GetTask(), brief}, briefJoin))
	recipe.Workspace.Branch = fmt.Sprintf(branchFormat, id)
	recipe.Workspace.BriefPath = ""
	recipe.Workspace.PullRequestTitle = entry.Title
	if recipe.Agent != nil {
		recipe.Agent.DisplayName = entry.Title
	}
	source := fmt.Sprintf(provenanceFormat, ProvenancePrefix, entry.Source, entry.Rank, total, entry.Score)
	if _, err := dreamer.dispatcher.AddSlice(ctx, dispatch.AddSliceInput{
		SliceID: id, Title: entry.Title, TicketURL: ticket, Recipe: recipe, Source: source, Hold: VisibilityHold,
	}); err != nil {
		return Added{}, err
	}
	return Added{SliceID: id, Source: entry.Source, Key: entry.Key, Rank: entry.Rank, Score: entry.Score, TicketURL: ticket, Title: entry.Title}, nil
}

// Brief is the task a generated slice's session runs after the recipe's own:
// what it is, why it ranks where it does, its evidence and its acceptance.
func Brief(entry Ranked, total int) string {
	var brief strings.Builder
	fmt.Fprintf(&brief, briefHeaderFormat, entry.Title, entry.Source, entry.Rank, total, entry.Score,
		entry.Frequency, entry.Fixability, entry.Explore, entry.FrequencyDerivation, entry.FixabilityDerivation)
	brief.WriteString(briefEvidence)
	for _, line := range entry.Evidence {
		fmt.Fprintf(&brief, briefItemFormat, line)
	}
	brief.WriteString(briefAcceptance)
	for _, line := range entry.Acceptance {
		fmt.Fprintf(&brief, briefItemFormat, line)
	}
	return brief.String()
}

// measureGraph reads the graph: the enqueue-to-merge durations of every
// merged slice, and the outcomes of the dreamer's own slices by source.
func measureGraph(nodes []*dispatchv1.SliceNode, added map[string]Added) ([]time.Duration, map[SourceName]Outcomes) {
	var durations []time.Duration
	outcomes := map[SourceName]Outcomes{}
	for _, node := range nodes {
		state := node.GetState()
		if state == dispatchv1.SliceState_SLICE_STATE_MERGED && node.GetCreatedAt() != nil && node.GetUpdatedAt() != nil {
			durations = append(durations, node.GetUpdatedAt().AsTime().Sub(node.GetCreatedAt().AsTime()))
		}
		own, ok := added[node.GetSlice().GetSliceId()]
		if !ok {
			continue
		}
		outcome := outcomes[own.Source]
		switch state {
		case dispatchv1.SliceState_SLICE_STATE_MERGED:
			outcome.Fixed++
			outcome.Attempted++
		case dispatchv1.SliceState_SLICE_STATE_FAILED, dispatchv1.SliceState_SLICE_STATE_CANCELED:
			outcome.Attempted++
		}
		outcomes[own.Source] = outcome
	}
	return durations, outcomes
}

// StrategizeInput asks for the strategy to be recomputed now; it has no
// fields.
type StrategizeInput struct{}

// Strategize runs the held-out comparison and records the strategy it sets.
func (dreamer *Dreamer) Strategize(ctx context.Context, _ StrategizeInput) (Comparison, error) {
	if dreamer.compare == nil {
		return Comparison{}, fmt.Errorf("%w: no comparison was granted", ErrInvalidOption)
	}
	comparison, err := dreamer.compare(ctx)
	if err != nil {
		return Comparison{}, err
	}
	err = dreamer.command(ctx, func(_ context.Context, current *state) error {
		dreamer.record(current, Record{At: dreamer.clock.Now(), Kind: RecordStrategy, Strategy: &comparison})
		return nil
	})
	return comparison, err
}

// Triggers declare the pass and the daily strategy for the cron service.
func (dreamer *Dreamer) Triggers() []cronservice.Option {
	triggers := []cronservice.Option{
		cronservice.WithTrigger(TriggerDream, grammar.Spec(grammar.Every(DreamInterval)), func(ctx context.Context, _ cronservice.Occurrence) error {
			_, err := dreamer.Dream(ctx, DreamInput{})
			return err
		}),
	}
	if dreamer.compare != nil {
		triggers = append(triggers, cronservice.WithTrigger(TriggerStrategy, grammar.Spec(grammar.Every(strategyInterval)), func(ctx context.Context, _ cronservice.Occurrence) error {
			_, err := dreamer.Strategize(ctx, StrategizeInput{})
			return err
		}))
	}
	return triggers
}

// The dreamer's typed operations: each is one MCP tool on the CSF service
// and one HTTP route.
const (
	SnapshotTool   = "DreamerSnapshot"
	DreamTool      = "Dream"
	PauseTool      = "PauseDreamer"
	ResumeTool     = "ResumeDreamer"
	StrategizeTool = "DreamerStrategy"

	SnapshotPath   = "/api/dreamer"
	DreamPath      = "/api/dreamer/dream"
	PausePath      = "/api/dreamer/pause"
	ResumePath     = "/api/dreamer/resume"
	StrategizePath = "/api/dreamer/strategy"
)

func (dreamer *Dreamer) operations() []csf.Operation {
	return []csf.Operation{
		csf.NewOperation(SnapshotTool, "Read the dreamer's snapshot: paused or not, the strategy with its held-out and in-sample comparison, the slices each source generated, and the latest decision records (why each slice was added, with its rank and every input).",
			http.MethodGet, SnapshotPath, dreamer.CurrentSnapshot),
		csf.NewOperation(DreamTool, "Run one dreamer pass now: it fills the slice dispatcher's ready frontier up to the target its admission derives, from the ranked sources, and returns the decision it recorded.",
			http.MethodPost, DreamPath, dreamer.Dream),
		csf.NewOperation(PauseTool, "Pause the dreamer: its passes add and release nothing until it is resumed. The reason is recorded.",
			http.MethodPost, PausePath, dreamer.Pause),
		csf.NewOperation(ResumeTool, "Resume the dreamer. The reason is recorded.",
			http.MethodPost, ResumePath, dreamer.Resume),
		csf.NewOperation(StrategizeTool, "Recompute the held-out comparison and the strategy now, and return both numbers: the weekly struggle factor on the runs the dreamer chooses work from and on the held-out runs it never reads.",
			http.MethodPost, StrategizePath, dreamer.Strategize),
	}
}

// Tools is every operation as an MCP tool for the CSF service.
func (dreamer *Dreamer) Tools() []csf.Option { return csf.OperationTools(dreamer.operations()) }

// Register mounts every operation's HTTP route on the caller's router.
func (dreamer *Dreamer) Register(router gin.IRouter) {
	csf.RegisterOperations(router, dreamer.operations())
}
