// Code generated by MockGen. DO NOT EDIT.
// Source: clock.go
//
// Generated by this command:
//
//	mockgen -source=clock.go -destination=mocks/mock_clock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockIClock is a mock of IClock interface.
type MockIClock struct {
	ctrl     *gomock.Controller
	recorder *MockIClockMockRecorder
	isgomock struct{}
}

// MockIClockMockRecorder is the mock recorder for MockIClock.
type MockIClockMockRecorder struct {
	mock *MockIClock
}

// NewMockIClock creates a new mock instance.
func NewMockIClock(ctrl *gomock.Controller) *MockIClock {
	mock := &MockIClock{ctrl: ctrl}
	mock.recorder = &MockIClockMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIClock) EXPECT() *MockIClockMockRecorder {
	return m.recorder
}

// After mocks base method.
func (m *MockIClock) After(d time.Duration) <-chan time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "After", d)
	ret0, _ := ret[0].(<-chan time.Time)
	return ret0
}

// After indicates an expected call of After.
func (mr *MockIClockMockRecorder) After(d any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "After", reflect.TypeOf((*MockIClock)(nil).After), d)
}

// Now mocks base method.
func (m *MockIClock) Now() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Now")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// Now indicates an expected call of Now.
func (mr *MockIClockMockRecorder) Now() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Now", reflect.TypeOf((*MockIClock)(nil).Now))
}
