// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/candacelabs/csf/io/ipc/docker (interfaces: IServices)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_services.go -package=mocks github.com/candacelabs/csf/io/ipc/docker IServices
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	docker "github.com/candacelabs/csf/io/ipc/docker"
	gomock "go.uber.org/mock/gomock"
)

// MockIServices is a mock of IServices interface.
type MockIServices struct {
	ctrl     *gomock.Controller
	recorder *MockIServicesMockRecorder
	isgomock struct{}
}

// MockIServicesMockRecorder is the mock recorder for MockIServices.
type MockIServicesMockRecorder struct {
	mock *MockIServices
}

// NewMockIServices creates a new mock instance.
func NewMockIServices(ctrl *gomock.Controller) *MockIServices {
	mock := &MockIServices{ctrl: ctrl}
	mock.recorder = &MockIServicesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIServices) EXPECT() *MockIServicesMockRecorder {
	return m.recorder
}

// EnsureService mocks base method.
func (m *MockIServices) EnsureService(ctx context.Context, spec docker.ServiceSpec) (docker.ServiceState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureService", ctx, spec)
	ret0, _ := ret[0].(docker.ServiceState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnsureService indicates an expected call of EnsureService.
func (mr *MockIServicesMockRecorder) EnsureService(ctx, spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureService", reflect.TypeOf((*MockIServices)(nil).EnsureService), ctx, spec)
}

// InspectService mocks base method.
func (m *MockIServices) InspectService(ctx context.Context, name string) (docker.ServiceState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InspectService", ctx, name)
	ret0, _ := ret[0].(docker.ServiceState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InspectService indicates an expected call of InspectService.
func (mr *MockIServicesMockRecorder) InspectService(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InspectService", reflect.TypeOf((*MockIServices)(nil).InspectService), ctx, name)
}

// StopService mocks base method.
func (m *MockIServices) StopService(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopService", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// StopService indicates an expected call of StopService.
func (mr *MockIServicesMockRecorder) StopService(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopService", reflect.TypeOf((*MockIServices)(nil).StopService), ctx, name)
}
