;; ////////////////////////////////////////////////////////////
;; Code generated by CandaceCodegen v0.1.0-dev; the _cgen suffix marks generated files. DO NOT EDIT.
;; ===== DO NOT EDIT =====
;; Edit the source definition or generator, then regenerate this file.
;; Source: csf/compiler/architecture/language.ebnf
;; Source: csf/compiler/architecture/frontend_lexer.ml
;; Generator: csf/compiler/architecture/highlight_codegen.ml
;; Regeneration owner: //csf/compiler/architecture:highlight_codegen
;; Regenerate: bash csf/editor/generate.sh write
;; ////////////////////////////////////////////////////////////
(comment) @comment
(string) @string
(integer) @number
(identifier) @variable
[
  "adapter"
  "allowed"
  "architecture"
  "borrowed"
  "boundary"
  "call"
  "channel"
  "connect"
  "device"
  "dir"
  "entrypoint"
  "existing"
  "external"
  "gateway"
  "generated"
  "go"
  "in"
  "in_process"
  "ipc"
  "kernel"
  "kind"
  "lazy"
  "library"
  "lifecycle"
  "manager"
  "net"
  "pending"
  "planned"
  "process"
  "remote"
  "requires"
  "resource"
  "scan"
  "scope"
  "scoped"
  "service"
  "source"
  "state"
  "subprocess"
  "test"
  "tier"
  "under"
  "verification"
  "version"
  "via"
] @keyword
[
  "["
  "]"
  "{"
  "}"
] @punctuation.bracket
[
  ","
  ";"
] @punctuation.delimiter
[
  "->"
] @operator
