// Code generated by MockGen. DO NOT EDIT.
// Source: registry.go
//
// Generated by this command:
//
//	mockgen -source=registry.go -destination=mock_registry_test.go -package=relay_test
//

// Package relay_test is a generated GoMock package.
package relay_test

import (
	context "context"
	reflect "reflect"

	relay "github.com/candacelabs/csf/services/relay"
	gomock "go.uber.org/mock/gomock"
)

// MockIRegistry is a mock of IRegistry interface.
type MockIRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockIRegistryMockRecorder
	isgomock struct{}
}

// MockIRegistryMockRecorder is the mock recorder for MockIRegistry.
type MockIRegistryMockRecorder struct {
	mock *MockIRegistry
}

// NewMockIRegistry creates a new mock instance.
func NewMockIRegistry(ctrl *gomock.Controller) *MockIRegistry {
	mock := &MockIRegistry{ctrl: ctrl}
	mock.recorder = &MockIRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRegistry) EXPECT() *MockIRegistryMockRecorder {
	return m.recorder
}

// Locate mocks base method.
func (m *MockIRegistry) Locate(ctx context.Context, addressKey string) (relay.Registration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Locate", ctx, addressKey)
	ret0, _ := ret[0].(relay.Registration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Locate indicates an expected call of Locate.
func (mr *MockIRegistryMockRecorder) Locate(ctx, addressKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Locate", reflect.TypeOf((*MockIRegistry)(nil).Locate), ctx, addressKey)
}

// Register mocks base method.
func (m *MockIRegistry) Register(ctx context.Context, registration relay.Registration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, registration)
	ret0, _ := ret[0].(error)
	return ret0
}

// Register indicates an expected call of Register.
func (mr *MockIRegistryMockRecorder) Register(ctx, registration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockIRegistry)(nil).Register), ctx, registration)
}

// Resolve mocks base method.
func (m *MockIRegistry) Resolve(ctx context.Context, agent relay.AgentID) (relay.Registration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", ctx, agent)
	ret0, _ := ret[0].(relay.Registration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resolve indicates an expected call of Resolve.
func (mr *MockIRegistryMockRecorder) Resolve(ctx, agent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockIRegistry)(nil).Resolve), ctx, agent)
}
