load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "argv",
    srcs = ["argv.go"],
    importpath = "github.com/candacelabs/csf/pkg/argv",
    visibility = ["//visibility:public"],
)

go_test(
    name = "argv_test",
    srcs = [
        "argv_internal_test.go",
        "argv_suite_test.go",
        "argv_test.go",
    ],
    embed = [":argv"],
    deps = [
        "@com_github_onsi_ginkgo_v2//:ginkgo",
        "@com_github_onsi_gomega//:gomega",
    ],
)
