// Code generated by protoc-gen-liquidproto. DO NOT EDIT.
// versions:
// 	protoc-gen-liquidproto v0.1.0
// 	protoc                 v7.35.1
// source: candace/agent/v1/agent.proto

package agentv1

import (
	fmt "fmt"
	liquidproto "github.com/candacelabs/csf/pkg/liquidproto"
	regexp "regexp"
)

var (
	_liquidAgentReferenceUriRe0     = regexp.MustCompile("^[a-z][a-z0-9+.-]*:[^ ]+$")
	_liquidAgentMessageInReplyToRe0 = regexp.MustCompile("^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$")
)

// ValidateAgentReference checks this message's annotated fields; it does not recurse.
// A failed predicate returns *liquidproto.Error. Nil input also returns an error.
func ValidateAgentReference(message *AgentReference) error {
	if message == nil {
		return fmt.Errorf("ValidateAgentReference: nil *AgentReference")
	}
	if !(len(message.Label) >= 1 && len(message.Label) <= 256) {
		return &liquidproto.Error{
			Message:   "candace.agent.v1.AgentReference",
			Field:     "label",
			Predicate: "len(this) >= 1 && len(this) <= 256",
			Value:     message.Label,
		}
	}
	if !(len(message.Uri) <= 2048 && _liquidAgentReferenceUriRe0.MatchString(message.Uri)) {
		return &liquidproto.Error{
			Message:   "candace.agent.v1.AgentReference",
			Field:     "uri",
			Predicate: "len(this) <= 2048 && matches(this, `^[a-z][a-z0-9+.-]*:[^ ]+$`)",
			Value:     message.Uri,
		}
	}
	return nil
}

// ValidateAgentMessage checks this message's annotated fields and opted-in nested messages.
// A failed predicate returns *liquidproto.Error. Nil input also returns an error.
func ValidateAgentMessage(message *AgentMessage) error {
	if message == nil {
		return fmt.Errorf("ValidateAgentMessage: nil *AgentMessage")
	}
	if !(message.Kind >= 1 && message.Kind <= 4) {
		return &liquidproto.Error{
			Message:   "candace.agent.v1.AgentMessage",
			Field:     "kind",
			Predicate: "this >= 1 && this <= 4",
			Value:     message.Kind,
		}
	}
	if !(len(message.Text) >= 1 && len(message.Text) <= 16384) {
		return &liquidproto.Error{
			Message:   "candace.agent.v1.AgentMessage",
			Field:     "text",
			Predicate: "len(this) >= 1 && len(this) <= 16384",
			Value:     message.Text,
		}
	}
	if !(len(message.InReplyTo) == 0 || _liquidAgentMessageInReplyToRe0.MatchString(message.InReplyTo)) {
		return &liquidproto.Error{
			Message:   "candace.agent.v1.AgentMessage",
			Field:     "in_reply_to",
			Predicate: "len(this) == 0 || matches(this, `^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$`)",
			Value:     message.InReplyTo,
		}
	}
	if message.Reference != nil {
		if err := ValidateAgentReference(message.Reference); err != nil {
			return err
		}
	}
	return nil
}
