load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "clock",
    srcs = [
        "clock.go",
        "manual.go",
    ],
    importpath = "github.com/candacelabs/csf/io/kernel/clock",
    visibility = ["//visibility:public"],
)

go_test(
    name = "clock_test",
    srcs = [
        "clock_suite_test.go",
        "clock_test.go",
    ],
    deps = [
        ":clock",
        "@com_github_onsi_ginkgo_v2//:ginkgo",
        "@com_github_onsi_gomega//:gomega",
    ],
)
