(* The seven executable EBNF grammars, generated from the kinds meta.csf
   declares (slices one_tree #520 and harness-bootstrap #529). grammar.ebnf's
   [source] lists the documentation kinds, architecture/language.ebnf's
   [declaration] lists the architecture kinds, and the slice planner's
   [decision_name] lists the planner kinds — all read from meta.csf in
   declaration order, so a kind added, renamed or dropped there regenerates
   here instead of drifting. The remaining productions are the languages'
   fixed syntax; this generator owns their bytes and the drift gate
   (tools/check-generated.sh) fails when a hand edit diverges from them.
   Every file opens with a "generated by csfc" header inside the first 300
   bytes, as a grammar-mode block comment. *)

exception Error of string

let kinds_source = "csf/compiler/language/meta.csf"
let generator_source = "csf/compiler/language/ebnf_codegen.ml"
let meta_grammar_path = "csf/compiler/language/meta.ebnf"

let header source =
  Printf.sprintf "(* Code generated by csfc from %s; DO NOT EDIT. *)\n" source

let decode root =
  match Meta.parse_files
    ~grammar_path:(Filename.concat root meta_grammar_path)
    ~source_path:(Filename.concat root kinds_source) with
  | Ok meta -> meta
  | Error diagnostics ->
      raise (Error (String.concat "; "
        (List.map (fun (diagnostic : Model.diagnostic) -> diagnostic.message) diagnostics)))

let names home meta =
  List.filter_map (fun (kind : Meta.kind) ->
    if kind.Meta.home = home then Some kind.Meta.name else None) meta.Meta.kinds

(* The kind lists are read from meta.csf; the productions below are the
   languages' fixed syntax, so a kind edit changes only these two lines. *)
let render_source kinds =
  Printf.sprintf "source = { %s } ;\n" (String.concat " | " kinds)

let render_declaration kinds =
  Printf.sprintf "declaration = %s ;\n" (String.concat " | " kinds)

(* Each planner kind is its own quoted terminal, so the decision set is a
   closed choice of words with no free text and no dangling production
   reference. *)
let render_choice kinds =
  Printf.sprintf "decision_name = %s ;\n"
    (String.concat " | " (List.map (Printf.sprintf "%S") kinds))

let decision_body = {|tree        = { question } ;
question    = "question", identifier, "{", text_clause, { option }, "}" ;
text_clause = "text", string, ";" ;
option      = "option", identifier, "leaf", string, ";"
            | "option", identifier, "refines", identifier, ";" ;
|}

let gate_body = {|gate        = "gate", identifier, string, string, edge_clause, side_clause,
              { relation }, { rule }, "{", { fact }, "}" ;
edge_clause = "edge", identifier, identifier ;
side_clause = "side", side ;
side        = "harness" | "harness_environment" | "environment" | "provider" | "model" ;
(* A declared relation or rule: its identifier and its one-line definition. *)
relation    = "relation", identifier, string ;
rule        = "rule", identifier, string ;
(* A fact names its relation, then its arguments, then ends a line. word W
   declares a gh noun; verb V declares a gh verb; replacement W V T maps the
   noun and verb to one CSF tool. *)
fact        = identifier, identifier, ";"
            | identifier, identifier, identifier, identifier, ";" ;
|}

let language_head = {|architecture = "architecture", identifier, "version", integer, "{", { declaration }, "}" ;
|}

let language_tail = {|process = "process", identifier, "kind", process_kind, [ "entrypoint", string ], ";" ;
process_kind = "go" | "external" ;
scope = "scope", identifier, "under", identifier, ";" ;
component = role, identifier, "in", identifier, "scope", identifier,
            [ "source", string ], "state", state, "lifecycle", lifecycle,
            "verification", verification, ";" ;
role = "service" | "manager" | "library" | "adapter" | "gateway" | "resource" ;
state = "existing" | "planned" ;
lifecycle = "scoped" | "lazy" | "borrowed" ;
verification = "pending" | "test", string ;
dependency = "requires", identifier, "->", identifier, ";" ;
connection = "connect", identifier, "->", identifier, "via", transport,
             [ "boundary", identifier ], "state", state, ";" ;
transport = "call" | "channel" | "subprocess" | "remote" | "device" ;
scan = "scan", string, ";" ;
generated = "generated", string, ";" ;
directory = "dir", string, "allowed", "[", [ string, { ",", string } ], "]", [ "tier", tier ], ";" ;
tier = "in_process" | "kernel" | "ipc" | "net" ;
|}

let shell_body = {|shell      = { block } ;
block      = identifier, name, "{", { item }, "}" ;
name       = identifier | string ;
item       = token, { token }, ";" ;
token      = identifier | integer | string | symbol ;
symbol     = "[" | "]" | "(" | ")" | "|" | ":" | "." | "," | "=" | "/" ;
|}

let meta_body = {|meta        = { declaration } ;
declaration = kind | relation ;
kind        = "kind", string, "in", home, ";" ;
home        = "documentation" | "architecture" | "meta" | "planner" ;
relation    = "relation", string, "->", string, ";" ;
|}

let slice_planner_head = {|slice_planner = "slice_planner", "dispatch_waiting", "{", { decision }, "}" ;
decision      = "decision", decision_name, ";" ;
|}

let grammar_static = {|(* identifier, name, definition, the edge's two term identifiers, the fault
   side that owns the repair, the MAST mode it refines (FM-1.1 ... FM-3.3)
   and the miner directory whose rule detects it *)
failure_code  = 'failure_code', identifier, string, string,
                  'edge', identifier, identifier, 'side', side,
                  [ 'mast', string ], [ 'miner', string ], ';' ;
side          = 'harness' | 'harness_environment' | 'environment'
              | 'provider' | 'model' ;
term          = 'term', identifier, string, string, [ forms ], [ kind ], [ home ], ';' ;
forms         = 'forms', string, { string } ;
kind          = 'kind', kind_value ;
kind_value    = 'concept' | 'component' ;
home          = 'home', ( string | planned ) ;
planned       = 'planned', number ;
(* name, meaning, how CSF uses it, citation, https:// link, optional next step
   and an inline relation: the entry stands to a target as same_as or
   specializes, or diverges from it with a stated reason. *)
literature    = 'literature', identifier, string, string, string, string,
                  string, [ forms ], [ next_step ], [ literature_relation ], ';' ;
next_step     = 'next', string ;
literature_relation = literature_verb, identifier, [ string ] ;
literature_verb = 'same_as' | 'specializes' | 'diverges' ;
(* subject term, verb, target term or literature entry, divergence reason *)
relation      = 'relation', identifier, identifier, identifier, [ string ],
                  ';' ;
retired       = 'retired', identifier, string, string, ';' ;
jargon        = 'jargon', string, ';' ;
(* title, plain-language summary, example, member terms *)
section       = 'section', identifier, string, string, string,
                  '{', { identifier, ';' }, '}' ;
linked        = 'linked', string, ';' ;
diagram       = 'diagram', identifier, direction, '{',
                  { node | group | edge }, '}' ;
direction     = 'LR' | 'TB' ;
node          = 'node', identifier, ':', identifier, state,
                  [ 'in', identifier ], ';' ;
group         = 'group', identifier, ':', identifier, ';' ;
edge          = 'edge', identifier, state, identifier,
                  [ 'label', string ], ';' ;
state         = 'existing' | 'planned' ;
(* The goal and its ordered milestones; a document renders it between
   <!-- csf:north_star NAME --> markers. *)
north_star    = 'north_star', identifier, '{', 'goal', string, ';',
                  milestone, { milestone }, '}' ;
(* identifier, status, statement, then what the milestone is made of *)
milestone     = 'milestone', identifier, status, string, '{',
                  { milestone_item }, '}' ;
status        = 'done' | 'in_progress' | 'planned' ;
milestone_item = 'uses', identifier, ';'
               | 'evidence', ( 'path', string | 'pr', number
                 | 'issue', number ), ';'
               | 'cites', identifier, ';' ;
number        = nonzero, { digit } ;
nonzero       = '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' ;
(* A document names diagrams, north stars and the components table; its markers
   say which. *)
document      = 'document', string, '{', { identifier, ';' }, '}' ;
(* Policy: named decision policy with optional class ordering and typed knees
   (parameters). Knees are measurements (numeric strings) or declared unmeasured
   when no sample exists. Class ordering is a priority list as a string. *)
policy        = 'policy', identifier, '{', [ class_order ], { knee }, '}' ;
class_order   = 'class', string, ';' ;
knee          = identifier, ( string | 'unmeasured' ), ';' ;
identifier    = lowercase, { lowercase | digit | '_' } ;
lowercase     = lowercase_low | lowercase_high ;
lowercase_low = 'a' | 'b' | 'c' | 'd' | 'e' | 'f' | 'g' | 'h'
              | 'i' | 'j' | 'k' | 'l' | 'm' | 'n' | 'o' | 'p' ;
lowercase_high = 'q' | 'r' | 's' | 't' | 'u' | 'v' | 'w' | 'x' | 'y' | 'z' ;
digit         = '0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' ;
string        = '"', { ordinary | escape }, '"' ;
escape        = '\', ( '"' | '\' | 'n' ) ;
ordinary      = ? UTF-8 character except quote, backslash, ASCII controls,
                  and DEL; UTF-8 is preserved without normalization ? ;
whitespace    = ' ' | ? tab ? | ? CR ? | ? LF ? ;
comment       = '#', { ? any character except LF ? }, [ ? LF ? ] ;

(* Semantic checks: at least one term, diagram, and document; every diagram
   has a node. Term names, definitions, and supplied edge labels are nonblank.
   Terms, diagrams, document paths, node/group identifiers within a diagram,
   ordered edge endpoint pairs, and each document's references are unique.
   Every reference resolves, including forward references. Document paths are
   relative .md or .markdown paths without empty, '.' or '..' components,
   backslashes, or control characters. The generated ontology path is reserved.
   File components must not be symlinks. Target documents already exist and
   contain each declared block's opening and closing marker once.
   Literature, retired, section and linked identifiers or paths are unique.
   Term names and forms, literature names and forms, retired words and jargon
   candidates are pairwise distinct. When sections exist, every term is in
   exactly one. Linked paths are Markdown and exclude the generated ontology
   and glossary paths; vocabulary matching rules are documented in compiler.ml.
   North stars: identifiers are unique and distinct from diagram identifiers;
   the goal and every statement are nonblank; milestone identifiers are unique
   within their north star; every milestone uses at least one term and every
   used term and cited literature entry resolves, without repeats; a done
   milestone has at least one path evidence and an in_progress one at least
   one evidence; evidence paths are repository-relative and name an existing
   file or directory, checked against ROOT before anything is written.
   Relations: the subject is a term or a literature entry; the target is a
   term or a literature entry; each subject, verb and target triple is unique.
   A relation whose target is a literature entry takes same_as, specializes,
   diverges or cites; a divergence carries a nonblank reason, and no other
   relation carries one. A literature entry's inline relations name it as the
   subject and take same_as, specializes or diverges.
   Policies: identifiers are unique; each policy has at most one class ordering
   (a space-separated priority list as a string); each knee name is unique
   within its policy; each knee value is a string (a numeric measurement) or the
   literal 'unmeasured' (no sample).
   Failure codes: identifiers and names are unique, names and definitions are
   nonblank, both edge endpoints are declared terms and differ, a mast value
   is spelled FM-<digits>.<digits>, and a miner is a repository-relative
   path. Each renders in the dictionary under #code-<identifier> and in
   services/ouroboros/codes/catalogue_cgen.go. *)
|}

(* The seven grammars in the brief's order. The three kind-list productions are
   read from meta.csf; the static bodies above own the rest of the bytes. *)
let render (meta : Meta.t) =
  let documentation = names Meta.Documentation meta in
  let architecture = names Meta.Architecture meta in
  let planner = names Meta.Planner meta in
  [ "csf/compiler/architecture/decision.ebnf", header generator_source ^ decision_body;
    "csf/compiler/architecture/gate.ebnf", header generator_source ^ gate_body;
    "csf/compiler/architecture/language.ebnf",
      header kinds_source ^ language_head ^ render_declaration architecture ^ language_tail;
    "csf/compiler/architecture/shell.ebnf", header generator_source ^ shell_body;
    "csf/compiler/architecture/slice_planner.ebnf",
      header kinds_source ^ slice_planner_head ^ render_choice planner;
    "csf/compiler/language/grammar.ebnf",
      header kinds_source ^ render_source documentation ^ grammar_static;
    "csf/compiler/language/meta.ebnf", header generator_source ^ meta_body ]

let outputs root = render (decode root)
