(* Acceptance for slices one_tree (#520) and harness-bootstrap (#529): the seven
   executable EBNF grammars are generated from the kinds meta.csf declares,
   each carrying a "generated by csfc" header inside its first 300 bytes so the
   drift gate and the grammar_generated_from_kinds invariant can both see it.
   The three kind-list productions — grammar.ebnf's [source], language.ebnf's
   [declaration] and slice_planner.ebnf's [decision_name] — are read from
   meta.csf in declaration order, so a kind added, renamed or dropped there
   regenerates here instead of drifting silently. The slice planner grammar is
   the one the brief hands to the planner first, so it names the planner kinds
   the dispatch pass checks and no free text at all. *)

let expect message condition = if not condition then failwith message

let describe diagnostics =
  List.map (fun (diagnostic : Model.diagnostic) ->
    Printf.sprintf "%s:%d:%d %s: %s" diagnostic.at.file diagnostic.at.line
      diagnostic.at.column diagnostic.code diagnostic.message) diagnostics
  |> String.concat "\n"

let meta_of grammar_path source_path =
  match Meta.parse_files ~grammar_path ~source_path with
  | Ok meta -> meta
  | Error diagnostics -> failwith (source_path ^ " did not parse:\n" ^ describe diagnostics)

let names kinds = List.map (fun (kind : Meta.kind) -> kind.Meta.name) kinds

let by_home home (meta : Meta.t) =
  List.filter (fun (kind : Meta.kind) -> kind.Meta.home = home) meta.Meta.kinds

let documentation_kinds =
  [ "term"; "literature"; "relation"; "retired"; "jargon"; "section";
    "linked"; "diagram"; "north_star"; "document"; "policy"; "failure_code" ]

let architecture_kinds =
  [ "process"; "scope"; "component"; "dependency"; "connection"; "scan"; "generated"; "directory" ]

let planner_kinds =
  [ "depends_on"; "held"; "contends"; "paused"; "rate"; "capacity"; "next_pass" ]

(* The seven grammars in the brief's order. *)
let expected_paths =
  [ "csf/compiler/architecture/decision.ebnf";
    "csf/compiler/architecture/gate.ebnf";
    "csf/compiler/architecture/language.ebnf";
    "csf/compiler/architecture/shell.ebnf";
    "csf/compiler/architecture/slice_planner.ebnf";
    "csf/compiler/language/grammar.ebnf";
    "csf/compiler/language/meta.ebnf" ]

let starts_with ~prefix text =
  String.length text >= String.length prefix &&
  String.sub text 0 (String.length prefix) = prefix

let first_300 text =
  if String.length text <= 300 then text else String.sub text 0 300

(* A substring check over a bounded prefix: whether [needle] occurs in [hay]. *)
let contains needle hay =
  let rec window i =
    if i + String.length needle > String.length hay then false
    else if String.sub hay i (String.length needle) = needle then true
    else window (i + 1) in
  window 0

let header source =
  Printf.sprintf "(* Code generated by csfc from %s; DO NOT EDIT. *)\n" source

(* The three generated kind-list productions, as this generator renders them. *)
let render_source kinds =
  Printf.sprintf "source = { %s } ;\n" (String.concat " | " kinds)

let render_declaration kinds =
  Printf.sprintf "declaration = %s ;\n" (String.concat " | " kinds)

let render_choice kinds =
  Printf.sprintf "decision_name = %s ;\n"
    (String.concat " | " (List.map (Printf.sprintf "%S") kinds))

let () =
  let argument index name =
    if Array.length Sys.argv <= index then failwith ("missing test argument: " ^ name);
    Sys.argv.(index) in
  let meta_grammar_path = argument 1 "meta.ebnf" in
  let meta_source_path = argument 2 "meta.csf" in
  let meta = meta_of meta_grammar_path meta_source_path in
  let rendered = Ebnf_codegen.render meta in
  expect "exactly seven grammars are rendered, in the brief's order"
    (List.map fst rendered = expected_paths);
  expect "the render is deterministic"
    (Ebnf_codegen.render meta = rendered);
  List.iter (fun (path, content) ->
    expect (path ^ " carries a generated-by-csfc header in its first 300 bytes")
      (contains "generated by csfc" (first_300 content))) rendered;
  (* The kind-list productions mirror meta.csf in declaration order. *)
  let content path = List.assoc path rendered in
  let grammar = content "csf/compiler/language/grammar.ebnf" in
  let language = content "csf/compiler/architecture/language.ebnf" in
  let generated_source = header "csf/compiler/language/meta.csf" ^
    render_source (names (by_home Meta.Documentation meta)) in
  let generated_declaration = header "csf/compiler/language/meta.csf" ^
    "architecture = \"architecture\", identifier, \"version\", integer, \"{\", { declaration }, \"}\" ;\n" ^
    render_declaration (names (by_home Meta.Architecture meta)) in
  expect "grammar.ebnf opens with the meta-driven source production"
    (starts_with ~prefix:generated_source grammar);
  expect "language.ebnf opens with the meta-driven declaration production"
    (starts_with ~prefix:generated_declaration language);
  expect "the documentation kinds are the twelve meta.csf declares in order"
    (names (by_home Meta.Documentation meta) = documentation_kinds);
  expect "the architecture kinds are the eight meta.csf declares in order"
    (names (by_home Meta.Architecture meta) = architecture_kinds);
  let planner = content "csf/compiler/architecture/slice_planner.ebnf" in
  let generated_choice =
    header "csf/compiler/language/meta.csf" ^
    "slice_planner = \"slice_planner\", \"dispatch_waiting\", \"{\", { decision }, \"}\" ;\n" ^
    "decision      = \"decision\", decision_name, \";\" ;\n" ^
    render_choice (names (by_home Meta.Planner meta)) in
  expect "the planner kinds are the seven meta.csf declares in order"
    (names (by_home Meta.Planner meta) = planner_kinds);
  expect "slice_planner.ebnf is the meta-driven decision_name production"
    (planner = generated_choice);
  print_endline "CSF ebnf codegen tests passed"
