(* Generator-owned Markdown blocks. A document holds each block between an
   opening <!-- csf:KIND NAME --> line and a closing <!-- /csf:KIND NAME -->
   line; the generator rewrites the interior and the generation metrics count
   it as generated.

   [kinds] is the only list of block kinds. The compiler matches on [kind], so
   a new constructor without a renderer does not compile; the OCaml metric
   reads [kinds]; and generation writes the Python oracle's copy to
   [python_path], which check mode keeps current. Adding a kind therefore
   changes no metric code. *)

type kind = Diagram | North_star | Components

let kinds = [Diagram; North_star; Components]

let name = function
  | Diagram -> "diagram" | North_star -> "north_star" | Components -> "components"

(* The Python compatibility oracle's generated copy of [kinds]. *)
let python_path = "csf/compiler/metric_compat/generated_blocks_cgen.py"

let render_python () =
  String.concat "\n" [
    "# Code generated by CandaceCodegen from csf/compiler/language/generated_block.ml; DO NOT EDIT.";
    "\"\"\"Generator-owned Markdown block kinds counted as generated by codegen.py.\"\"\"";
    "";
    (* A trailing comma keeps a one-kind tuple a tuple. *)
    "BLOCK_KINDS = (" ^ String.concat ", " (List.map (fun kind -> "\"" ^ name kind ^ "\"") kinds)
      ^ (if List.length kinds = 1 then ",)" else ")");
    "" ]
