load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "archive",
    srcs = ["archive.go"],
    importpath = "github.com/candacelabs/csf/csf/bootstrap/archive",
    visibility = ["//visibility:public"],
    deps = [
        "//io/ipc/proc",
        "//pkg/atomicfile",
        "//services/bootstrap",
    ],
)

go_test(
    name = "archive_test",
    srcs = [
        "archive_suite_test.go",
        "archive_test.go",
        "mock_generate_test.go",
        "mock_launcher_test.go",
    ],
    deps = [
        ":archive",
        "//io/ipc/proc",
        "//services/bootstrap",
        "@com_github_onsi_ginkgo_v2//:ginkgo",
        "@com_github_onsi_gomega//:gomega",
        "@org_uber_go_mock//gomock",
    ],
)
