load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "http",
    srcs = [
        "client.go",
        "listener.go",
    ],
    importpath = "github.com/candacelabs/csf/io/net/http",
    visibility = ["//visibility:public"],
    deps = [
        "//io/net",
        "//pkg/httpserver",
        "//runtime",
    ],
)

go_test(
    name = "http_test",
    srcs = [
        "client_test.go",
        "http_suite_test.go",
        "lifecycle_test.go",
        "listener_test.go",
        "mock_network_test.go",
    ],
    deps = [
        ":http",
        "//io/net",
        "//pkg/eventually",
        "//runtime",
        "@com_github_onsi_ginkgo_v2//:ginkgo",
        "@com_github_onsi_gomega//:gomega",
        "@org_uber_go_goleak//:goleak",
        "@org_uber_go_mock//gomock",
    ],
)
