// Code generated by MockGen. DO NOT EDIT.
// Source: ../network.go
//
// Generated by this command:
//
//	mockgen -source=../network.go -destination=mock_network_test.go -package=http_test
//

// Package http_test is a generated GoMock package.
package http_test

import (
	context "context"
	net "net"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIListener is a mock of IListener interface.
type MockIListener struct {
	ctrl     *gomock.Controller
	recorder *MockIListenerMockRecorder
	isgomock struct{}
}

// MockIListenerMockRecorder is the mock recorder for MockIListener.
type MockIListenerMockRecorder struct {
	mock *MockIListener
}

// NewMockIListener creates a new mock instance.
func NewMockIListener(ctrl *gomock.Controller) *MockIListener {
	mock := &MockIListener{ctrl: ctrl}
	mock.recorder = &MockIListenerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIListener) EXPECT() *MockIListenerMockRecorder {
	return m.recorder
}

// Listen mocks base method.
func (m *MockIListener) Listen(ctx context.Context, network, address string) (net.Listener, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Listen", ctx, network, address)
	ret0, _ := ret[0].(net.Listener)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Listen indicates an expected call of Listen.
func (mr *MockIListenerMockRecorder) Listen(ctx, network, address any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Listen", reflect.TypeOf((*MockIListener)(nil).Listen), ctx, network, address)
}

// MockIDialer is a mock of IDialer interface.
type MockIDialer struct {
	ctrl     *gomock.Controller
	recorder *MockIDialerMockRecorder
	isgomock struct{}
}

// MockIDialerMockRecorder is the mock recorder for MockIDialer.
type MockIDialerMockRecorder struct {
	mock *MockIDialer
}

// NewMockIDialer creates a new mock instance.
func NewMockIDialer(ctrl *gomock.Controller) *MockIDialer {
	mock := &MockIDialer{ctrl: ctrl}
	mock.recorder = &MockIDialerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDialer) EXPECT() *MockIDialerMockRecorder {
	return m.recorder
}

// DialContext mocks base method.
func (m *MockIDialer) DialContext(ctx context.Context, network, address string) (net.Conn, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DialContext", ctx, network, address)
	ret0, _ := ret[0].(net.Conn)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DialContext indicates an expected call of DialContext.
func (mr *MockIDialerMockRecorder) DialContext(ctx, network, address any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DialContext", reflect.TypeOf((*MockIDialer)(nil).DialContext), ctx, network, address)
}
