// Code generated by MockGen. DO NOT EDIT.
// Source: dispatch.go
//
// Generated by this command:
//
//	mockgen -source=dispatch.go -destination=mocks/mock_sessions.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	harnessv1 "github.com/candacelabs/csf/proto/candace/harness/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockISessionHost is a mock of ISessionHost interface.
type MockISessionHost struct {
	ctrl     *gomock.Controller
	recorder *MockISessionHostMockRecorder
	isgomock struct{}
}

// MockISessionHostMockRecorder is the mock recorder for MockISessionHost.
type MockISessionHostMockRecorder struct {
	mock *MockISessionHost
}

// NewMockISessionHost creates a new mock instance.
func NewMockISessionHost(ctrl *gomock.Controller) *MockISessionHost {
	mock := &MockISessionHost{ctrl: ctrl}
	mock.recorder = &MockISessionHostMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISessionHost) EXPECT() *MockISessionHostMockRecorder {
	return m.recorder
}

// Cancel mocks base method.
func (m *MockISessionHost) Cancel(ctx context.Context, request *harnessv1.CancelAgentSessionRequest) (*harnessv1.CancelAgentSessionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cancel", ctx, request)
	ret0, _ := ret[0].(*harnessv1.CancelAgentSessionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Cancel indicates an expected call of Cancel.
func (mr *MockISessionHostMockRecorder) Cancel(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cancel", reflect.TypeOf((*MockISessionHost)(nil).Cancel), ctx, request)
}

// Send mocks base method.
func (m *MockISessionHost) Send(ctx context.Context, request *harnessv1.SendAgentSessionMessageRequest) (*harnessv1.SendAgentSessionMessageResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, request)
	ret0, _ := ret[0].(*harnessv1.SendAgentSessionMessageResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Send indicates an expected call of Send.
func (mr *MockISessionHostMockRecorder) Send(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockISessionHost)(nil).Send), ctx, request)
}

// Submit mocks base method.
func (m *MockISessionHost) Submit(ctx context.Context, request *harnessv1.SubmitAgentSessionRequest) (*harnessv1.SubmitAgentSessionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Submit", ctx, request)
	ret0, _ := ret[0].(*harnessv1.SubmitAgentSessionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Submit indicates an expected call of Submit.
func (mr *MockISessionHostMockRecorder) Submit(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Submit", reflect.TypeOf((*MockISessionHost)(nil).Submit), ctx, request)
}
