load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "stub",
    srcs = ["stub.go"],
    importpath = "github.com/candacelabs/csf/io/net/model/stub",
    visibility = ["//visibility:public"],
    deps = ["//io/net/model"],
)

go_test(
    name = "stub_test",
    srcs = [
        "stub_suite_test.go",
        "stub_test.go",
    ],
    deps = [
        ":stub",
        "//io/net/model",
        "@com_github_onsi_ginkgo_v2//:ginkgo",
        "@com_github_onsi_gomega//:gomega",
    ],
)
