// Code generated by MockGen. DO NOT EDIT.
// Source: lazy.go
//
// Generated by this command:
//
//	mockgen -source=lazy.go -destination=mock_lazy_test.go -package=runtime_test
//

// Package runtime_test is a generated GoMock package.
package runtime_test

import (
	context "context"
	reflect "reflect"

	runtime "github.com/candacelabs/csf/runtime"
	gomock "go.uber.org/mock/gomock"
)

// MockIIdleReporter is a mock of IIdleReporter interface.
type MockIIdleReporter struct {
	ctrl     *gomock.Controller
	recorder *MockIIdleReporterMockRecorder
	isgomock struct{}
}

// MockIIdleReporterMockRecorder is the mock recorder for MockIIdleReporter.
type MockIIdleReporterMockRecorder struct {
	mock *MockIIdleReporter
}

// NewMockIIdleReporter creates a new mock instance.
func NewMockIIdleReporter(ctrl *gomock.Controller) *MockIIdleReporter {
	mock := &MockIIdleReporter{ctrl: ctrl}
	mock.recorder = &MockIIdleReporterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIIdleReporter) EXPECT() *MockIIdleReporterMockRecorder {
	return m.recorder
}

// Idle mocks base method.
func (m *MockIIdleReporter) Idle() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Idle")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Idle indicates an expected call of Idle.
func (mr *MockIIdleReporterMockRecorder) Idle() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Idle", reflect.TypeOf((*MockIIdleReporter)(nil).Idle))
}

// MockILazyService is a mock of ILazyService interface.
type MockILazyService[T runtime.IService] struct {
	ctrl     *gomock.Controller
	recorder *MockILazyServiceMockRecorder[T]
	isgomock struct{}
}

// MockILazyServiceMockRecorder is the mock recorder for MockILazyService.
type MockILazyServiceMockRecorder[T runtime.IService] struct {
	mock *MockILazyService[T]
}

// NewMockILazyService creates a new mock instance.
func NewMockILazyService[T runtime.IService](ctrl *gomock.Controller) *MockILazyService[T] {
	mock := &MockILazyService[T]{ctrl: ctrl}
	mock.recorder = &MockILazyServiceMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockILazyService[T]) EXPECT() *MockILazyServiceMockRecorder[T] {
	return m.recorder
}

// Start mocks base method.
func (m *MockILazyService[T]) Start(scope *runtime.Scope) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", scope)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockILazyServiceMockRecorder[T]) Start(scope any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockILazyService[T])(nil).Start), scope)
}

// Use mocks base method.
func (m *MockILazyService[T]) Use(ctx context.Context, call func(T) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Use", ctx, call)
	ret0, _ := ret[0].(error)
	return ret0
}

// Use indicates an expected call of Use.
func (mr *MockILazyServiceMockRecorder[T]) Use(ctx, call any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Use", reflect.TypeOf((*MockILazyService[T])(nil).Use), ctx, call)
}
