// Code generated by MockGen. DO NOT EDIT.
// Source: host.go
//
// Generated by this command:
//
//	mockgen -source=host.go -destination=mock_host_test.go -package=runtime_test
//

// Package runtime_test is a generated GoMock package.
package runtime_test

import (
	reflect "reflect"

	runtime "github.com/candacelabs/csf/runtime"
	gomock "go.uber.org/mock/gomock"
)

// MockIService is a mock of IService interface.
type MockIService struct {
	ctrl     *gomock.Controller
	recorder *MockIServiceMockRecorder
	isgomock struct{}
}

// MockIServiceMockRecorder is the mock recorder for MockIService.
type MockIServiceMockRecorder struct {
	mock *MockIService
}

// NewMockIService creates a new mock instance.
func NewMockIService(ctrl *gomock.Controller) *MockIService {
	mock := &MockIService{ctrl: ctrl}
	mock.recorder = &MockIServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIService) EXPECT() *MockIServiceMockRecorder {
	return m.recorder
}

// Start mocks base method.
func (m *MockIService) Start(scope *runtime.Scope) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", scope)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockIServiceMockRecorder) Start(scope any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockIService)(nil).Start), scope)
}
