// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/candacelabs/csf/services/harness/session (interfaces: ISessionContainers)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_session_containers.go -package=mocks github.com/candacelabs/csf/services/harness/session ISessionContainers
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	docker "github.com/candacelabs/csf/io/ipc/docker"
	sandbox "github.com/candacelabs/csf/io/kernel/sandbox"
	gomock "go.uber.org/mock/gomock"
)

// MockISessionContainers is a mock of ISessionContainers interface.
type MockISessionContainers struct {
	ctrl     *gomock.Controller
	recorder *MockISessionContainersMockRecorder
	isgomock struct{}
}

// MockISessionContainersMockRecorder is the mock recorder for MockISessionContainers.
type MockISessionContainersMockRecorder struct {
	mock *MockISessionContainers
}

// NewMockISessionContainers creates a new mock instance.
func NewMockISessionContainers(ctrl *gomock.Controller) *MockISessionContainers {
	mock := &MockISessionContainers{ctrl: ctrl}
	mock.recorder = &MockISessionContainersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISessionContainers) EXPECT() *MockISessionContainersMockRecorder {
	return m.recorder
}

// ContainerUsage mocks base method.
func (m *MockISessionContainers) ContainerUsage(started docker.StartedContainer) (sandbox.Usage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContainerUsage", started)
	ret0, _ := ret[0].(sandbox.Usage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContainerUsage indicates an expected call of ContainerUsage.
func (mr *MockISessionContainersMockRecorder) ContainerUsage(started any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContainerUsage", reflect.TypeOf((*MockISessionContainers)(nil).ContainerUsage), started)
}

// RemoveContainer mocks base method.
func (m *MockISessionContainers) RemoveContainer(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveContainer", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveContainer indicates an expected call of RemoveContainer.
func (mr *MockISessionContainersMockRecorder) RemoveContainer(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveContainer", reflect.TypeOf((*MockISessionContainers)(nil).RemoveContainer), ctx, id)
}

// StartDetached mocks base method.
func (m *MockISessionContainers) StartDetached(ctx context.Context, spec docker.SandboxSpec) (docker.StartedContainer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartDetached", ctx, spec)
	ret0, _ := ret[0].(docker.StartedContainer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartDetached indicates an expected call of StartDetached.
func (mr *MockISessionContainersMockRecorder) StartDetached(ctx, spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartDetached", reflect.TypeOf((*MockISessionContainers)(nil).StartDetached), ctx, spec)
}
