// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/candacelabs/csf/services/harness/session (interfaces: ITurnExecutor,IOpenTurnExecutor,IRouter)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_turn_executor.go -package=mocks github.com/candacelabs/csf/services/harness/session ITurnExecutor,IOpenTurnExecutor,IRouter
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/candacelabs/csf/ipc/model"
	claudecode "github.com/candacelabs/csf/ipc/model/claudecode"
	session "github.com/candacelabs/csf/services/harness/session"
	gomock "go.uber.org/mock/gomock"
)

// MockITurnExecutor is a mock of ITurnExecutor interface.
type MockITurnExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockITurnExecutorMockRecorder
	isgomock struct{}
}

// MockITurnExecutorMockRecorder is the mock recorder for MockITurnExecutor.
type MockITurnExecutorMockRecorder struct {
	mock *MockITurnExecutor
}

// NewMockITurnExecutor creates a new mock instance.
func NewMockITurnExecutor(ctrl *gomock.Controller) *MockITurnExecutor {
	mock := &MockITurnExecutor{ctrl: ctrl}
	mock.recorder = &MockITurnExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITurnExecutor) EXPECT() *MockITurnExecutorMockRecorder {
	return m.recorder
}

// Propose mocks base method.
func (m *MockITurnExecutor) Propose(ctx context.Context, turn *claudecode.Turn) (*model.Proposal[claudecode.Event], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Propose", ctx, turn)
	ret0, _ := ret[0].(*model.Proposal[claudecode.Event])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Propose indicates an expected call of Propose.
func (mr *MockITurnExecutorMockRecorder) Propose(ctx, turn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Propose", reflect.TypeOf((*MockITurnExecutor)(nil).Propose), ctx, turn)
}

// MockIOpenTurnExecutor is a mock of IOpenTurnExecutor interface.
type MockIOpenTurnExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockIOpenTurnExecutorMockRecorder
	isgomock struct{}
}

// MockIOpenTurnExecutorMockRecorder is the mock recorder for MockIOpenTurnExecutor.
type MockIOpenTurnExecutorMockRecorder struct {
	mock *MockIOpenTurnExecutor
}

// NewMockIOpenTurnExecutor creates a new mock instance.
func NewMockIOpenTurnExecutor(ctrl *gomock.Controller) *MockIOpenTurnExecutor {
	mock := &MockIOpenTurnExecutor{ctrl: ctrl}
	mock.recorder = &MockIOpenTurnExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIOpenTurnExecutor) EXPECT() *MockIOpenTurnExecutorMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockIOpenTurnExecutor) Close(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockIOpenTurnExecutorMockRecorder) Close(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockIOpenTurnExecutor)(nil).Close), ctx)
}

// Interrupt mocks base method.
func (m *MockIOpenTurnExecutor) Interrupt(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Interrupt", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Interrupt indicates an expected call of Interrupt.
func (mr *MockIOpenTurnExecutorMockRecorder) Interrupt(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Interrupt", reflect.TypeOf((*MockIOpenTurnExecutor)(nil).Interrupt), ctx)
}

// Propose mocks base method.
func (m *MockIOpenTurnExecutor) Propose(ctx context.Context, turn *claudecode.Turn) (*model.Proposal[claudecode.Event], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Propose", ctx, turn)
	ret0, _ := ret[0].(*model.Proposal[claudecode.Event])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Propose indicates an expected call of Propose.
func (mr *MockIOpenTurnExecutorMockRecorder) Propose(ctx, turn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Propose", reflect.TypeOf((*MockIOpenTurnExecutor)(nil).Propose), ctx, turn)
}

// MockIRouter is a mock of IRouter interface.
type MockIRouter struct {
	ctrl     *gomock.Controller
	recorder *MockIRouterMockRecorder
	isgomock struct{}
}

// MockIRouterMockRecorder is the mock recorder for MockIRouter.
type MockIRouterMockRecorder struct {
	mock *MockIRouter
}

// NewMockIRouter creates a new mock instance.
func NewMockIRouter(ctrl *gomock.Controller) *MockIRouter {
	mock := &MockIRouter{ctrl: ctrl}
	mock.recorder = &MockIRouterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRouter) EXPECT() *MockIRouterMockRecorder {
	return m.recorder
}

// Route mocks base method.
func (m *MockIRouter) Route(ctx context.Context, request session.RouteRequest) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Route", ctx, request)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Route indicates an expected call of Route.
func (mr *MockIRouterMockRecorder) Route(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Route", reflect.TypeOf((*MockIRouter)(nil).Route), ctx, request)
}
