// Code generated by csfc from csf/compiler/testdata/golden/service/blah/blah.csf; DO NOT EDIT.
//
// Package blah answers one request with one bounded response. A caller supplies
// a name and gets one rendered greeting or the empty_name outcome. The service
// starts no goroutines and keeps no state between calls.

package blah
