// Code generated by csfc from csf/compiler/testdata/golden/service/blah/blah.csf; DO NOT EDIT.
//
// One spec per declared operation outcome. blah is a fresh service, so the body
// and the classifier are generated from the declaration; the specs below assert
// the declared behaviour — the rendered greeting and the bounded outcome — for
// each `when` clause.

package blah

import (
	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

var _ = Describe("Blah greet", func() {
	It("renders one greeting and classifies ok for a non-empty name", func() {
		blah, err := NewBlah()
		Expect(err).NotTo(HaveOccurred())
		response := blah.Greet(&Name{Name: "world"})
		Expect(response.Text).To(Equal("Hello, world"))
		Expect(response.Outcome).To(Equal(outcomeOK))
	})

	It("classifies an empty name as empty_name", func() {
		blah, err := NewBlah()
		Expect(err).NotTo(HaveOccurred())
		response := blah.Greet(&Name{})
		Expect(response.Text).To(Equal("Hello, "))
		Expect(response.Outcome).To(Equal(outcomeEmptyName))
	})

	DescribeTable("declares one bounded label per outcome",
		func(outcome string) {
			Expect(outcome).To(BeElementOf([]string{outcomeEmptyName, outcomeOK}))
		},
		Entry("empty_name", outcomeEmptyName),
		Entry("ok", outcomeOK),
	)
})
