// Code generated by csfc from csf/compiler/testdata/golden/service/blah/blah.csf; DO NOT EDIT.
//
// The one declared operation, greet, with its input and output records, its
// declared logic, its generated classifier and its metrics. Greet times one
// attempt, renders the declared greeting, classifies the declared outcome and
// records both on the declared metrics. There is no seam: the body and the
// classifier are emitted from the declaration's logic and when/otherwise
// clauses.

package blah

import (
	"fmt"
	"time"

	"github.com/prometheus/client_golang/prometheus"

	"github.com/candacelabs/csf/pkg/telemetry"
)

// Name names the subject to greet.
type Name struct {
	Name string
}

// Greeting carries the rendered greeting and its outcome as typed data.
type Greeting struct {
	Text    string
	Outcome string
}

const (
	outcomeEmptyName = "empty_name"
	outcomeOK        = "ok"
)

// Greet renders one greeting for the named subject and returns the declared
// outcome. Greet is safe for concurrent use.
func (blah *Blah) Greet(request *Name) *Greeting {
	started := time.Now()
	response := &Greeting{
		Text:    fmt.Sprintf("Hello, %s", request.Name),
		Outcome: classifyGreet(request.Name),
	}
	blah.metrics.observe(response.Outcome, time.Since(started).Seconds())
	return response
}

// classifyGreet is the generated classifier for the declared outcomes: the
// first `when` clause that matches wins, and `otherwise` is the default.
func classifyGreet(name string) string {
	if name == "" {
		return outcomeEmptyName
	}
	return outcomeOK
}

// greetMetrics holds the two metric families of the greet operation.
type greetMetrics struct {
	greets   *prometheus.CounterVec
	duration *prometheus.HistogramVec
}

// newGreetMetrics registers the greet metrics. A nil registerer records
// nothing, so instrumentation is optional and off by default.
func newGreetMetrics(registerer prometheus.Registerer) (*greetMetrics, error) {
	if registerer == nil {
		return nil, nil
	}
	greets, err := telemetry.RegisterOnce(registerer, prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "csf_blah_greet_total",
		Help: "Total bounded blah greet outcomes; ok means one greeting rendered for a non-empty name.",
	}, []string{"outcome"}))
	if err != nil {
		return nil, err
	}
	duration, err := telemetry.RegisterOnce(registerer, prometheus.NewHistogramVec(prometheus.HistogramOpts{
		Name:    "csf_blah_greet_duration_seconds",
		Help:    "Duration of blah greet attempts by bounded outcome.",
		Buckets: prometheus.DefBuckets,
	}, []string{"outcome"}))
	if err != nil {
		return nil, err
	}
	return &greetMetrics{greets: greets, duration: duration}, nil
}

// observe records one attempt's bounded outcome and its duration.
func (metrics *greetMetrics) observe(outcome string, seconds float64) {
	if metrics == nil {
		return
	}
	metrics.greets.WithLabelValues(outcome).Inc()
	metrics.duration.WithLabelValues(outcome).Observe(seconds)
}
