// Code generated by tools/githubgen from ipc/github/api.github.com.json. DO NOT EDIT.

package githubtools

import (
	"context"
	"encoding/json"
	"net/http"

	"github.com/candacelabs/csf/csf"
	"github.com/candacelabs/csf/io/net/github"
)

// The generated GitHub tools' names.
const (
	ToolChecksListForRef             = "ChecksListForRef"
	ToolGitGetRef                    = "GitGetRef"
	ToolIssuesAddBlockedByDependency = "IssuesAddBlockedByDependency"
	ToolIssuesCreate                 = "IssuesCreate"
	ToolIssuesCreateComment          = "IssuesCreateComment"
	ToolIssuesGet                    = "IssuesGet"
	ToolIssuesListComments           = "IssuesListComments"
	ToolIssuesListForRepo            = "IssuesListForRepo"
	ToolIssuesUpdate                 = "IssuesUpdate"
	ToolPullsCreate                  = "PullsCreate"
	ToolPullsGet                     = "PullsGet"
	ToolPullsList                    = "PullsList"
	ToolPullsMerge                   = "PullsMerge"
	ToolPullsUpdate                  = "PullsUpdate"
	ToolReposGetCommit               = "ReposGetCommit"
	ToolReposListWebhookDeliveries   = "ReposListWebhookDeliveries"
	ToolReposListWebhooks            = "ReposListWebhooks"
)

// ChecksListForRefInput is the input of the ChecksListForRef tool.
type ChecksListForRefInput struct {
	Owner  string                         `json:"owner" jsonschema:"The account owner of the repository"`
	Repo   string                         `json:"repo" jsonschema:"The name of the repository without the '.git' extension"`
	Ref    string                         `json:"ref" jsonschema:"The commit reference"`
	Params *github.CheckslistForRefParams `json:"params,omitempty" jsonschema:"query parameters"`
}

func (tools *GitHubTools) handleChecksListForRef(ctx context.Context, input ChecksListForRefInput) (json.RawMessage, error) {
	call := toolCall{operation: ToolChecksListForRef, owner: input.Owner, repo: input.Repo}
	if err := tools.prepare(ctx, &call, &input); err != nil {
		return nil, err
	}
	response, err := tools.client.CheckslistForRefWithResponse(ctx, input.Owner, input.Repo, input.Ref, input.Params)
	if err != nil {
		return finish(ctx, tools, call, nil, nil, false, err)
	}
	return finish(ctx, tools, call, response.HTTPResponse, response.Body, response.JSON200 != nil, nil)
}

// GitGetRefInput is the input of the GitGetRef tool.
type GitGetRefInput struct {
	Owner string `json:"owner" jsonschema:"The account owner of the repository"`
	Repo  string `json:"repo" jsonschema:"The name of the repository without the '.git' extension"`
	Ref   string `json:"ref" jsonschema:"The Git reference"`
}

func (tools *GitHubTools) handleGitGetRef(ctx context.Context, input GitGetRefInput) (json.RawMessage, error) {
	call := toolCall{operation: ToolGitGetRef, owner: input.Owner, repo: input.Repo}
	if err := tools.prepare(ctx, &call, &input); err != nil {
		return nil, err
	}
	response, err := tools.client.GitgetRefWithResponse(ctx, input.Owner, input.Repo, input.Ref)
	if err != nil {
		return finish(ctx, tools, call, nil, nil, false, err)
	}
	return finish(ctx, tools, call, response.HTTPResponse, response.Body, response.JSON200 != nil, nil)
}

// IssuesAddBlockedByDependencyInput is the input of the IssuesAddBlockedByDependency tool.
type IssuesAddBlockedByDependencyInput struct {
	Owner       string                                             `json:"owner" jsonschema:"The account owner of the repository"`
	Repo        string                                             `json:"repo" jsonschema:"The name of the repository without the '.git' extension"`
	IssueNumber int                                                `json:"issue_number" jsonschema:"The number that identifies the issue"`
	Body        github.IssuesaddBlockedByDependencyJSONRequestBody `json:"body" jsonschema:"the request body"`
}

func (tools *GitHubTools) handleIssuesAddBlockedByDependency(ctx context.Context, input IssuesAddBlockedByDependencyInput) (json.RawMessage, error) {
	call := toolCall{operation: ToolIssuesAddBlockedByDependency, owner: input.Owner, repo: input.Repo, number: input.IssueNumber}
	if err := tools.prepare(ctx, &call, &input); err != nil {
		return nil, err
	}
	response, err := tools.client.IssuesaddBlockedByDependencyWithResponse(ctx, input.Owner, input.Repo, input.IssueNumber, input.Body)
	if err != nil {
		return finish(ctx, tools, call, nil, nil, false, err)
	}
	return finish(ctx, tools, call, response.HTTPResponse, response.Body, response.JSON201 != nil, nil)
}

// IssuesCreateInput is the input of the IssuesCreate tool.
type IssuesCreateInput struct {
	Owner string                             `json:"owner" jsonschema:"The account owner of the repository"`
	Repo  string                             `json:"repo" jsonschema:"The name of the repository without the '.git' extension"`
	Body  github.IssuescreateJSONRequestBody `json:"body" jsonschema:"the request body"`
}

func (tools *GitHubTools) handleIssuesCreate(ctx context.Context, input IssuesCreateInput) (json.RawMessage, error) {
	call := toolCall{operation: ToolIssuesCreate, owner: input.Owner, repo: input.Repo}
	if err := tools.prepare(ctx, &call, &input); err != nil {
		return nil, err
	}
	response, err := tools.client.IssuescreateWithResponse(ctx, input.Owner, input.Repo, input.Body)
	if err != nil {
		return finish(ctx, tools, call, nil, nil, false, err)
	}
	return finish(ctx, tools, call, response.HTTPResponse, response.Body, response.JSON201 != nil, nil)
}

// IssuesCreateCommentInput is the input of the IssuesCreateComment tool.
type IssuesCreateCommentInput struct {
	Owner       string                                    `json:"owner" jsonschema:"The account owner of the repository"`
	Repo        string                                    `json:"repo" jsonschema:"The name of the repository without the '.git' extension"`
	IssueNumber int                                       `json:"issue_number" jsonschema:"The number that identifies the issue"`
	Body        github.IssuescreateCommentJSONRequestBody `json:"body" jsonschema:"the request body"`
}

func (tools *GitHubTools) handleIssuesCreateComment(ctx context.Context, input IssuesCreateCommentInput) (json.RawMessage, error) {
	call := toolCall{operation: ToolIssuesCreateComment, owner: input.Owner, repo: input.Repo, number: input.IssueNumber}
	if err := tools.prepare(ctx, &call, &input); err != nil {
		return nil, err
	}
	response, err := tools.client.IssuescreateCommentWithResponse(ctx, input.Owner, input.Repo, input.IssueNumber, input.Body)
	if err != nil {
		return finish(ctx, tools, call, nil, nil, false, err)
	}
	return finish(ctx, tools, call, response.HTTPResponse, response.Body, response.JSON201 != nil, nil)
}

// IssuesGetInput is the input of the IssuesGet tool.
type IssuesGetInput struct {
	Owner       string `json:"owner" jsonschema:"The account owner of the repository"`
	Repo        string `json:"repo" jsonschema:"The name of the repository without the '.git' extension"`
	IssueNumber int    `json:"issue_number" jsonschema:"The number that identifies the issue"`
}

func (tools *GitHubTools) handleIssuesGet(ctx context.Context, input IssuesGetInput) (json.RawMessage, error) {
	call := toolCall{operation: ToolIssuesGet, owner: input.Owner, repo: input.Repo, number: input.IssueNumber}
	if err := tools.prepare(ctx, &call, &input); err != nil {
		return nil, err
	}
	response, err := tools.client.IssuesgetWithResponse(ctx, input.Owner, input.Repo, input.IssueNumber)
	if err != nil {
		return finish(ctx, tools, call, nil, nil, false, err)
	}
	return finish(ctx, tools, call, response.HTTPResponse, response.Body, response.JSON200 != nil, nil)
}

// IssuesListCommentsInput is the input of the IssuesListComments tool.
type IssuesListCommentsInput struct {
	Owner       string                           `json:"owner" jsonschema:"The account owner of the repository"`
	Repo        string                           `json:"repo" jsonschema:"The name of the repository without the '.git' extension"`
	IssueNumber int                              `json:"issue_number" jsonschema:"The number that identifies the issue"`
	Params      *github.IssueslistCommentsParams `json:"params,omitempty" jsonschema:"query parameters"`
}

func (tools *GitHubTools) handleIssuesListComments(ctx context.Context, input IssuesListCommentsInput) (ListOutput, error) {
	call := toolCall{operation: ToolIssuesListComments, owner: input.Owner, repo: input.Repo, number: input.IssueNumber}
	if err := tools.prepare(ctx, &call, &input); err != nil {
		return ListOutput{}, err
	}
	response, err := tools.client.IssueslistCommentsWithResponse(ctx, input.Owner, input.Repo, input.IssueNumber, input.Params)
	if err != nil {
		return listed(finish(ctx, tools, call, nil, nil, false, err))
	}
	return listed(finish(ctx, tools, call, response.HTTPResponse, response.Body, response.JSON200 != nil, nil))
}

// IssuesListForRepoInput is the input of the IssuesListForRepo tool.
type IssuesListForRepoInput struct {
	Owner  string                          `json:"owner" jsonschema:"The account owner of the repository"`
	Repo   string                          `json:"repo" jsonschema:"The name of the repository without the '.git' extension"`
	Params *github.IssueslistForRepoParams `json:"params,omitempty" jsonschema:"query parameters"`
}

func (tools *GitHubTools) handleIssuesListForRepo(ctx context.Context, input IssuesListForRepoInput) (ListOutput, error) {
	call := toolCall{operation: ToolIssuesListForRepo, owner: input.Owner, repo: input.Repo}
	if err := tools.prepare(ctx, &call, &input); err != nil {
		return ListOutput{}, err
	}
	response, err := tools.client.IssueslistForRepoWithResponse(ctx, input.Owner, input.Repo, input.Params)
	if err != nil {
		return listed(finish(ctx, tools, call, nil, nil, false, err))
	}
	return listed(finish(ctx, tools, call, response.HTTPResponse, response.Body, response.JSON200 != nil, nil))
}

// IssuesUpdateInput is the input of the IssuesUpdate tool.
type IssuesUpdateInput struct {
	Owner       string                             `json:"owner" jsonschema:"The account owner of the repository"`
	Repo        string                             `json:"repo" jsonschema:"The name of the repository without the '.git' extension"`
	IssueNumber int                                `json:"issue_number" jsonschema:"The number that identifies the issue"`
	Body        github.IssuesupdateJSONRequestBody `json:"body" jsonschema:"the request body"`
}

func (tools *GitHubTools) handleIssuesUpdate(ctx context.Context, input IssuesUpdateInput) (json.RawMessage, error) {
	call := toolCall{operation: ToolIssuesUpdate, owner: input.Owner, repo: input.Repo, number: input.IssueNumber}
	if err := tools.prepare(ctx, &call, &input); err != nil {
		return nil, err
	}
	response, err := tools.client.IssuesupdateWithResponse(ctx, input.Owner, input.Repo, input.IssueNumber, input.Body)
	if err != nil {
		return finish(ctx, tools, call, nil, nil, false, err)
	}
	return finish(ctx, tools, call, response.HTTPResponse, response.Body, response.JSON200 != nil, nil)
}

// PullsCreateInput is the input of the PullsCreate tool.
type PullsCreateInput struct {
	Owner string                            `json:"owner" jsonschema:"The account owner of the repository"`
	Repo  string                            `json:"repo" jsonschema:"The name of the repository without the '.git' extension"`
	Body  github.PullscreateJSONRequestBody `json:"body" jsonschema:"the request body"`
}

func (tools *GitHubTools) handlePullsCreate(ctx context.Context, input PullsCreateInput) (json.RawMessage, error) {
	call := toolCall{operation: ToolPullsCreate, owner: input.Owner, repo: input.Repo}
	if err := tools.prepare(ctx, &call, &input); err != nil {
		return nil, err
	}
	response, err := tools.client.PullscreateWithResponse(ctx, input.Owner, input.Repo, input.Body)
	if err != nil {
		return finish(ctx, tools, call, nil, nil, false, err)
	}
	return finish(ctx, tools, call, response.HTTPResponse, response.Body, response.JSON201 != nil, nil)
}

// PullsGetInput is the input of the PullsGet tool.
type PullsGetInput struct {
	Owner      string `json:"owner" jsonschema:"The account owner of the repository"`
	Repo       string `json:"repo" jsonschema:"The name of the repository without the '.git' extension"`
	PullNumber int    `json:"pull_number" jsonschema:"The number that identifies the pull request"`
}

func (tools *GitHubTools) handlePullsGet(ctx context.Context, input PullsGetInput) (json.RawMessage, error) {
	call := toolCall{operation: ToolPullsGet, owner: input.Owner, repo: input.Repo, number: input.PullNumber}
	if err := tools.prepare(ctx, &call, &input); err != nil {
		return nil, err
	}
	response, err := tools.client.PullsgetWithResponse(ctx, input.Owner, input.Repo, input.PullNumber)
	if err != nil {
		return finish(ctx, tools, call, nil, nil, false, err)
	}
	return finish(ctx, tools, call, response.HTTPResponse, response.Body, response.JSON200 != nil, nil)
}

// PullsListInput is the input of the PullsList tool.
type PullsListInput struct {
	Owner  string                  `json:"owner" jsonschema:"The account owner of the repository"`
	Repo   string                  `json:"repo" jsonschema:"The name of the repository without the '.git' extension"`
	Params *github.PullslistParams `json:"params,omitempty" jsonschema:"query parameters"`
}

func (tools *GitHubTools) handlePullsList(ctx context.Context, input PullsListInput) (ListOutput, error) {
	call := toolCall{operation: ToolPullsList, owner: input.Owner, repo: input.Repo}
	if err := tools.prepare(ctx, &call, &input); err != nil {
		return ListOutput{}, err
	}
	response, err := tools.client.PullslistWithResponse(ctx, input.Owner, input.Repo, input.Params)
	if err != nil {
		return listed(finish(ctx, tools, call, nil, nil, false, err))
	}
	return listed(finish(ctx, tools, call, response.HTTPResponse, response.Body, response.JSON200 != nil, nil))
}

// PullsMergeInput is the input of the PullsMerge tool.
type PullsMergeInput struct {
	Owner      string                           `json:"owner" jsonschema:"The account owner of the repository"`
	Repo       string                           `json:"repo" jsonschema:"The name of the repository without the '.git' extension"`
	PullNumber int                              `json:"pull_number" jsonschema:"The number that identifies the pull request"`
	Body       github.PullsmergeJSONRequestBody `json:"body" jsonschema:"the request body"`
}

func (tools *GitHubTools) handlePullsMerge(ctx context.Context, input PullsMergeInput) (json.RawMessage, error) {
	call := toolCall{operation: ToolPullsMerge, owner: input.Owner, repo: input.Repo, number: input.PullNumber}
	if err := tools.prepare(ctx, &call, &input); err != nil {
		return nil, err
	}
	response, err := tools.client.PullsmergeWithResponse(ctx, input.Owner, input.Repo, input.PullNumber, input.Body)
	if err != nil {
		return finish(ctx, tools, call, nil, nil, false, err)
	}
	return finish(ctx, tools, call, response.HTTPResponse, response.Body, response.JSON200 != nil, nil)
}

// PullsUpdateInput is the input of the PullsUpdate tool.
type PullsUpdateInput struct {
	Owner      string                            `json:"owner" jsonschema:"The account owner of the repository"`
	Repo       string                            `json:"repo" jsonschema:"The name of the repository without the '.git' extension"`
	PullNumber int                               `json:"pull_number" jsonschema:"The number that identifies the pull request"`
	Body       github.PullsupdateJSONRequestBody `json:"body" jsonschema:"the request body"`
}

func (tools *GitHubTools) handlePullsUpdate(ctx context.Context, input PullsUpdateInput) (json.RawMessage, error) {
	call := toolCall{operation: ToolPullsUpdate, owner: input.Owner, repo: input.Repo, number: input.PullNumber}
	if err := tools.prepare(ctx, &call, &input); err != nil {
		return nil, err
	}
	response, err := tools.client.PullsupdateWithResponse(ctx, input.Owner, input.Repo, input.PullNumber, input.Body)
	if err != nil {
		return finish(ctx, tools, call, nil, nil, false, err)
	}
	return finish(ctx, tools, call, response.HTTPResponse, response.Body, response.JSON200 != nil, nil)
}

// ReposGetCommitInput is the input of the ReposGetCommit tool.
type ReposGetCommitInput struct {
	Owner  string                       `json:"owner" jsonschema:"The account owner of the repository"`
	Repo   string                       `json:"repo" jsonschema:"The name of the repository without the '.git' extension"`
	Ref    string                       `json:"ref" jsonschema:"The commit reference"`
	Params *github.ReposgetCommitParams `json:"params,omitempty" jsonschema:"query parameters"`
}

func (tools *GitHubTools) handleReposGetCommit(ctx context.Context, input ReposGetCommitInput) (json.RawMessage, error) {
	call := toolCall{operation: ToolReposGetCommit, owner: input.Owner, repo: input.Repo}
	if err := tools.prepare(ctx, &call, &input); err != nil {
		return nil, err
	}
	response, err := tools.client.ReposgetCommitWithResponse(ctx, input.Owner, input.Repo, input.Ref, input.Params)
	if err != nil {
		return finish(ctx, tools, call, nil, nil, false, err)
	}
	return finish(ctx, tools, call, response.HTTPResponse, response.Body, response.JSON200 != nil, nil)
}

// ReposListWebhookDeliveriesInput is the input of the ReposListWebhookDeliveries tool.
type ReposListWebhookDeliveriesInput struct {
	Owner  string                                   `json:"owner" jsonschema:"The account owner of the repository"`
	Repo   string                                   `json:"repo" jsonschema:"The name of the repository without the '.git' extension"`
	HookId int                                      `json:"hook_id" jsonschema:"The unique identifier of the hook"`
	Params *github.ReposlistWebhookDeliveriesParams `json:"params,omitempty" jsonschema:"query parameters"`
}

func (tools *GitHubTools) handleReposListWebhookDeliveries(ctx context.Context, input ReposListWebhookDeliveriesInput) (ListOutput, error) {
	call := toolCall{operation: ToolReposListWebhookDeliveries, owner: input.Owner, repo: input.Repo}
	if err := tools.prepare(ctx, &call, &input); err != nil {
		return ListOutput{}, err
	}
	response, err := tools.client.ReposlistWebhookDeliveriesWithResponse(ctx, input.Owner, input.Repo, input.HookId, input.Params)
	if err != nil {
		return listed(finish(ctx, tools, call, nil, nil, false, err))
	}
	return listed(finish(ctx, tools, call, response.HTTPResponse, response.Body, response.JSON200 != nil, nil))
}

// ReposListWebhooksInput is the input of the ReposListWebhooks tool.
type ReposListWebhooksInput struct {
	Owner  string                          `json:"owner" jsonschema:"The account owner of the repository"`
	Repo   string                          `json:"repo" jsonschema:"The name of the repository without the '.git' extension"`
	Params *github.ReposlistWebhooksParams `json:"params,omitempty" jsonschema:"query parameters"`
}

func (tools *GitHubTools) handleReposListWebhooks(ctx context.Context, input ReposListWebhooksInput) (ListOutput, error) {
	call := toolCall{operation: ToolReposListWebhooks, owner: input.Owner, repo: input.Repo}
	if err := tools.prepare(ctx, &call, &input); err != nil {
		return ListOutput{}, err
	}
	response, err := tools.client.ReposlistWebhooksWithResponse(ctx, input.Owner, input.Repo, input.Params)
	if err != nil {
		return listed(finish(ctx, tools, call, nil, nil, false, err))
	}
	return listed(finish(ctx, tools, call, response.HTTPResponse, response.Body, response.JSON200 != nil, nil))
}

// generatedOperations are the operationIds the generated tools serve.
var generatedOperations = []string{
	"checks/list-for-ref",
	"git/get-ref",
	"issues/add-blocked-by-dependency",
	"issues/create",
	"issues/create-comment",
	"issues/get",
	"issues/list-comments",
	"issues/list-for-repo",
	"issues/update",
	"pulls/create",
	"pulls/get",
	"pulls/list",
	"pulls/merge",
	"pulls/update",
	"repos/get-commit",
	"repos/list-webhook-deliveries",
	"repos/list-webhooks",
}

// generated is every generated GitHub tool, each served at RoutePrefix plus
// its operationId.
func (tools *GitHubTools) generated() []csf.Operation {
	return []csf.Operation{
		csf.NewToolOperation(tools.tool(ToolChecksListForRef, "checks/list-for-ref", "List check runs for a Git reference. Lists check runs for a commit ref. The `ref` can be a SHA, branch name, or a tag name. GitHub REST operation checks/list-for-ref."), http.MethodPost, RoutePrefix+"checks/list-for-ref", tools.handleChecksListForRef),
		csf.NewToolOperation(tools.tool(ToolGitGetRef, "git/get-ref", "Get a reference. Returns a single reference from your Git database. The `:ref` in the URL must be formatted as `heads/<branch name>` for branches and `tags/<tag name>` for tags. If the `:ref` doesn't match an existing ref, a `404` is returned. GitHub REST operation git/get-ref."), http.MethodPost, RoutePrefix+"git/get-ref", tools.handleGitGetRef),
		csf.NewToolOperation(tools.tool(ToolIssuesAddBlockedByDependency, "issues/add-blocked-by-dependency", "Add a dependency an issue is blocked by. You can use the REST API to add a 'blocked by' relationship to an issue. GitHub REST operation issues/add-blocked-by-dependency."), http.MethodPost, RoutePrefix+"issues/add-blocked-by-dependency", tools.handleIssuesAddBlockedByDependency),
		csf.NewToolOperation(tools.tool(ToolIssuesCreate, "issues/create", "Create an issue. Any user with pull access to a repository can create an issue. If [issues are disabled in the repository](https://docs.github.com/articles/disabling-issues/), the API returns a `410 Gone` status. GitHub REST operation issues/create."), http.MethodPost, RoutePrefix+"issues/create", tools.handleIssuesCreate),
		csf.NewToolOperation(tools.tool(ToolIssuesCreateComment, "issues/create-comment", "Create an issue comment. You can use the REST API to create comments on issues and pull requests. Every pull request is an issue, but not every issue is a pull request. GitHub REST operation issues/create-comment."), http.MethodPost, RoutePrefix+"issues/create-comment", tools.handleIssuesCreateComment),
		csf.NewToolOperation(tools.tool(ToolIssuesGet, "issues/get", "Get an issue. The API returns a [`301 Moved Permanently` status](https://docs.github.com/rest/guides/best-practices-for-using-the-rest-api#follow-redirects) if the issue was [transferred](https://docs.github.com/articles/transferring-an-issue-to-another-repository/) to another repository. If the issue was transferred to or deleted from a repository where the authenticated user lacks read access, the API returns a `404 Not Found` status. If the issue was deleted from a repository where the authenticated user has read access, the API returns a `410 Gone` status. To receive webhook events for transferred and deleted issues, subscribe to the [`issues`](https://docs.github.com/webhooks/event-payloads/#issues) webhook. GitHub REST operation issues/get."), http.MethodPost, RoutePrefix+"issues/get", tools.handleIssuesGet),
		csf.NewToolOperation(tools.tool(ToolIssuesListComments, "issues/list-comments", "List issue comments. You can use the REST API to list comments on issues and pull requests. Every pull request is an issue, but not every issue is a pull request. GitHub REST operation issues/list-comments."), http.MethodPost, RoutePrefix+"issues/list-comments", tools.handleIssuesListComments),
		csf.NewToolOperation(tools.tool(ToolIssuesListForRepo, "issues/list-for-repo", "List repository issues. List issues in a repository. Only open issues will be listed. GitHub REST operation issues/list-for-repo."), http.MethodPost, RoutePrefix+"issues/list-for-repo", tools.handleIssuesListForRepo),
		csf.NewToolOperation(tools.tool(ToolIssuesUpdate, "issues/update", "Update an issue. Issue owners and users with push access or Triage role can edit an issue. GitHub REST operation issues/update."), http.MethodPost, RoutePrefix+"issues/update", tools.handleIssuesUpdate),
		csf.NewToolOperation(tools.tool(ToolPullsCreate, "pulls/create", "Create a pull request. Draft pull requests are available in public repositories with GitHub Free and GitHub Free for organizations, GitHub Pro, and legacy per-repository billing plans, and in public and private repositories with GitHub Team and GitHub Enterprise Cloud. For more information, see [GitHub's products](https://docs.github.com/github/getting-started-with-github/githubs-products) in the GitHub Help documentation. GitHub REST operation pulls/create."), http.MethodPost, RoutePrefix+"pulls/create", tools.handlePullsCreate),
		csf.NewToolOperation(tools.tool(ToolPullsGet, "pulls/get", "Get a pull request. Draft pull requests are available in public repositories with GitHub Free and GitHub Free for organizations, GitHub Pro, and legacy per-repository billing plans, and in public and private repositories with GitHub Team and GitHub Enterprise Cloud. For more information, see [GitHub's products](https://docs.github.com/github/getting-started-with-github/githubs-products) in the GitHub Help documentation. GitHub REST operation pulls/get."), http.MethodPost, RoutePrefix+"pulls/get", tools.handlePullsGet),
		csf.NewToolOperation(tools.tool(ToolPullsList, "pulls/list", "List pull requests. Lists pull requests in a specified repository. GitHub REST operation pulls/list."), http.MethodPost, RoutePrefix+"pulls/list", tools.handlePullsList),
		csf.NewToolOperation(tools.tool(ToolPullsMerge, "pulls/merge", "Merge a pull request. > [!NOTE] > We recommend using the [asynchronous merge API](https://docs.github.com/rest/pulls/pulls#merge-a-pull-request-asynchronously) instead. This endpoint does not support stacked pull requests or merging with a merge queue. GitHub REST operation pulls/merge."), http.MethodPost, RoutePrefix+"pulls/merge", tools.handlePullsMerge),
		csf.NewToolOperation(tools.tool(ToolPullsUpdate, "pulls/update", "Update a pull request. Draft pull requests are available in public repositories with GitHub Free and GitHub Free for organizations, GitHub Pro, and legacy per-repository billing plans, and in public and private repositories with GitHub Team and GitHub Enterprise Cloud. For more information, see [GitHub's products](https://docs.github.com/github/getting-started-with-github/githubs-products) in the GitHub Help documentation. GitHub REST operation pulls/update."), http.MethodPost, RoutePrefix+"pulls/update", tools.handlePullsUpdate),
		csf.NewToolOperation(tools.tool(ToolReposGetCommit, "repos/get-commit", "Get a commit. Returns the contents of a single commit reference. You must have `read` access for the repository to use this endpoint. GitHub REST operation repos/get-commit."), http.MethodPost, RoutePrefix+"repos/get-commit", tools.handleReposGetCommit),
		csf.NewToolOperation(tools.tool(ToolReposListWebhookDeliveries, "repos/list-webhook-deliveries", "List deliveries for a repository webhook. Returns a list of webhook deliveries for a webhook configured in a repository. GitHub REST operation repos/list-webhook-deliveries."), http.MethodPost, RoutePrefix+"repos/list-webhook-deliveries", tools.handleReposListWebhookDeliveries),
		csf.NewToolOperation(tools.tool(ToolReposListWebhooks, "repos/list-webhooks", "List repository webhooks. Lists webhooks for a repository. `last response` may return null if there have not been any deliveries within 30 days. GitHub REST operation repos/list-webhooks."), http.MethodPost, RoutePrefix+"repos/list-webhooks", tools.handleReposListWebhooks),
	}
}
