// Code generated by MockGen. DO NOT EDIT.
// Source: recovery.go
//
// Generated by this command:
//
//	mockgen -source=recovery.go -destination=mock_hook_deliveries_test.go -package=intake_test
//

// Package intake_test is a generated GoMock package.
package intake_test

import (
	context "context"
	reflect "reflect"

	intake "github.com/candacelabs/csf/services/intake"
	gomock "go.uber.org/mock/gomock"
)

// MockIHookDeliveries is a mock of IHookDeliveries interface.
type MockIHookDeliveries struct {
	ctrl     *gomock.Controller
	recorder *MockIHookDeliveriesMockRecorder
	isgomock struct{}
}

// MockIHookDeliveriesMockRecorder is the mock recorder for MockIHookDeliveries.
type MockIHookDeliveriesMockRecorder struct {
	mock *MockIHookDeliveries
}

// NewMockIHookDeliveries creates a new mock instance.
func NewMockIHookDeliveries(ctrl *gomock.Controller) *MockIHookDeliveries {
	mock := &MockIHookDeliveries{ctrl: ctrl}
	mock.recorder = &MockIHookDeliveriesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIHookDeliveries) EXPECT() *MockIHookDeliveriesMockRecorder {
	return m.recorder
}

// ListHookDeliveries mocks base method.
func (m *MockIHookDeliveries) ListHookDeliveries(ctx context.Context, repository string, hook int64, cursor string) ([]intake.HookDelivery, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListHookDeliveries", ctx, repository, hook, cursor)
	ret0, _ := ret[0].([]intake.HookDelivery)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListHookDeliveries indicates an expected call of ListHookDeliveries.
func (mr *MockIHookDeliveriesMockRecorder) ListHookDeliveries(ctx, repository, hook, cursor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListHookDeliveries", reflect.TypeOf((*MockIHookDeliveries)(nil).ListHookDeliveries), ctx, repository, hook, cursor)
}

// ListHooks mocks base method.
func (m *MockIHookDeliveries) ListHooks(ctx context.Context, repository string) ([]intake.Hook, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListHooks", ctx, repository)
	ret0, _ := ret[0].([]intake.Hook)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListHooks indicates an expected call of ListHooks.
func (mr *MockIHookDeliveriesMockRecorder) ListHooks(ctx, repository any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListHooks", reflect.TypeOf((*MockIHookDeliveries)(nil).ListHooks), ctx, repository)
}

// RedeliverHookDelivery mocks base method.
func (m *MockIHookDeliveries) RedeliverHookDelivery(ctx context.Context, repository string, hook, delivery int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RedeliverHookDelivery", ctx, repository, hook, delivery)
	ret0, _ := ret[0].(error)
	return ret0
}

// RedeliverHookDelivery indicates an expected call of RedeliverHookDelivery.
func (mr *MockIHookDeliveriesMockRecorder) RedeliverHookDelivery(ctx, repository, hook, delivery any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RedeliverHookDelivery", reflect.TypeOf((*MockIHookDeliveries)(nil).RedeliverHookDelivery), ctx, repository, hook, delivery)
}
