// Code generated by MockGen. DO NOT EDIT.
// Source: ../relay/messenger.go
//
// Generated by this command:
//
//	mockgen -source=../relay/messenger.go -destination=mock_messenger_test.go -package=intake_test
//

// Package intake_test is a generated GoMock package.
package intake_test

import (
	context "context"
	reflect "reflect"

	model "github.com/candacelabs/csf/io/net/model"
	relay "github.com/candacelabs/csf/services/relay"
	gomock "go.uber.org/mock/gomock"
)

// MockIMessenger is a mock of IMessenger interface.
type MockIMessenger[Body any] struct {
	ctrl     *gomock.Controller
	recorder *MockIMessengerMockRecorder[Body]
	isgomock struct{}
}

// MockIMessengerMockRecorder is the mock recorder for MockIMessenger.
type MockIMessengerMockRecorder[Body any] struct {
	mock *MockIMessenger[Body]
}

// NewMockIMessenger creates a new mock instance.
func NewMockIMessenger[Body any](ctrl *gomock.Controller) *MockIMessenger[Body] {
	mock := &MockIMessenger[Body]{ctrl: ctrl}
	mock.recorder = &MockIMessengerMockRecorder[Body]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIMessenger[Body]) EXPECT() *MockIMessengerMockRecorder[Body] {
	return m.recorder
}

// Receive mocks base method.
func (m *MockIMessenger[Body]) Receive(ctx context.Context, agent relay.AgentID) (relay.Envelope[Body], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Receive", ctx, agent)
	ret0, _ := ret[0].(relay.Envelope[Body])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Receive indicates an expected call of Receive.
func (mr *MockIMessengerMockRecorder[Body]) Receive(ctx, agent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Receive", reflect.TypeOf((*MockIMessenger[Body])(nil).Receive), ctx, agent)
}

// Send mocks base method.
func (m *MockIMessenger[Body]) Send(ctx context.Context, from, to model.IAgentAddress, body Body) (relay.Envelope[Body], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, from, to, body)
	ret0, _ := ret[0].(relay.Envelope[Body])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Send indicates an expected call of Send.
func (mr *MockIMessengerMockRecorder[Body]) Send(ctx, from, to, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockIMessenger[Body])(nil).Send), ctx, from, to, body)
}
