// Code generated by MockGen. DO NOT EDIT.
// Source: options.go
//
// Generated by this command:
//
//	mockgen -source=options.go -destination=mock_directory_test.go -package=intake_test
//

// Package intake_test is a generated GoMock package.
package intake_test

import (
	context "context"
	reflect "reflect"

	relay "github.com/candacelabs/csf/services/relay"
	gomock "go.uber.org/mock/gomock"
)

// MockIAgentDirectory is a mock of IAgentDirectory interface.
type MockIAgentDirectory struct {
	ctrl     *gomock.Controller
	recorder *MockIAgentDirectoryMockRecorder
	isgomock struct{}
}

// MockIAgentDirectoryMockRecorder is the mock recorder for MockIAgentDirectory.
type MockIAgentDirectoryMockRecorder struct {
	mock *MockIAgentDirectory
}

// NewMockIAgentDirectory creates a new mock instance.
func NewMockIAgentDirectory(ctrl *gomock.Controller) *MockIAgentDirectory {
	mock := &MockIAgentDirectory{ctrl: ctrl}
	mock.recorder = &MockIAgentDirectoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAgentDirectory) EXPECT() *MockIAgentDirectoryMockRecorder {
	return m.recorder
}

// Register mocks base method.
func (m *MockIAgentDirectory) Register(ctx context.Context, registration relay.Registration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, registration)
	ret0, _ := ret[0].(error)
	return ret0
}

// Register indicates an expected call of Register.
func (mr *MockIAgentDirectoryMockRecorder) Register(ctx, registration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockIAgentDirectory)(nil).Register), ctx, registration)
}

// Resolve mocks base method.
func (m *MockIAgentDirectory) Resolve(ctx context.Context, agent relay.AgentID) (relay.Registration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", ctx, agent)
	ret0, _ := ret[0].(relay.Registration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resolve indicates an expected call of Resolve.
func (mr *MockIAgentDirectoryMockRecorder) Resolve(ctx, agent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockIAgentDirectory)(nil).Resolve), ctx, agent)
}
