(* pkg/collections' exported primitives are generated, not copied.

   The operator's taste correction on 2cbcea2 (PR #460) named the shape: a set
   toggle or a keyed lookup reimplemented at each site belongs to one exported
   primitive instead. This generator owns that primitive's Go, so the committed
   file has one author and a site calls the export rather than growing its own
   copy.

   golden_first step 4: the emitted bytes are pinned byte for byte by
   collections_codegen_test against pkg/collections/testdata/golden/collections.go,
   which step 2 handwrote first. *)

let banner = "// Code generated by csfc. DO NOT EDIT."

(* The exports the ask names: Set[T comparable] (Toggle removes when present and
   adds when absent; Remove removes when present and is otherwise unchanged) and
   KeyedList[K comparable, V any].Get (the value whose key matches, else the zero
   value and false). There is no instance data to vary them. Toggle and Get are
   the ask's two; Remove is the third shape a rewritten site needed, a remove
   that reports whether the value was there. *)
let body =
  [ "// Copyright 2026 Candace Labs";
    "";
    "// Package collections provides small generic collection primitives shared across";
    "// the handwritten Go, so a site carries a typed value instead of reimplementing";
    "// a set operation or a keyed lookup locally.";
    "package collections";
    "";
    "import \"slices\"";
    "";
    "// Set is a set of comparable values, kept as a slice without duplicates.";
    "type Set[T comparable] []T";
    "";
    "// Toggle returns the set with value removed when it is present and added when";
    "// it is absent.";
    "func (set Set[T]) Toggle(value T) Set[T] {";
    "\tif index := slices.Index(set, value); index >= 0 {";
    "\t\treturn slices.Delete(slices.Clone(set), index, index+1)";
    "\t}";
    "\treturn append(slices.Clip(set), value)";
    "}";
    "";
    "// Remove returns the set with value removed, and whether value was present.";
    "func (set Set[T]) Remove(value T) (Set[T], bool) {";
    "\tif index := slices.Index(set, value); index >= 0 {";
    "\t\treturn slices.Delete(slices.Clone(set), index, index+1), true";
    "\t}";
    "\treturn set, false";
    "}";
    "";
    "// KeyedList is a list of values each carrying a key of type K.";
    "type KeyedList[K comparable, V any] struct {";
    "\tvalues []V";
    "\tkey    func(V) K";
    "}";
    "";
    "// NewKeyedList returns a keyed list looked up by the key each value carries.";
    "func NewKeyedList[K comparable, V any](key func(V) K, values []V) KeyedList[K, V] {";
    "\treturn KeyedList[K, V]{values: values, key: key}";
    "}";
    "";
    "// Get returns the value whose key is key, or the zero value and false when no";
    "// value carries that key.";
    "func (list KeyedList[K, V]) Get(key K) (V, bool) {";
    "\tindex := slices.IndexFunc(list.values, func(each V) bool { return list.key(each) == key })";
    "\tif index < 0 {";
    "\t\tvar zero V";
    "\t\treturn zero, false";
    "\t}";
    "\treturn list.values[index], true";
    "}" ]

(* The bytes the generator emits: the banner line, then the package, each line
   newline-terminated so the output ends in exactly one newline. *)
let render () =
  let output = Buffer.create 2048 in
  List.iter (fun line ->
    Buffer.add_string output line;
    Buffer.add_char output '\n') (banner :: body);
  Buffer.contents output
