// Code generated by MockGen. DO NOT EDIT.
// Source: control.go
//
// Generated by this command:
//
//	mockgen -source=control.go -destination=mock_operations_test.go -package=opsview_test
//

// Package opsview_test is a generated GoMock package.
package opsview_test

import (
	context "context"
	reflect "reflect"

	brainspinev1 "github.com/candacelabs/csf/proto/candace/brainspine/v1"
	harnessv1 "github.com/candacelabs/csf/proto/candace/harness/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockIWorkbenchOperations is a mock of IWorkbenchOperations interface.
type MockIWorkbenchOperations struct {
	ctrl     *gomock.Controller
	recorder *MockIWorkbenchOperationsMockRecorder
	isgomock struct{}
}

// MockIWorkbenchOperationsMockRecorder is the mock recorder for MockIWorkbenchOperations.
type MockIWorkbenchOperationsMockRecorder struct {
	mock *MockIWorkbenchOperations
}

// NewMockIWorkbenchOperations creates a new mock instance.
func NewMockIWorkbenchOperations(ctrl *gomock.Controller) *MockIWorkbenchOperations {
	mock := &MockIWorkbenchOperations{ctrl: ctrl}
	mock.recorder = &MockIWorkbenchOperationsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIWorkbenchOperations) EXPECT() *MockIWorkbenchOperationsMockRecorder {
	return m.recorder
}

// CancelAgentSession mocks base method.
func (m *MockIWorkbenchOperations) CancelAgentSession(ctx context.Context, request *harnessv1.CancelAgentSessionRequest) (*harnessv1.CancelAgentSessionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelAgentSession", ctx, request)
	ret0, _ := ret[0].(*harnessv1.CancelAgentSessionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelAgentSession indicates an expected call of CancelAgentSession.
func (mr *MockIWorkbenchOperationsMockRecorder) CancelAgentSession(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelAgentSession", reflect.TypeOf((*MockIWorkbenchOperations)(nil).CancelAgentSession), ctx, request)
}

// CheckAgentSessionAdmission mocks base method.
func (m *MockIWorkbenchOperations) CheckAgentSessionAdmission(ctx context.Context, request *harnessv1.CheckAgentSessionAdmissionRequest) (*harnessv1.CheckAgentSessionAdmissionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckAgentSessionAdmission", ctx, request)
	ret0, _ := ret[0].(*harnessv1.CheckAgentSessionAdmissionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckAgentSessionAdmission indicates an expected call of CheckAgentSessionAdmission.
func (mr *MockIWorkbenchOperationsMockRecorder) CheckAgentSessionAdmission(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAgentSessionAdmission", reflect.TypeOf((*MockIWorkbenchOperations)(nil).CheckAgentSessionAdmission), ctx, request)
}

// GetWorkbenchTheme mocks base method.
func (m *MockIWorkbenchOperations) GetWorkbenchTheme(ctx context.Context, request *brainspinev1.GetWorkbenchThemeRequest) (*brainspinev1.GetWorkbenchThemeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkbenchTheme", ctx, request)
	ret0, _ := ret[0].(*brainspinev1.GetWorkbenchThemeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkbenchTheme indicates an expected call of GetWorkbenchTheme.
func (mr *MockIWorkbenchOperationsMockRecorder) GetWorkbenchTheme(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkbenchTheme", reflect.TypeOf((*MockIWorkbenchOperations)(nil).GetWorkbenchTheme), ctx, request)
}

// ListAgentSessions mocks base method.
func (m *MockIWorkbenchOperations) ListAgentSessions(ctx context.Context, request *harnessv1.ListAgentSessionsRequest) (*harnessv1.ListAgentSessionsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAgentSessions", ctx, request)
	ret0, _ := ret[0].(*harnessv1.ListAgentSessionsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAgentSessions indicates an expected call of ListAgentSessions.
func (mr *MockIWorkbenchOperationsMockRecorder) ListAgentSessions(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAgentSessions", reflect.TypeOf((*MockIWorkbenchOperations)(nil).ListAgentSessions), ctx, request)
}

// MergeAgentSessionPullRequest mocks base method.
func (m *MockIWorkbenchOperations) MergeAgentSessionPullRequest(ctx context.Context, request *harnessv1.MergeAgentSessionPullRequestRequest) (*harnessv1.MergeAgentSessionPullRequestResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MergeAgentSessionPullRequest", ctx, request)
	ret0, _ := ret[0].(*harnessv1.MergeAgentSessionPullRequestResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MergeAgentSessionPullRequest indicates an expected call of MergeAgentSessionPullRequest.
func (mr *MockIWorkbenchOperationsMockRecorder) MergeAgentSessionPullRequest(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MergeAgentSessionPullRequest", reflect.TypeOf((*MockIWorkbenchOperations)(nil).MergeAgentSessionPullRequest), ctx, request)
}

// ReadyAgentSessionPullRequest mocks base method.
func (m *MockIWorkbenchOperations) ReadyAgentSessionPullRequest(ctx context.Context, request *harnessv1.ReadyAgentSessionPullRequestRequest) (*harnessv1.ReadyAgentSessionPullRequestResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadyAgentSessionPullRequest", ctx, request)
	ret0, _ := ret[0].(*harnessv1.ReadyAgentSessionPullRequestResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadyAgentSessionPullRequest indicates an expected call of ReadyAgentSessionPullRequest.
func (mr *MockIWorkbenchOperationsMockRecorder) ReadyAgentSessionPullRequest(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadyAgentSessionPullRequest", reflect.TypeOf((*MockIWorkbenchOperations)(nil).ReadyAgentSessionPullRequest), ctx, request)
}

// SendAgentSessionMessage mocks base method.
func (m *MockIWorkbenchOperations) SendAgentSessionMessage(ctx context.Context, request *harnessv1.SendAgentSessionMessageRequest) (*harnessv1.SendAgentSessionMessageResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendAgentSessionMessage", ctx, request)
	ret0, _ := ret[0].(*harnessv1.SendAgentSessionMessageResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendAgentSessionMessage indicates an expected call of SendAgentSessionMessage.
func (mr *MockIWorkbenchOperationsMockRecorder) SendAgentSessionMessage(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendAgentSessionMessage", reflect.TypeOf((*MockIWorkbenchOperations)(nil).SendAgentSessionMessage), ctx, request)
}

// SetAgentExecutorDefault mocks base method.
func (m *MockIWorkbenchOperations) SetAgentExecutorDefault(ctx context.Context, request *harnessv1.SetAgentExecutorDefaultRequest) (*harnessv1.SetAgentExecutorDefaultResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetAgentExecutorDefault", ctx, request)
	ret0, _ := ret[0].(*harnessv1.SetAgentExecutorDefaultResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetAgentExecutorDefault indicates an expected call of SetAgentExecutorDefault.
func (mr *MockIWorkbenchOperationsMockRecorder) SetAgentExecutorDefault(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAgentExecutorDefault", reflect.TypeOf((*MockIWorkbenchOperations)(nil).SetAgentExecutorDefault), ctx, request)
}

// SubmitAgentSession mocks base method.
func (m *MockIWorkbenchOperations) SubmitAgentSession(ctx context.Context, request *harnessv1.SubmitAgentSessionRequest) (*harnessv1.SubmitAgentSessionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitAgentSession", ctx, request)
	ret0, _ := ret[0].(*harnessv1.SubmitAgentSessionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubmitAgentSession indicates an expected call of SubmitAgentSession.
func (mr *MockIWorkbenchOperationsMockRecorder) SubmitAgentSession(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitAgentSession", reflect.TypeOf((*MockIWorkbenchOperations)(nil).SubmitAgentSession), ctx, request)
}
