// Code generated by csfc from csf/compiler/testdata/golden/view/observe_sessions.csf; DO NOT EDIT.
//
// observe_sessions: one projection of every harness session, read by two
// verbs. csf status renders one session_progress row per session as a table;
// csf tail renders the lines the session's event log folds to, readably and
// labelled by agent. Both read this one projection, and neither reads the log
// a second way.

package progress

import (
	"fmt"
	"slices"
	"strconv"
	"strings"
	"time"

	"github.com/candacelabs/csf/pkg/textbound"
	"github.com/candacelabs/csf/services/harness/session"
)

// Kind is the kind of one tail line, as declared by the view's kind facts.
type Kind string

// The kinds, in declaration order. A kind fact added to the block adds a case
// to kindOf below.
const (
	// KindTurn is a turn starting, ending, or a message sent to the session.
	KindTurn Kind = "turn"
	// KindTool is one tool call the session made.
	KindTool Kind = "tool"
	// KindGate is a session gate's decision.
	KindGate Kind = "gate"
	// KindMerge is a pull request moving.
	KindMerge Kind = "merge"
	// KindError is a failure a record reported.
	KindError Kind = "error"
)

// Kinds is every line kind, in declaration order.
func Kinds() []Kind { return []Kind{KindTurn, KindTool, KindGate, KindMerge, KindError} }

// kindOf decodes a literal token to the line kind it names.
func kindOf(token string) (Kind, bool) {
	switch Kind(token) {
	case KindTurn:
		return KindTurn, true
	case KindTool:
		return KindTool, true
	case KindGate:
		return KindGate, true
	case KindMerge:
		return KindMerge, true
	case KindError:
		return KindError, true
	default:
		return "", false
	}
}

// ParseKind reads one kind by its spelling.
func ParseKind(name string) (Kind, error) {
	if kind, ok := kindOf(name); ok {
		return kind, nil
	}
	names := make([]string, 0, len(Kinds()))
	for _, kind := range Kinds() {
		names = append(names, string(kind))
	}
	return "", fmt.Errorf("progress: unknown kind %q; want one of %s", name, strings.Join(names, ", "))
}

// ParseKinds reads a comma-separated kind list into the set of kinds to show.
// An empty list means every kind.
func ParseKinds(names string) (map[Kind]bool, error) {
	keep := map[Kind]bool{}
	for _, name := range strings.Split(names, ",") {
		name = strings.TrimSpace(name)
		if name == "" {
			continue
		}
		kind, err := ParseKind(name)
		if err != nil {
			return nil, err
		}
		keep[kind] = true
	}
	if len(keep) == 0 {
		for _, kind := range Kinds() {
			keep[kind] = true
		}
	}
	return keep, nil
}

// Phase is a session's phase, as the view declares it.
type Phase string

const (
	PhaseRunning  Phase = "running"
	PhaseOpen     Phase = "open"
	PhaseClosed   Phase = "closed"
	PhaseCanceled Phase = "canceled"
	PhaseFailed   Phase = "failed"
)

// Progress is one row of the session_progress relation: one typed field per
// declared field, in declaration order.
type Progress struct {
	Assignment   string
	Agent        string
	Phase        Phase
	Turn         int
	Queued       int
	ToolCalls    int
	CommitsAhead int
	ChangedFiles int
	Model        string
	LastActivity time.Time
	LastNote     string
}

// Line is one folded tail line: when it happened, the agent that wrote it,
// which kind it is and what it says.
type Line struct {
	Time  time.Time
	Agent string
	Kind  Kind
	Text  string
}

// lineRender is the render the view declares: render line
// "{time} {agent} {kind} {text}". lineTimeFormat is how {time} spells.
const (
	lineRender     = "{time} {agent} {kind} {text}"
	lineTimeFormat = "15:04:05"
)

// String renders the line for the terminal: readable, labelled by agent, and
// never JSON.
func (line Line) String() string {
	return fmt.Sprintf("%s %s %s %s", line.Time.Format(lineTimeFormat), line.Agent, line.Kind, line.Text)
}

// Fold applies one event log record to a row and returns the row with the
// lines the record adds. It is the projection the relation names: a record
// folds to the same row and the same lines every time.
func Fold(row Progress, record *session.Record) (Progress, []Line) {
	if record.Time.After(row.LastActivity) {
		row.LastActivity = record.Time
	}
	if record.Turn > row.Turn {
		row.Turn = record.Turn
	}
	lines := []Line{}
	add := func(kind Kind, text string) {
		text = strings.Join(strings.Fields(text), " ")
		if text == "" {
			return
		}
		lines = append(lines, Line{Time: record.Time, Agent: row.Agent, Kind: kind, Text: textbound.Prefix(text, lineLimit)})
	}
	switch record.EventType {
	case session.EventTypeRunStarted:
		row.Phase = PhaseOpen
		add(KindTurn, "session started")
	case session.EventTypeTurnRequested:
		row.Phase = PhaseRunning
		add(KindTurn, "turn "+strconv.Itoa(record.Turn))
	case session.EventTypeRunFinished:
		row.Phase = PhaseOpen
		if record.Error == "" {
			add(KindTurn, "turn "+strconv.Itoa(record.Turn)+" done")
		}
	case session.EventTypeSessionClosed:
		row.Phase = PhaseClosed
		add(KindTurn, "session closed")
	case session.EventTypeGateDecision:
		add(KindGate, record.Gate+" "+record.Decision)
	case session.EventTypeControlAction:
		kind, text := actionLine(record.Action)
		add(kind, text)
	case session.EventTypeAssistant:
		row, lines = foldAssistant(row, record, lines)
	}
	if record.Error != "" {
		add(KindError, record.Error)
	}
	return row, lines
}

// actionLine is the kind and text one control action folds to.
func actionLine(action string) (Kind, string) {
	switch action {
	case session.ActionSubmit:
		return KindTurn, "launched"
	case session.ActionSend:
		return KindTurn, "message sent"
	case session.ActionCancel:
		return KindTurn, "cancel requested"
	case session.ActionReady:
		return KindMerge, "pull request marked ready"
	case session.ActionMergeStarted:
		return KindMerge, "merge started"
	case session.ActionMerge:
		return KindMerge, "pull request merged"
	}
	return KindTurn, "control action: " + action
}

// foldAssistant counts one assistant message's tool calls, keeps the last thing
// the session said as the row's note, and adds the turn's line on the message
// that ends a turn.
func foldAssistant(row Progress, record *session.Record, lines []Line) (Progress, []Line) {
	add := func(kind Kind, text string) {
		text = strings.Join(strings.Fields(text), " ")
		if text == "" {
			return
		}
		lines = append(lines, Line{Time: record.Time, Agent: row.Agent, Kind: kind, Text: textbound.Prefix(text, lineLimit)})
	}
	text, tools := record.Assistant()
	for _, tool := range tools {
		row.ToolCalls++
		add(KindTool, tool.Name+" "+toolGist(tool.Input))
	}
	if len(text) == 0 {
		return row, lines
	}
	said := firstLine(text[len(text)-1])
	if said == "" {
		return row, lines
	}
	row.LastNote = textbound.Prefix(said, noteLimit)
	if message, ok := record.Stream(); ok && message.Message.StopReason == session.StopReasonEndTurn {
		add(KindTurn, said)
	}
	return row, lines
}

// Status renders every session's row, in assignment order, as a table. It is
// the generated csf status verb, as a function value so the command registers
// it in data.
func Status(rows []Progress) string {
	table := &strings.Builder{}
	fmt.Fprintln(table, "AGENT\tASSIGNMENT\tPHASE\tTURN\tQUEUED\tTOOLS\tAHEAD\tCHANGED\tLAST\tNOTE")
	for _, row := range rows {
		fmt.Fprintf(table, "%s\t%s\t%s\t%d\t%d\t%d\t%d\t%d\t%s\t%s\n",
			row.Agent, row.Assignment, row.Phase, row.Turn, row.Queued, row.ToolCalls,
			row.CommitsAhead, row.ChangedFiles, activity(row.LastActivity), row.LastNote)
	}
	return table.String()
}

// Tail keeps the folded lines to the kinds and agents asked for, takes the
// last n, and renders each one line. It is the generated csf tail verb.
func Tail(lines []Line, keepKind map[Kind]bool, keepAgent func(string) bool, n int) []string {
	shown := slices.DeleteFunc(slices.Clone(lines), func(line Line) bool {
		return !keepKind[line.Kind] || !keepAgent(line.Agent)
	})
	if len(shown) > n {
		shown = shown[len(shown)-n:]
	}
	rendered := make([]string, 0, len(shown))
	for _, line := range shown {
		rendered = append(rendered, line.String())
	}
	return rendered
}

const (
	lineLimit      = 200
	noteLimit      = 100
	activityFormat = "01-02 15:04:05"
)

func activity(at time.Time) string {
	if at.IsZero() {
		return "-"
	}
	return at.Format(activityFormat)
}

// ---------------------------------------------------------------------------
// The seam. This section is the hand-written half the generated projection
// plugs into; it is shown here so one file carries the whole shape, and it is
// NOT part of what the generator emits (it lives in the package's read.go and
// work.go). The projection above is pure over a session.Record; reading the
// state directory into records, and filling the two git fields through a
// proc.ILauncher, is the seam's job and is deliberately not generated.
// ---------------------------------------------------------------------------

// toolGist and firstLine bound a tool call's input and a note's text. They are
// helpers the fold shares with the seam, listed here only so the whole fold is
// readable in one file.
func toolGist(input []byte) string { return firstLine(string(input)) }

func firstLine(text string) string {
	for _, line := range strings.Split(text, "\n") {
		if trimmed := strings.TrimSpace(line); trimmed != "" {
			return trimmed
		}
	}
	return ""
}
