// Code generated by csfc from csf/compiler/testdata/golden/service/email/email.csf; DO NOT EDIT.
//
// The email service: the Mailer the host builds from its options, and the
// config the constructor validates once. NewMailer fails on a missing boundary
// or an invalid address, never later at Send. The config validation is declared
// by the constructor's boundary checks and by WithAddresses; there is no seam.

package email

import (
	"errors"
	"fmt"
	"net/mail"
	"strings"
	"time"

	"github.com/prometheus/client_golang/prometheus"
)

var (
	// ErrNoSender means the host did not configure one valid sender.
	ErrNoSender = errors.New("email: sender is required")
	// ErrNoRecipients means the host did not configure any valid recipients.
	ErrNoRecipients = errors.New("email: at least one recipient is required")
	// ErrHeaderInjection means an address contains a line break.
	ErrHeaderInjection = errors.New("email: address contains a CR or LF")
)

const (
	maxRecipients    = 64
	maxAddressHeader = 512
)

// addressEnvelope holds one send's parsed sender and recipients, validated
// together so neither can outlive the other.
type addressEnvelope struct {
	sender     *mail.Address
	recipients []*mail.Address
}

// mailerConfig holds the host-configured boundaries before the service is
// built. It is not exported; every field is set through one option.
type mailerConfig struct {
	transport  ITransport
	provenance IProvenanceSource
	receipts   IReceiptSink
	from       *mail.Address
	to         []*mail.Address
	now        func() time.Time
	registerer prometheus.Registerer
}

// Option configures the service before construction.
type Option func(config *mailerConfig) error

// WithAddresses configures the host-owned envelope and visible address headers.
func WithAddresses(from string, to []string) Option {
	return func(config *mailerConfig) error {
		envelope, err := parseAddresses(from, to)
		if err != nil {
			return err
		}
		config.from = envelope.sender
		config.to = envelope.recipients
		return nil
	}
}

// WithClock replaces the real clock, primarily for deterministic verification.
func WithClock(now func() time.Time) Option {
	return func(config *mailerConfig) error {
		if now == nil {
			return errors.New("email: clock is nil")
		}
		config.now = now
		return nil
	}
}

// WithMetrics registers bounded send metrics with registerer.
func WithMetrics(registerer prometheus.Registerer) Option {
	return func(config *mailerConfig) error {
		if registerer == nil {
			return errors.New("email: metrics registerer is nil")
		}
		config.registerer = registerer
		return nil
	}
}

func parseAddresses(from string, to []string) (addressEnvelope, error) {
	if strings.TrimSpace(from) == "" {
		return addressEnvelope{}, ErrNoSender
	}
	if strings.ContainsAny(from, "\r\n") {
		return addressEnvelope{}, ErrHeaderInjection
	}
	sender, err := mail.ParseAddress(from)
	if err != nil || !strings.Contains(sender.Address, "@") {
		return addressEnvelope{}, fmt.Errorf("%w: invalid From address", ErrNoSender)
	}
	if len(sender.String()) > maxAddressHeader {
		return addressEnvelope{}, fmt.Errorf("%w: From address is too long", ErrNoSender)
	}
	if len(to) == 0 || len(to) > maxRecipients {
		return addressEnvelope{}, ErrNoRecipients
	}
	recipients := make([]*mail.Address, 0, len(to))
	for _, raw := range to {
		if strings.TrimSpace(raw) == "" {
			return addressEnvelope{}, ErrNoRecipients
		}
		if strings.ContainsAny(raw, "\r\n") {
			return addressEnvelope{}, ErrHeaderInjection
		}
		recipient, parseErr := mail.ParseAddress(raw)
		if parseErr != nil || !strings.Contains(recipient.Address, "@") {
			return addressEnvelope{}, fmt.Errorf("%w: invalid To address", ErrNoRecipients)
		}
		if len(recipient.String()) > maxAddressHeader {
			return addressEnvelope{}, fmt.Errorf("%w: To address is too long", ErrNoRecipients)
		}
		recipients = append(recipients, recipient)
	}
	return addressEnvelope{sender: sender, recipients: recipients}, nil
}

// Mailer delivers one bounded message and retains receipt evidence. It owns no
// goroutine and holds no connection between calls; every boundary is the host's.
type Mailer struct {
	transport  ITransport
	provenance IProvenanceSource
	receipts   IReceiptSink
	from       string
	to         []string
	now        func() time.Time
	metrics    *mailerMetrics
}

// NewMailer builds a Mailer from the host-configured options. It fails when a
// required boundary is absent or an address is invalid, never later at Send.
func NewMailer(options ...Option) (*Mailer, error) {
	config := &mailerConfig{now: time.Now}
	for _, option := range options {
		if err := option(config); err != nil {
			return nil, err
		}
	}
	if config.transport == nil {
		return nil, ErrNoTransport
	}
	if config.provenance == nil {
		return nil, ErrNoProvenance
	}
	if config.receipts == nil {
		return nil, ErrNoReceiptSink
	}
	if config.from == nil {
		return nil, ErrNoSender
	}
	if len(config.to) == 0 {
		return nil, ErrNoRecipients
	}
	metrics, err := newMailerMetrics(config.registerer)
	if err != nil {
		return nil, err
	}
	recipients := make([]string, 0, len(config.to))
	for _, address := range config.to {
		recipients = append(recipients, address.String())
	}
	return &Mailer{
		transport:  config.transport,
		provenance: config.provenance,
		receipts:   config.receipts,
		from:       config.from.String(),
		to:         recipients,
		now:        config.now,
		metrics:    metrics,
	}, nil
}
