// Code generated by csfc from csf/compiler/testdata/golden/service/email/email.csf; DO NOT EDIT.
//
// The provenance capability: the interface the host binds, the option that sets
// it, and the error a missing boundary returns.

package email

import (
	"context"
	"errors"

	provenancev1 "github.com/candacelabs/csf/proto/candace/provenance/v1"
)

// ErrNoProvenance means no runtime provenance source was configured.
var ErrNoProvenance = errors.New("email: provenance source is required")

// IProvenanceSource observes the runtime facts attached to one send attempt.
// The service clones the returned message before assigning receipt-owned
// fields.
type IProvenanceSource interface {
	Snapshot(ctx context.Context) (*provenancev1.ReceiptMetadata, error)
}

// WithProvenance configures the trusted runtime observation boundary.
func WithProvenance(source IProvenanceSource) Option {
	return func(config *mailerConfig) error {
		if source == nil {
			return ErrNoProvenance
		}
		config.provenance = source
		return nil
	}
}
