// Code generated by csfc from csf/compiler/testdata/golden/service/email/email.csf; DO NOT EDIT.
//
// The receipts capability's test file: its gomock double, so a spec can hold
// the receipts boundary without a live receipt sink, and the misuse spec that
// protects the constructor's refusal of a missing boundary.

package email

import (
	"context"
	"reflect"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
	"go.uber.org/mock/gomock"

	emailv1 "github.com/candacelabs/csf/proto/candace/email/v1"
)

// MockIReceiptSink is a mock of IReceiptSink.
type MockIReceiptSink struct {
	ctrl     *gomock.Controller
	recorder *MockIReceiptSinkMockRecorder
}

// MockIReceiptSinkMockRecorder records calls to MockIReceiptSink.
type MockIReceiptSinkMockRecorder struct {
	mock *MockIReceiptSink
}

// NewMockIReceiptSink returns a new mock of IReceiptSink.
func NewMockIReceiptSink(ctrl *gomock.Controller) *MockIReceiptSink {
	mock := &MockIReceiptSink{ctrl: ctrl}
	mock.recorder = &MockIReceiptSinkMockRecorder{mock}
	return mock
}

// EXPECT returns the recorder for setting expectations.
func (mock *MockIReceiptSink) EXPECT() *MockIReceiptSinkMockRecorder {
	return mock.recorder
}

// Record mocks IReceiptSink.Record.
func (mock *MockIReceiptSink) Record(ctx context.Context, receipt *emailv1.EmailReceipt) error {
	mock.ctrl.T.Helper()
	ret := mock.ctrl.Call(mock, "Record", ctx, receipt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Record indicates an expected call of Record.
func (mr *MockIReceiptSinkMockRecorder) Record(ctx, receipt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Record", reflect.TypeOf((*MockIReceiptSink)(nil).Record), ctx, receipt)
}

var _ = Describe("Mailer receipts boundary", func() {
	It("refuses to build without a receipt sink", func() {
		_, err := NewMailer(
			WithTransport(NewMockITransport(gomock.NewController(GinkgoT()))),
			WithProvenance(NewMockIProvenanceSource(gomock.NewController(GinkgoT()))),
		)
		Expect(err).To(MatchError(ErrNoReceiptSink))
	})
})
