// Code generated by csfc from csf/compiler/testdata/golden/service/email/email.csf; DO NOT EDIT.
//
// One spec per declared operation outcome, plus the address-envelope misuse the
// service constructor rejects. These protect the emitted shape — the
// constructor validates every boundary, Send records the bounded outcome, and
// the generated body never invents evidence; the transport stays a host-bound
// capability.

package email

import (
	"context"
	"errors"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
	"go.uber.org/mock/gomock"

	emailv1 "github.com/candacelabs/csf/proto/candace/email/v1"
	provenancev1 "github.com/candacelabs/csf/proto/candace/provenance/v1"
)

var _ = Describe("Mailer send", func() {
	var (
		controller *gomock.Controller
		transport  *MockITransport
		provenance *MockIProvenanceSource
		sink       *MockIReceiptSink
	)

	BeforeEach(func() {
		controller = gomock.NewController(GinkgoT())
		transport = NewMockITransport(controller)
		provenance = NewMockIProvenanceSource(controller)
		sink = NewMockIReceiptSink(controller)
	})

	configured := func() *Mailer {
		GinkgoHelper()
		mailer, err := NewMailer(
			WithTransport(transport),
			WithProvenance(provenance),
			WithReceiptSink(sink),
			WithAddresses("spine@example.invalid", []string{"operator@example.invalid"}),
		)
		Expect(err).NotTo(HaveOccurred())
		return mailer
	}

	It("records UNKNOWN before network and replaces it with the final outcome", func() {
		provenance.EXPECT().Snapshot(gomock.Any()).Return(&provenancev1.ReceiptMetadata{}, nil)
		gomock.InOrder(
			sink.EXPECT().Record(gomock.Any(), gomock.Any()).DoAndReturn(func(_ context.Context, receipt *emailv1.EmailReceipt) error {
				Expect(receipt.GetOutcome()).To(Equal(emailv1.DeliveryOutcome_DELIVERY_OUTCOME_UNKNOWN))
				Expect(receipt.GetErrorCode()).To(Equal(errorCodeAttempt))
				return nil
			}),
			transport.EXPECT().Send(gomock.Any(), gomock.Any()).Return(emailv1.DeliveryOutcome_DELIVERY_OUTCOME_ACCEPTED, nil),
			sink.EXPECT().Record(gomock.Any(), gomock.Any()).DoAndReturn(func(_ context.Context, receipt *emailv1.EmailReceipt) error {
				Expect(receipt.GetOutcome()).To(Equal(emailv1.DeliveryOutcome_DELIVERY_OUTCOME_ACCEPTED))
				Expect(receipt.GetCompletedAt()).NotTo(BeNil())
				return nil
			}),
		)
		receipt, err := configured().Send(context.Background(), &emailv1.EmailMessage{Subject: "Status", Text: "body"})
		Expect(err).NotTo(HaveOccurred())
		Expect(receipt.GetOutcome()).To(Equal(emailv1.DeliveryOutcome_DELIVERY_OUTCOME_ACCEPTED))
		Expect(receipt.GetMessageSha256()).To(MatchRegexp("^[0-9a-f]{64}$"))
	})

	DescribeTable("returns the receipt and its sentinel for a non-accepted outcome",
		func(outcome emailv1.DeliveryOutcome, wantCode string, wantErr error) {
			provenance.EXPECT().Snapshot(gomock.Any()).Return(&provenancev1.ReceiptMetadata{}, nil)
			sink.EXPECT().Record(gomock.Any(), gomock.Any()).Return(nil).Times(2)
			transport.EXPECT().Send(gomock.Any(), gomock.Any()).Return(outcome, nil)
			receipt, err := configured().Send(context.Background(), &emailv1.EmailMessage{Subject: "Status", Text: "body"})
			Expect(err).To(MatchError(wantErr))
			Expect(receipt.GetOutcome()).To(Equal(outcome))
			Expect(receipt.GetErrorCode()).To(Equal(wantCode))
		},
		Entry("failed", emailv1.DeliveryOutcome_DELIVERY_OUTCOME_FAILED, errorCodeFailed, ErrDeliveryFailed),
		Entry("unknown", emailv1.DeliveryOutcome_DELIVERY_OUTCOME_UNKNOWN, errorCodeUnknown, ErrDeliveryUnknown),
	)

	It("treats an invalid transport outcome as unknown rather than accepted", func() {
		provenance.EXPECT().Snapshot(gomock.Any()).Return(&provenancev1.ReceiptMetadata{}, nil)
		sink.EXPECT().Record(gomock.Any(), gomock.Any()).Return(nil).Times(2)
		transport.EXPECT().Send(gomock.Any(), gomock.Any()).Return(emailv1.DeliveryOutcome_DELIVERY_OUTCOME_UNSPECIFIED, nil)
		receipt, err := configured().Send(context.Background(), &emailv1.EmailMessage{Subject: "Status", Text: "body"})
		Expect(err).To(MatchError(ErrInvalidTransportOutcome))
		Expect(receipt.GetOutcome()).To(Equal(emailv1.DeliveryOutcome_DELIVERY_OUTCOME_UNKNOWN))
		Expect(receipt.GetErrorCode()).To(Equal(errorCodeInvalid))
	})

	It("does not call the transport when the pre-send receipt cannot be recorded", func() {
		provenance.EXPECT().Snapshot(gomock.Any()).Return(&provenancev1.ReceiptMetadata{}, nil)
		sink.EXPECT().Record(gomock.Any(), gomock.Any()).Return(errors.New("disk unavailable"))
		receipt, err := configured().Send(context.Background(), &emailv1.EmailMessage{Subject: "Status", Text: "body"})
		Expect(err).To(HaveOccurred())
		Expect(receipt.GetOutcome()).To(Equal(emailv1.DeliveryOutcome_DELIVERY_OUTCOME_FAILED))
		Expect(receipt.GetErrorCode()).To(Equal(errorCodeSink))
	})

	It("collects an unavailable provenance source without inventing facts", func() {
		provenance.EXPECT().Snapshot(gomock.Any()).Return(nil, errors.New("observer down"))
		sink.EXPECT().Record(gomock.Any(), gomock.Any()).Return(nil).Times(2)
		transport.EXPECT().Send(gomock.Any(), gomock.Any()).Return(emailv1.DeliveryOutcome_DELIVERY_OUTCOME_ACCEPTED, nil)
		receipt, err := configured().Send(context.Background(), &emailv1.EmailMessage{Subject: "Status", Text: "body"})
		Expect(err).NotTo(HaveOccurred())
		Expect(receipt.GetProvenance().GetUnavailable()).To(ContainElement(provenanceUnavailable))
	})

	DescribeTable("classifies every outcome as one bounded label",
		func(outcome emailv1.DeliveryOutcome, want string) {
			label, classifyErr := classifyOutcome(outcome)
			Expect(classifyErr).NotTo(HaveOccurred())
			Expect(label).To(Equal(want))
		},
		Entry("accepted", emailv1.DeliveryOutcome_DELIVERY_OUTCOME_ACCEPTED, metricOutcomeAccepted),
		Entry("failed", emailv1.DeliveryOutcome_DELIVERY_OUTCOME_FAILED, metricOutcomeFailed),
		Entry("unknown", emailv1.DeliveryOutcome_DELIVERY_OUTCOME_UNKNOWN, metricOutcomeUnknown),
		Entry("unspecified", emailv1.DeliveryOutcome_DELIVERY_OUTCOME_UNSPECIFIED, metricOutcomeUnknown),
	)
})

var _ = Describe("Mailer addresses", func() {
	It("refuses a recipient address that carries a line break", func() {
		_, err := NewMailer(
			WithTransport(NewMockITransport(gomock.NewController(GinkgoT()))),
			WithProvenance(NewMockIProvenanceSource(gomock.NewController(GinkgoT()))),
			WithReceiptSink(NewMockIReceiptSink(gomock.NewController(GinkgoT()))),
			WithAddresses("spine@example.invalid", []string{"operator@example.invalid\r\nBcc: bad@example.invalid"}),
		)
		Expect(err).To(MatchError(ErrHeaderInjection))
	})
})
