// Code generated by csfc from csf/compiler/testdata/golden/service/email/email.csf; DO NOT EDIT.
//
// The one declared operation, send, with its delivery sentinels, its receipt
// evidence sequence, its outcome classifier and its metrics. Send times one
// attempt, records pre-send evidence, renders and delivers the message, records
// the final evidence, then classifies the bounded outcome and records both on
// the declared metrics. There is no seam: the body and the classifier are
// emitted from the declaration's logic and when/otherwise clauses, and the
// retained reverse-ported evidence sequence is asked in email.csf as typed
// questions rather than left in an unmarked file.

package email

import (
	"context"
	"crypto/sha256"
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/prometheus/client_golang/prometheus"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/known/timestamppb"

	"github.com/candacelabs/csf/pkg/telemetry"
	emailv1 "github.com/candacelabs/csf/proto/candace/email/v1"
	provenancev1 "github.com/candacelabs/csf/proto/candace/provenance/v1"
)

var (
	// ErrDeliveryFailed means the transport reported a definite failure.
	ErrDeliveryFailed = errors.New("email: delivery failed")
	// ErrDeliveryUnknown means the outcome could not be determined; the message
	// may or may not have been delivered.
	ErrDeliveryUnknown = errors.New("email: delivery outcome unknown")
	// ErrInvalidTransportOutcome means a transport returned an unusable outcome.
	ErrInvalidTransportOutcome = errors.New("email: transport returned an invalid outcome")
)

const (
	metricOutcomeAccepted = "accepted"
	metricOutcomeFailed   = "failed"
	metricOutcomeUnknown  = "unknown"
)

const (
	receiptSchemaVersion  = 1
	errorCodeAttempt      = "attempt_pending"
	errorCodeSink         = "receipt_sink_failed"
	errorCodeFailed       = "transport_failed"
	errorCodeUnknown      = "transport_unknown"
	errorCodeInvalid      = "transport_invalid_outcome"
	provenanceUnavailable = "provenance source unavailable"
)

// Send delivers one message and returns the final bounded receipt. It hands the
// one operation body to sendBody, then records the bounded outcome and the
// attempt duration on the declared metrics. Send is safe for concurrent use.
func (mailer *Mailer) Send(ctx context.Context, message *emailv1.EmailMessage) (*emailv1.EmailReceipt, error) {
	started := mailer.now()
	receipt, err := sendBody(ctx, mailer, message)
	if receipt == nil {
		receipt = &emailv1.EmailReceipt{Outcome: emailv1.DeliveryOutcome_DELIVERY_OUTCOME_UNKNOWN}
	}
	label, classifyErr := classifyOutcome(receipt.GetOutcome())
	if classifyErr != nil {
		label = metricOutcomeUnknown
	}
	mailer.metrics.observe(label, mailer.now().Sub(started).Seconds())
	return receipt, err
}

// sendBody is the generated operation body: it records pre-send evidence,
// renders and delivers the message, and records the final evidence.
func sendBody(ctx context.Context, mailer *Mailer, message *emailv1.EmailMessage) (*emailv1.EmailReceipt, error) {
	started := mailer.now()
	receipt := newAttemptReceipt(mailer, ctx, started)
	if err := mailer.record(ctx, receipt); err != nil {
		// The sink just refused this receipt; a second write to it would only repeat the failure.
		receipt.Outcome = emailv1.DeliveryOutcome_DELIVERY_OUTCOME_FAILED
		receipt.ErrorCode = errorCodeSink
		receipt.CompletedAt = timestamppb.New(mailer.now())
		return receipt, fmt.Errorf("recording pre-send receipt: %w", err)
	}
	if err := ctx.Err(); err != nil {
		return mailer.finishWithoutTransport(ctx, receipt, errorCodeAttempt, err)
	}
	raw, renderErr := renderMessage(mailer, message)
	if renderErr != nil {
		return mailer.finishWithoutTransport(ctx, receipt, errorCodeFailed, renderErr)
	}
	digest := sha256.Sum256(raw)
	receipt.MessageSha256 = fmt.Sprintf("%x", digest)
	outcome, transportErr := mailer.transport.Send(ctx, raw)
	return mailer.finishTransport(ctx, receipt, outcome, transportErr)
}

// classifyOutcome is the generated classifier: the declared `when` clauses plus
// the `otherwise` default, each mapped to its bounded metric label.
func classifyOutcome(outcome emailv1.DeliveryOutcome) (string, error) {
	switch outcome {
	case emailv1.DeliveryOutcome_DELIVERY_OUTCOME_ACCEPTED:
		return metricOutcomeAccepted, nil
	case emailv1.DeliveryOutcome_DELIVERY_OUTCOME_FAILED:
		return metricOutcomeFailed, nil
	default:
		return metricOutcomeUnknown, nil
	}
}

func newReceiptID() string { return uuid.NewString() }

func (mailer *Mailer) snapshot(ctx context.Context, recordedAt time.Time) *provenancev1.ReceiptMetadata {
	observed, err := mailer.provenance.Snapshot(ctx)
	if err != nil || observed == nil {
		return &provenancev1.ReceiptMetadata{
			SchemaVersion: receiptSchemaVersion,
			ReceiptId:     newReceiptID(),
			RecordedAt:    timestamppb.New(recordedAt),
			Unavailable:   []string{provenanceUnavailable},
		}
	}
	metadata := proto.Clone(observed).(*provenancev1.ReceiptMetadata)
	metadata.SchemaVersion = receiptSchemaVersion
	metadata.ReceiptId = newReceiptID()
	metadata.RecordedAt = timestamppb.New(recordedAt)
	return metadata
}

func newAttemptReceipt(mailer *Mailer, ctx context.Context, started time.Time) *emailv1.EmailReceipt {
	return &emailv1.EmailReceipt{
		Provenance: mailer.snapshot(ctx, started),
		Outcome:    emailv1.DeliveryOutcome_DELIVERY_OUTCOME_UNKNOWN,
		ErrorCode:  errorCodeAttempt,
	}
}

func (mailer *Mailer) record(ctx context.Context, receipt *emailv1.EmailReceipt) error {
	return mailer.receipts.Record(ctx, proto.Clone(receipt).(*emailv1.EmailReceipt))
}

func (mailer *Mailer) finishWithoutTransport(
	ctx context.Context,
	receipt *emailv1.EmailReceipt,
	errorCode string,
	cause error,
) (*emailv1.EmailReceipt, error) {
	receipt.Outcome = emailv1.DeliveryOutcome_DELIVERY_OUTCOME_FAILED
	receipt.ErrorCode = errorCode
	receipt.CompletedAt = timestamppb.New(mailer.now())
	if err := mailer.record(ctx, receipt); err != nil {
		receipt.ErrorCode = errorCodeSink
		cause = errors.Join(cause, fmt.Errorf("recording final receipt: %w", err))
	}
	return receipt, cause
}

func (mailer *Mailer) finishTransport(
	ctx context.Context,
	receipt *emailv1.EmailReceipt,
	outcome emailv1.DeliveryOutcome,
	transportErr error,
) (*emailv1.EmailReceipt, error) {
	normalized, transportErr := normalizeOutcome(outcome, transportErr)
	receipt.Outcome = normalized.outcome
	receipt.ErrorCode = normalized.code
	receipt.CompletedAt = timestamppb.New(mailer.now())
	if err := mailer.record(ctx, receipt); err != nil {
		receipt.ErrorCode = errorCodeSink
		transportErr = errors.Join(transportErr, fmt.Errorf("recording final receipt: %w", err))
	}
	return receipt, transportErr
}

// outcomeNormalization names one attempt's bounded outcome and its receipt
// error code together, so the two never split across an unnamed return.
type outcomeNormalization struct {
	outcome emailv1.DeliveryOutcome
	code    string
}

func normalizeOutcome(outcome emailv1.DeliveryOutcome, transportErr error) (outcomeNormalization, error) {
	switch outcome {
	case emailv1.DeliveryOutcome_DELIVERY_OUTCOME_ACCEPTED:
		return outcomeNormalization{outcome: outcome}, transportErr
	case emailv1.DeliveryOutcome_DELIVERY_OUTCOME_FAILED:
		if transportErr == nil {
			transportErr = ErrDeliveryFailed
		}
		return outcomeNormalization{outcome: outcome, code: errorCodeFailed}, transportErr
	case emailv1.DeliveryOutcome_DELIVERY_OUTCOME_UNKNOWN:
		if transportErr == nil {
			transportErr = ErrDeliveryUnknown
		} else {
			transportErr = errors.Join(ErrDeliveryUnknown, transportErr)
		}
		return outcomeNormalization{outcome: outcome, code: errorCodeUnknown}, transportErr
	default:
		return outcomeNormalization{
			outcome: emailv1.DeliveryOutcome_DELIVERY_OUTCOME_UNKNOWN,
			code:    errorCodeInvalid,
		}, errors.Join(ErrInvalidTransportOutcome, transportErr)
	}
}

func renderMessage(mailer *Mailer, message *emailv1.EmailMessage) ([]byte, error) {
	if message == nil {
		return nil, errors.New("email: message is nil")
	}
	if message.GetSubject() == "" {
		return nil, errors.New("email: subject is required")
	}
	header := "From: " + mailer.from + "\r\n" +
		"To: " + strings.Join(mailer.to, ", ") + "\r\n" +
		"Subject: " + message.GetSubject() + "\r\n" +
		"Date: " + mailer.now().UTC().Format(time.RFC1123Z) + "\r\n" +
		"MIME-Version: 1.0\r\n" +
		"Content-Type: text/plain; charset=\"utf-8\"\r\n\r\n"
	return []byte(header + message.GetText()), nil
}

// mailerMetrics holds the two metric families of the send operation.
type mailerMetrics struct {
	sends    *prometheus.CounterVec
	duration *prometheus.HistogramVec
}

// newMailerMetrics registers the send metrics. A nil registerer records
// nothing, so instrumentation is optional and off by default.
func newMailerMetrics(registerer prometheus.Registerer) (*mailerMetrics, error) {
	if registerer == nil {
		return nil, nil
	}
	sends, err := telemetry.RegisterOnce(registerer, prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "csf_email_send_total",
		Help: "Total bounded CSF email send outcomes; accepted is not inbox delivery.",
	}, []string{"outcome"}))
	if err != nil {
		return nil, err
	}
	duration, err := telemetry.RegisterOnce(registerer, prometheus.NewHistogramVec(prometheus.HistogramOpts{
		Name:    "csf_email_send_duration_seconds",
		Help:    "Duration of CSF email send attempts by bounded delivery outcome.",
		Buckets: prometheus.DefBuckets,
	}, []string{"outcome"}))
	if err != nil {
		return nil, err
	}
	return &mailerMetrics{sends: sends, duration: duration}, nil
}

// observe records one attempt's bounded outcome and its duration.
func (metrics *mailerMetrics) observe(outcome string, seconds float64) {
	if metrics == nil {
		return
	}
	metrics.sends.WithLabelValues(outcome).Inc()
	metrics.duration.WithLabelValues(outcome).Observe(seconds)
}
