// Code generated by csfc from csf/compiler/testdata/golden/service/email/email.csf; DO NOT EDIT.
//
// The transport capability: the interface the host binds, the option that sets
// it, and the error a missing boundary returns. The host chooses the transport;
// the service never invents one.

package email

import (
	"context"
	"errors"

	emailv1 "github.com/candacelabs/csf/proto/candace/email/v1"
)

// ErrNoTransport means no delivery transport was configured.
var ErrNoTransport = errors.New("email: transport is required")

// ITransport delivers one complete RFC 5322 message. ACCEPTED means the
// transport accepted the message; it does not prove inbox delivery.
type ITransport interface {
	Send(ctx context.Context, message []byte) (emailv1.DeliveryOutcome, error)
}

// WithTransport configures the delivery boundary.
func WithTransport(transport ITransport) Option {
	return func(config *mailerConfig) error {
		if transport == nil {
			return ErrNoTransport
		}
		config.transport = transport
		return nil
	}
}
