load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "docker",
    srcs = ["containers.go"],
    importpath = "github.com/candacelabs/csf/ipc/docker",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/boundedbuffer",
        "//pkg/boundedbuffer/v1:boundedbuffer",
        "@com_github_google_uuid//:uuid",
        "@com_github_moby_moby_api//pkg/stdcopy",
        "@com_github_moby_moby_api//types/container",
        "@com_github_moby_moby_api//types/mount",
        "@com_github_moby_moby_client//:client",
    ],
)

go_test(
    name = "docker_test",
    srcs = [
        "containers_test.go",
        "docker_suite_test.go",
        "engine_unit_test.go",
        "mock_container_api_test.go",
        "mock_generate_test.go",
    ],
    embed = [":docker"],
    deps = [
        "@com_github_moby_moby_api//pkg/stdcopy",
        "@com_github_moby_moby_api//types/container",
        "@com_github_moby_moby_client//:client",
        "@com_github_onsi_ginkgo_v2//:ginkgo",
        "@com_github_onsi_gomega//:gomega",
        "@org_uber_go_goleak//:goleak",
        "@org_uber_go_mock//gomock",
    ],
)
