// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/candacelabs/csf/io/ipc/docker (interfaces: IContainerAPI)
//
// Generated by this command:
//
//	mockgen -destination=mock_container_api_test.go -package=docker_test github.com/candacelabs/csf/io/ipc/docker IContainerAPI
//

// Package docker_test is a generated GoMock package.
package docker_test

import (
	context "context"
	reflect "reflect"

	client "github.com/moby/moby/client"
	gomock "go.uber.org/mock/gomock"
)

// MockIContainerAPI is a mock of IContainerAPI interface.
type MockIContainerAPI struct {
	ctrl     *gomock.Controller
	recorder *MockIContainerAPIMockRecorder
	isgomock struct{}
}

// MockIContainerAPIMockRecorder is the mock recorder for MockIContainerAPI.
type MockIContainerAPIMockRecorder struct {
	mock *MockIContainerAPI
}

// NewMockIContainerAPI creates a new mock instance.
func NewMockIContainerAPI(ctrl *gomock.Controller) *MockIContainerAPI {
	mock := &MockIContainerAPI{ctrl: ctrl}
	mock.recorder = &MockIContainerAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIContainerAPI) EXPECT() *MockIContainerAPIMockRecorder {
	return m.recorder
}

// BuildCachePrune mocks base method.
func (m *MockIContainerAPI) BuildCachePrune(ctx context.Context, options client.BuildCachePruneOptions) (client.BuildCachePruneResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildCachePrune", ctx, options)
	ret0, _ := ret[0].(client.BuildCachePruneResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuildCachePrune indicates an expected call of BuildCachePrune.
func (mr *MockIContainerAPIMockRecorder) BuildCachePrune(ctx, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildCachePrune", reflect.TypeOf((*MockIContainerAPI)(nil).BuildCachePrune), ctx, options)
}

// Close mocks base method.
func (m *MockIContainerAPI) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockIContainerAPIMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockIContainerAPI)(nil).Close))
}

// ContainerCreate mocks base method.
func (m *MockIContainerAPI) ContainerCreate(ctx context.Context, options client.ContainerCreateOptions) (client.ContainerCreateResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContainerCreate", ctx, options)
	ret0, _ := ret[0].(client.ContainerCreateResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContainerCreate indicates an expected call of ContainerCreate.
func (mr *MockIContainerAPIMockRecorder) ContainerCreate(ctx, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContainerCreate", reflect.TypeOf((*MockIContainerAPI)(nil).ContainerCreate), ctx, options)
}

// ContainerInspect mocks base method.
func (m *MockIContainerAPI) ContainerInspect(ctx context.Context, id string, options client.ContainerInspectOptions) (client.ContainerInspectResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContainerInspect", ctx, id, options)
	ret0, _ := ret[0].(client.ContainerInspectResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContainerInspect indicates an expected call of ContainerInspect.
func (mr *MockIContainerAPIMockRecorder) ContainerInspect(ctx, id, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContainerInspect", reflect.TypeOf((*MockIContainerAPI)(nil).ContainerInspect), ctx, id, options)
}

// ContainerKill mocks base method.
func (m *MockIContainerAPI) ContainerKill(ctx context.Context, id string, options client.ContainerKillOptions) (client.ContainerKillResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContainerKill", ctx, id, options)
	ret0, _ := ret[0].(client.ContainerKillResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContainerKill indicates an expected call of ContainerKill.
func (mr *MockIContainerAPIMockRecorder) ContainerKill(ctx, id, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContainerKill", reflect.TypeOf((*MockIContainerAPI)(nil).ContainerKill), ctx, id, options)
}

// ContainerList mocks base method.
func (m *MockIContainerAPI) ContainerList(ctx context.Context, options client.ContainerListOptions) (client.ContainerListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContainerList", ctx, options)
	ret0, _ := ret[0].(client.ContainerListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContainerList indicates an expected call of ContainerList.
func (mr *MockIContainerAPIMockRecorder) ContainerList(ctx, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContainerList", reflect.TypeOf((*MockIContainerAPI)(nil).ContainerList), ctx, options)
}

// ContainerLogs mocks base method.
func (m *MockIContainerAPI) ContainerLogs(ctx context.Context, id string, options client.ContainerLogsOptions) (client.ContainerLogsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContainerLogs", ctx, id, options)
	ret0, _ := ret[0].(client.ContainerLogsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContainerLogs indicates an expected call of ContainerLogs.
func (mr *MockIContainerAPIMockRecorder) ContainerLogs(ctx, id, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContainerLogs", reflect.TypeOf((*MockIContainerAPI)(nil).ContainerLogs), ctx, id, options)
}

// ContainerPause mocks base method.
func (m *MockIContainerAPI) ContainerPause(ctx context.Context, id string, options client.ContainerPauseOptions) (client.ContainerPauseResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContainerPause", ctx, id, options)
	ret0, _ := ret[0].(client.ContainerPauseResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContainerPause indicates an expected call of ContainerPause.
func (mr *MockIContainerAPIMockRecorder) ContainerPause(ctx, id, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContainerPause", reflect.TypeOf((*MockIContainerAPI)(nil).ContainerPause), ctx, id, options)
}

// ContainerRemove mocks base method.
func (m *MockIContainerAPI) ContainerRemove(ctx context.Context, id string, options client.ContainerRemoveOptions) (client.ContainerRemoveResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContainerRemove", ctx, id, options)
	ret0, _ := ret[0].(client.ContainerRemoveResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContainerRemove indicates an expected call of ContainerRemove.
func (mr *MockIContainerAPIMockRecorder) ContainerRemove(ctx, id, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContainerRemove", reflect.TypeOf((*MockIContainerAPI)(nil).ContainerRemove), ctx, id, options)
}

// ContainerStart mocks base method.
func (m *MockIContainerAPI) ContainerStart(ctx context.Context, id string, options client.ContainerStartOptions) (client.ContainerStartResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContainerStart", ctx, id, options)
	ret0, _ := ret[0].(client.ContainerStartResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContainerStart indicates an expected call of ContainerStart.
func (mr *MockIContainerAPIMockRecorder) ContainerStart(ctx, id, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContainerStart", reflect.TypeOf((*MockIContainerAPI)(nil).ContainerStart), ctx, id, options)
}

// ContainerStats mocks base method.
func (m *MockIContainerAPI) ContainerStats(ctx context.Context, id string, options client.ContainerStatsOptions) (client.ContainerStatsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContainerStats", ctx, id, options)
	ret0, _ := ret[0].(client.ContainerStatsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContainerStats indicates an expected call of ContainerStats.
func (mr *MockIContainerAPIMockRecorder) ContainerStats(ctx, id, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContainerStats", reflect.TypeOf((*MockIContainerAPI)(nil).ContainerStats), ctx, id, options)
}

// ContainerStop mocks base method.
func (m *MockIContainerAPI) ContainerStop(ctx context.Context, id string, options client.ContainerStopOptions) (client.ContainerStopResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContainerStop", ctx, id, options)
	ret0, _ := ret[0].(client.ContainerStopResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContainerStop indicates an expected call of ContainerStop.
func (mr *MockIContainerAPIMockRecorder) ContainerStop(ctx, id, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContainerStop", reflect.TypeOf((*MockIContainerAPI)(nil).ContainerStop), ctx, id, options)
}

// ContainerUnpause mocks base method.
func (m *MockIContainerAPI) ContainerUnpause(ctx context.Context, id string, options client.ContainerUnpauseOptions) (client.ContainerUnpauseResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContainerUnpause", ctx, id, options)
	ret0, _ := ret[0].(client.ContainerUnpauseResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContainerUnpause indicates an expected call of ContainerUnpause.
func (mr *MockIContainerAPIMockRecorder) ContainerUnpause(ctx, id, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContainerUnpause", reflect.TypeOf((*MockIContainerAPI)(nil).ContainerUnpause), ctx, id, options)
}

// ContainerWait mocks base method.
func (m *MockIContainerAPI) ContainerWait(ctx context.Context, id string, options client.ContainerWaitOptions) client.ContainerWaitResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContainerWait", ctx, id, options)
	ret0, _ := ret[0].(client.ContainerWaitResult)
	return ret0
}

// ContainerWait indicates an expected call of ContainerWait.
func (mr *MockIContainerAPIMockRecorder) ContainerWait(ctx, id, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContainerWait", reflect.TypeOf((*MockIContainerAPI)(nil).ContainerWait), ctx, id, options)
}

// DiskUsage mocks base method.
func (m *MockIContainerAPI) DiskUsage(ctx context.Context, options client.DiskUsageOptions) (client.DiskUsageResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DiskUsage", ctx, options)
	ret0, _ := ret[0].(client.DiskUsageResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DiskUsage indicates an expected call of DiskUsage.
func (mr *MockIContainerAPIMockRecorder) DiskUsage(ctx, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DiskUsage", reflect.TypeOf((*MockIContainerAPI)(nil).DiskUsage), ctx, options)
}

// ExecAttach mocks base method.
func (m *MockIContainerAPI) ExecAttach(ctx context.Context, execID string, options client.ExecAttachOptions) (client.ExecAttachResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecAttach", ctx, execID, options)
	ret0, _ := ret[0].(client.ExecAttachResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecAttach indicates an expected call of ExecAttach.
func (mr *MockIContainerAPIMockRecorder) ExecAttach(ctx, execID, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecAttach", reflect.TypeOf((*MockIContainerAPI)(nil).ExecAttach), ctx, execID, options)
}

// ExecCreate mocks base method.
func (m *MockIContainerAPI) ExecCreate(ctx context.Context, containerID string, options client.ExecCreateOptions) (client.ExecCreateResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecCreate", ctx, containerID, options)
	ret0, _ := ret[0].(client.ExecCreateResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecCreate indicates an expected call of ExecCreate.
func (mr *MockIContainerAPIMockRecorder) ExecCreate(ctx, containerID, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecCreate", reflect.TypeOf((*MockIContainerAPI)(nil).ExecCreate), ctx, containerID, options)
}

// ExecInspect mocks base method.
func (m *MockIContainerAPI) ExecInspect(ctx context.Context, execID string, options client.ExecInspectOptions) (client.ExecInspectResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecInspect", ctx, execID, options)
	ret0, _ := ret[0].(client.ExecInspectResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecInspect indicates an expected call of ExecInspect.
func (mr *MockIContainerAPIMockRecorder) ExecInspect(ctx, execID, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecInspect", reflect.TypeOf((*MockIContainerAPI)(nil).ExecInspect), ctx, execID, options)
}

// ImageList mocks base method.
func (m *MockIContainerAPI) ImageList(ctx context.Context, options client.ImageListOptions) (client.ImageListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImageList", ctx, options)
	ret0, _ := ret[0].(client.ImageListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ImageList indicates an expected call of ImageList.
func (mr *MockIContainerAPIMockRecorder) ImageList(ctx, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImageList", reflect.TypeOf((*MockIContainerAPI)(nil).ImageList), ctx, options)
}

// ImagePrune mocks base method.
func (m *MockIContainerAPI) ImagePrune(ctx context.Context, options client.ImagePruneOptions) (client.ImagePruneResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImagePrune", ctx, options)
	ret0, _ := ret[0].(client.ImagePruneResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ImagePrune indicates an expected call of ImagePrune.
func (mr *MockIContainerAPIMockRecorder) ImagePrune(ctx, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImagePrune", reflect.TypeOf((*MockIContainerAPI)(nil).ImagePrune), ctx, options)
}

// ImagePull mocks base method.
func (m *MockIContainerAPI) ImagePull(ctx context.Context, reference string, options client.ImagePullOptions) (client.ImagePullResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImagePull", ctx, reference, options)
	ret0, _ := ret[0].(client.ImagePullResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ImagePull indicates an expected call of ImagePull.
func (mr *MockIContainerAPIMockRecorder) ImagePull(ctx, reference, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImagePull", reflect.TypeOf((*MockIContainerAPI)(nil).ImagePull), ctx, reference, options)
}
