// Code generated by MockGen. DO NOT EDIT.
// Source: check.go
//
// Generated by this command:
//
//	mockgen -source=check.go -destination=mocks/mock_check.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	proc "github.com/candacelabs/csf/io/ipc/proc"
	gomock "go.uber.org/mock/gomock"
)

// MockIHostMeasures is a mock of IHostMeasures interface.
type MockIHostMeasures struct {
	ctrl     *gomock.Controller
	recorder *MockIHostMeasuresMockRecorder
	isgomock struct{}
}

// MockIHostMeasuresMockRecorder is the mock recorder for MockIHostMeasures.
type MockIHostMeasuresMockRecorder struct {
	mock *MockIHostMeasures
}

// NewMockIHostMeasures creates a new mock instance.
func NewMockIHostMeasures(ctrl *gomock.Controller) *MockIHostMeasures {
	mock := &MockIHostMeasures{ctrl: ctrl}
	mock.recorder = &MockIHostMeasuresMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIHostMeasures) EXPECT() *MockIHostMeasuresMockRecorder {
	return m.recorder
}

// Cores mocks base method.
func (m *MockIHostMeasures) Cores() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cores")
	ret0, _ := ret[0].(int)
	return ret0
}

// Cores indicates an expected call of Cores.
func (mr *MockIHostMeasuresMockRecorder) Cores() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cores", reflect.TypeOf((*MockIHostMeasures)(nil).Cores))
}

// DirectoryBytes mocks base method.
func (m *MockIHostMeasures) DirectoryBytes(directory string) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DirectoryBytes", directory)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DirectoryBytes indicates an expected call of DirectoryBytes.
func (mr *MockIHostMeasuresMockRecorder) DirectoryBytes(directory any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DirectoryBytes", reflect.TypeOf((*MockIHostMeasures)(nil).DirectoryBytes), directory)
}

// FreeBytes mocks base method.
func (m *MockIHostMeasures) FreeBytes(path string) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FreeBytes", path)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FreeBytes indicates an expected call of FreeBytes.
func (mr *MockIHostMeasuresMockRecorder) FreeBytes(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FreeBytes", reflect.TypeOf((*MockIHostMeasures)(nil).FreeBytes), path)
}

// LoadAverage mocks base method.
func (m *MockIHostMeasures) LoadAverage() (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadAverage")
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadAverage indicates an expected call of LoadAverage.
func (mr *MockIHostMeasuresMockRecorder) LoadAverage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadAverage", reflect.TypeOf((*MockIHostMeasures)(nil).LoadAverage))
}

// MemoryAvailable mocks base method.
func (m *MockIHostMeasures) MemoryAvailable() (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MemoryAvailable")
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MemoryAvailable indicates an expected call of MemoryAvailable.
func (mr *MockIHostMeasuresMockRecorder) MemoryAvailable() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MemoryAvailable", reflect.TypeOf((*MockIHostMeasures)(nil).MemoryAvailable))
}

// Pressure mocks base method.
func (m *MockIHostMeasures) Pressure(resource proc.PressureResource) (proc.Pressure, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pressure", resource)
	ret0, _ := ret[0].(proc.Pressure)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Pressure indicates an expected call of Pressure.
func (mr *MockIHostMeasuresMockRecorder) Pressure(resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pressure", reflect.TypeOf((*MockIHostMeasures)(nil).Pressure), resource)
}

// MockIClock is a mock of IClock interface.
type MockIClock struct {
	ctrl     *gomock.Controller
	recorder *MockIClockMockRecorder
	isgomock struct{}
}

// MockIClockMockRecorder is the mock recorder for MockIClock.
type MockIClockMockRecorder struct {
	mock *MockIClock
}

// NewMockIClock creates a new mock instance.
func NewMockIClock(ctrl *gomock.Controller) *MockIClock {
	mock := &MockIClock{ctrl: ctrl}
	mock.recorder = &MockIClockMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIClock) EXPECT() *MockIClockMockRecorder {
	return m.recorder
}

// After mocks base method.
func (m *MockIClock) After(d time.Duration) (<-chan time.Time, func() bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "After", d)
	ret0, _ := ret[0].(<-chan time.Time)
	ret1, _ := ret[1].(func() bool)
	return ret0, ret1
}

// After indicates an expected call of After.
func (mr *MockIClockMockRecorder) After(d any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "After", reflect.TypeOf((*MockIClock)(nil).After), d)
}

// AfterFunc mocks base method.
func (m *MockIClock) AfterFunc(d time.Duration, f func()) func() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AfterFunc", d, f)
	ret0, _ := ret[0].(func() bool)
	return ret0
}

// AfterFunc indicates an expected call of AfterFunc.
func (mr *MockIClockMockRecorder) AfterFunc(d, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AfterFunc", reflect.TypeOf((*MockIClock)(nil).AfterFunc), d, f)
}

// Now mocks base method.
func (m *MockIClock) Now() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Now")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// Now indicates an expected call of Now.
func (mr *MockIClockMockRecorder) Now() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Now", reflect.TypeOf((*MockIClock)(nil).Now))
}
