load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "adaptertest",
    srcs = [
        "memory_listener.go",
        "mock_network.go",
        "server.go",
        "store.go",
    ],
    importpath = "github.com/candacelabs/csf/services/copilot-adapter/adaptertest",
    visibility = ["//visibility:public"],
    deps = [
        "//io/net/http",
        "//pkg/pgmem",
        "//pkg/sqlmigrate",
        "//runtime",
        "//services/copilot-adapter",
        "//services/copilot-adapter/store",
        "@org_uber_go_mock//gomock",
    ],
)

go_test(
    name = "adaptertest_test",
    srcs = [
        "adaptertest_suite_test.go",
        "server_test.go",
    ],
    deps = [
        ":adaptertest",
        "@com_github_onsi_ginkgo_v2//:ginkgo",
        "@com_github_onsi_gomega//:gomega",
    ],
)
