// Code generated by protoc-gen-liquidproto. DO NOT EDIT.
// versions:
// 	protoc-gen-liquidproto v0.1.0
// 	protoc                 v7.35.1
// source: candace/intake/v1/intake.proto

package intakev1

import (
	fmt "fmt"
	liquidproto "github.com/candacelabs/csf/pkg/liquidproto"
	regexp "regexp"
)

var (
	_liquidSubjectRepositoryRe0 = regexp.MustCompile("^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$")
)

// ValidateSubject checks this message's annotated fields; it does not recurse.
// A failed predicate returns *liquidproto.Error. Nil input also returns an error.
func ValidateSubject(message *Subject) error {
	if message == nil {
		return fmt.Errorf("ValidateSubject: nil *Subject")
	}
	if !(_liquidSubjectRepositoryRe0.MatchString(message.Repository)) {
		return &liquidproto.Error{
			Message:   "candace.intake.v1.Subject",
			Field:     "repository",
			Predicate: "matches(this, `^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$`)",
			Value:     message.Repository,
		}
	}
	return nil
}

// ValidateEvent checks this message's annotated fields; it does not recurse.
// A failed predicate returns *liquidproto.Error. Nil input also returns an error.
func ValidateEvent(message *Event) error {
	if message == nil {
		return fmt.Errorf("ValidateEvent: nil *Event")
	}
	if !(len(message.Id) >= 1 && len(message.Id) <= 256) {
		return &liquidproto.Error{
			Message:   "candace.intake.v1.Event",
			Field:     "id",
			Predicate: "len(this) >= 1 && len(this) <= 256",
			Value:     message.Id,
		}
	}
	if !(len(message.Summary) <= 4096) {
		return &liquidproto.Error{
			Message:   "candace.intake.v1.Event",
			Field:     "summary",
			Predicate: "len(this) <= 4096",
			Value:     message.Summary,
		}
	}
	if !(len(message.Branch) <= 255) {
		return &liquidproto.Error{
			Message:   "candace.intake.v1.Event",
			Field:     "branch",
			Predicate: "len(this) <= 255",
			Value:     message.Branch,
		}
	}
	if !(len(message.Base) <= 255) {
		return &liquidproto.Error{
			Message:   "candace.intake.v1.Event",
			Field:     "base",
			Predicate: "len(this) <= 255",
			Value:     message.Base,
		}
	}
	if !(len(message.Conclusion) <= 64) {
		return &liquidproto.Error{
			Message:   "candace.intake.v1.Event",
			Field:     "conclusion",
			Predicate: "len(this) <= 64",
			Value:     message.Conclusion,
		}
	}
	if !(len(message.Delivery) <= 64) {
		return &liquidproto.Error{
			Message:   "candace.intake.v1.Event",
			Field:     "delivery",
			Predicate: "len(this) <= 64",
			Value:     message.Delivery,
		}
	}
	return nil
}
