// Copyright 2026 Candace Labs

package pgmem

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"sync/atomic"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
)

// PGX is an in-process substitute for an out-of-process PostgreSQL pool
// (csfpg.OpenPool), for tests: it serves the pgx query surface over a
// schema, the Exec, Query and QueryRow methods of the DBTX interface sqlc
// generates, plus Begin, BeginTx and Ping. Code generated by sqlc with sql_package pgx/v5 runs against pgmem
// unchanged, and PGX satisfies candace/ipc/db/csfpg.IDB. Values cross the
// database/sql conversion: parameters through driver.Valuer, which pgtype
// values implement, and results through sql.Scanner, which pgtype values and
// sqlc enum types implement.
//
// Not emulated: CopyFrom, SendBatch, Prepare, large objects and the
// underlying *pgx.Conn, which report ErrPGXUnsupported or return nil;
// transaction isolation levels and read-only mode, because the engine runs
// every transaction serially on one connection. FieldDescriptions carry
// column names only, and RawValues is nil.
type PGX struct {
	db     *sql.DB
	closed atomic.Bool
}

// ErrPGXUnsupported reports a pgx feature PGX does not emulate.
var ErrPGXUnsupported = errors.New("pgmem: pgx feature not emulated")

// ErrPGXClosed reports a call on a PGX after Close.
var ErrPGXClosed = errors.New("pgmem: pgx surface closed")

// OpenPGX returns the pgx surface over this schema. Close it before the DB.
func (s *Schema) OpenPGX() *PGX {
	return &PGX{db: s.Open()}
}

// Close releases the underlying handle. Every later call except Close
// reports ErrPGXClosed; a second Close does nothing.
func (p *PGX) Close() error {
	if p.closed.Swap(true) {
		return nil
	}
	return p.db.Close()
}

func (p *PGX) usable() error {
	if p.closed.Load() {
		return ErrPGXClosed
	}
	return nil
}

type iSQLExecutor interface {
	ExecContext(ctx context.Context, query string, arguments ...any) (sql.Result, error)
	QueryContext(ctx context.Context, query string, arguments ...any) (*sql.Rows, error)
}

// Exec runs a statement and reports its command tag.
func (p *PGX) Exec(ctx context.Context, statement string, arguments ...any) (pgconn.CommandTag, error) {
	if err := p.usable(); err != nil {
		return pgconn.CommandTag{}, err
	}
	return execTag(ctx, p.db, statement, arguments)
}

// Query runs a row-returning statement.
func (p *PGX) Query(ctx context.Context, statement string, arguments ...any) (pgx.Rows, error) {
	if err := p.usable(); err != nil {
		return nil, err
	}
	return queryRows(ctx, p.db, statement, arguments)
}

// QueryRow runs a statement expected to return one row. Its Scan reports
// pgx.ErrNoRows when the statement returned none.
func (p *PGX) QueryRow(ctx context.Context, statement string, arguments ...any) pgx.Row {
	if err := p.usable(); err != nil {
		return &pgxRow{err: err}
	}
	return queryRow(ctx, p.db, statement, arguments)
}

// Begin starts a transaction.
func (p *PGX) Begin(ctx context.Context) (pgx.Tx, error) {
	return p.BeginTx(ctx, pgx.TxOptions{})
}

// BeginTx starts a transaction. The options are accepted and not enforced.
func (p *PGX) BeginTx(ctx context.Context, options pgx.TxOptions) (pgx.Tx, error) {
	if err := p.usable(); err != nil {
		return nil, err
	}
	transaction, err := p.db.BeginTx(ctx, nil)
	if err != nil {
		return nil, err
	}
	return &pgxTx{transaction: transaction}, nil
}

// Ping reports whether the schema answers.
func (p *PGX) Ping(ctx context.Context) error {
	if err := p.usable(); err != nil {
		return err
	}
	return p.db.PingContext(ctx)
}

func execTag(ctx context.Context, executor iSQLExecutor, statement string, arguments []any) (pgconn.CommandTag, error) {
	result, err := executor.ExecContext(ctx, statement, arguments...)
	if err != nil {
		return pgconn.CommandTag{}, err
	}
	affected, err := result.RowsAffected()
	if err != nil {
		return pgconn.CommandTag{}, err
	}
	return commandTag(statement, affected), nil
}

const (
	insertCommand  = "INSERT"
	insertTagForm  = "%s 0 %d"
	commandTagForm = "%s %d"
)

// commandTag renders the PostgreSQL tag: INSERT 0 n, or the command and n.
func commandTag(statement string, rows int64) pgconn.CommandTag {
	command := statementCommand(statement)
	if command == insertCommand {
		return pgconn.NewCommandTag(fmt.Sprintf(insertTagForm, command, rows))
	}
	return pgconn.NewCommandTag(fmt.Sprintf(commandTagForm, command, rows))
}

func queryRows(ctx context.Context, executor iSQLExecutor, statement string, arguments []any) (pgx.Rows, error) {
	rows, err := executor.QueryContext(ctx, statement, arguments...)
	if err != nil {
		return nil, err
	}
	return &pgxRows{rows: rows, statement: statement}, nil
}

func queryRow(ctx context.Context, executor iSQLExecutor, statement string, arguments []any) pgx.Row {
	rows, err := queryRows(ctx, executor, statement, arguments)
	return &pgxRow{rows: rows, err: err}
}

type pgxRows struct {
	rows      *sql.Rows
	statement string
	count     int64
	err       error
	closed    bool
}

func (r *pgxRows) Close() {
	if r.closed {
		return
	}
	r.closed = true
	if err := r.rows.Close(); err != nil && r.err == nil {
		r.err = err
	}
}

func (r *pgxRows) Err() error {
	if r.err != nil {
		return r.err
	}
	return r.rows.Err()
}

func (r *pgxRows) CommandTag() pgconn.CommandTag { return commandTag(r.statement, r.count) }

func (r *pgxRows) FieldDescriptions() []pgconn.FieldDescription {
	columns, err := r.rows.Columns()
	if err != nil {
		return nil
	}
	descriptions := make([]pgconn.FieldDescription, len(columns))
	for index, name := range columns {
		descriptions[index] = pgconn.FieldDescription{Name: name}
	}
	return descriptions
}

func (r *pgxRows) Next() bool {
	if r.closed {
		return false
	}
	if r.rows.Next() {
		r.count++
		return true
	}
	r.err = r.rows.Err()
	r.Close()
	return false
}

func (r *pgxRows) Scan(destinations ...any) error { return r.rows.Scan(destinations...) }

func (r *pgxRows) Values() ([]any, error) {
	columns, err := r.rows.Columns()
	if err != nil {
		return nil, err
	}
	values := make([]any, len(columns))
	pointers := make([]any, len(columns))
	for index := range values {
		pointers[index] = &values[index]
	}
	if err := r.rows.Scan(pointers...); err != nil {
		return nil, err
	}
	return values, nil
}

func (r *pgxRows) RawValues() [][]byte { return nil }

func (r *pgxRows) Conn() *pgx.Conn { return nil }

type pgxRow struct {
	rows pgx.Rows
	err  error
}

func (r *pgxRow) Scan(destinations ...any) error {
	if r.err != nil {
		return r.err
	}
	defer r.rows.Close()
	if !r.rows.Next() {
		if err := r.rows.Err(); err != nil {
			return err
		}
		return pgx.ErrNoRows
	}
	if err := r.rows.Scan(destinations...); err != nil {
		return err
	}
	r.rows.Close()
	return r.rows.Err()
}

const (
	savepointSQL         = "SAVEPOINT %s"
	releaseSavepointSQL  = "RELEASE SAVEPOINT %s"
	rollbackSavepointSQL = "ROLLBACK TO SAVEPOINT %s"
	savepointNameForm    = "pgmem_savepoint_%d"
)

// pgxTx is a transaction, or a savepoint inside one when savepoint is set,
// which is how pgx nests Begin on a transaction.
type pgxTx struct {
	transaction *sql.Tx
	savepoint   string
	depth       int
	finished    bool
}

func (t *pgxTx) Begin(ctx context.Context) (pgx.Tx, error) {
	if t.finished {
		return nil, pgx.ErrTxClosed
	}
	name := fmt.Sprintf(savepointNameForm, t.depth+1)
	if _, err := t.transaction.ExecContext(ctx, fmt.Sprintf(savepointSQL, name)); err != nil {
		return nil, err
	}
	return &pgxTx{transaction: t.transaction, savepoint: name, depth: t.depth + 1}, nil
}

func (t *pgxTx) Commit(ctx context.Context) error {
	if t.finished {
		return pgx.ErrTxClosed
	}
	t.finished = true
	if t.savepoint == "" {
		return t.transaction.Commit()
	}
	_, err := t.transaction.ExecContext(ctx, fmt.Sprintf(releaseSavepointSQL, t.savepoint))
	return err
}

func (t *pgxTx) Rollback(ctx context.Context) error {
	if t.finished {
		return pgx.ErrTxClosed
	}
	t.finished = true
	if t.savepoint == "" {
		return t.transaction.Rollback()
	}
	if _, err := t.transaction.ExecContext(ctx, fmt.Sprintf(rollbackSavepointSQL, t.savepoint)); err != nil {
		return err
	}
	_, err := t.transaction.ExecContext(ctx, fmt.Sprintf(releaseSavepointSQL, t.savepoint))
	return err
}

func (t *pgxTx) CopyFrom(ctx context.Context, tableName pgx.Identifier, columnNames []string, rowSource pgx.CopyFromSource) (int64, error) {
	return 0, ErrPGXUnsupported
}

func (t *pgxTx) SendBatch(ctx context.Context, batch *pgx.Batch) pgx.BatchResults {
	return unsupportedBatch{}
}

func (t *pgxTx) LargeObjects() pgx.LargeObjects { return pgx.LargeObjects{} }

func (t *pgxTx) Prepare(ctx context.Context, name string, statement string) (*pgconn.StatementDescription, error) {
	return nil, ErrPGXUnsupported
}

func (t *pgxTx) Exec(ctx context.Context, statement string, arguments ...any) (pgconn.CommandTag, error) {
	return execTag(ctx, t.transaction, statement, arguments)
}

func (t *pgxTx) Query(ctx context.Context, statement string, arguments ...any) (pgx.Rows, error) {
	return queryRows(ctx, t.transaction, statement, arguments)
}

func (t *pgxTx) QueryRow(ctx context.Context, statement string, arguments ...any) pgx.Row {
	return queryRow(ctx, t.transaction, statement, arguments)
}

func (t *pgxTx) Conn() *pgx.Conn { return nil }

// unsupportedBatch answers every batch call with ErrPGXUnsupported.
type unsupportedBatch struct{}

func (unsupportedBatch) Exec() (pgconn.CommandTag, error) {
	return pgconn.CommandTag{}, ErrPGXUnsupported
}
func (unsupportedBatch) Query() (pgx.Rows, error) { return nil, ErrPGXUnsupported }
func (unsupportedBatch) QueryRow() pgx.Row        { return &pgxRow{err: ErrPGXUnsupported} }
func (unsupportedBatch) Close() error             { return ErrPGXUnsupported }
