// Code generated by MockGen. DO NOT EDIT.
// Source: ../../../ipc/ros/spine.go
//
// Generated by this command:
//
//	mockgen -source=../../../ipc/ros/spine.go -destination=mock_spine_test.go -package=main
//

// Package main is a generated GoMock package.
package main

import (
	context "context"
	reflect "reflect"

	brainspinev1 "github.com/candacelabs/csf/proto/candace/brainspine/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockISpine is a mock of ISpine interface.
type MockISpine struct {
	ctrl     *gomock.Controller
	recorder *MockISpineMockRecorder
	isgomock struct{}
}

// MockISpineMockRecorder is the mock recorder for MockISpine.
type MockISpineMockRecorder struct {
	mock *MockISpine
}

// NewMockISpine creates a new mock instance.
func NewMockISpine(ctrl *gomock.Controller) *MockISpine {
	mock := &MockISpine{ctrl: ctrl}
	mock.recorder = &MockISpineMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISpine) EXPECT() *MockISpineMockRecorder {
	return m.recorder
}

// Observe mocks base method.
func (m *MockISpine) Observe(ctx context.Context) (*brainspinev1.Observation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Observe", ctx)
	ret0, _ := ret[0].(*brainspinev1.Observation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Observe indicates an expected call of Observe.
func (mr *MockISpineMockRecorder) Observe(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Observe", reflect.TypeOf((*MockISpine)(nil).Observe), ctx)
}

// Submit mocks base method.
func (m *MockISpine) Submit(ctx context.Context, action *brainspinev1.Action) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Submit", ctx, action)
	ret0, _ := ret[0].(error)
	return ret0
}

// Submit indicates an expected call of Submit.
func (mr *MockISpineMockRecorder) Submit(ctx, action any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Submit", reflect.TypeOf((*MockISpine)(nil).Submit), ctx, action)
}
