#!/usr/bin/env bash
# golden_first step 4 (issue #475): the rest_client template engine's driver.
#
#   write  emits the two Go projections into csf/compiler/testdata/golden/rest_client/;
#   check  emits them into a scratch directory and diffs against the golden.
#
# The declaration is csf/compiler/testdata/golden/rest_client/rest_client.csf;
# the templates are the golden's own rest.go and hfjobs.go with the values the
# declaration names spelled as {{name}} placeholders. check failing therefore
# means the declaration, a template, or the committed golden drifted apart.
# Both outputs carry a "Code generated by csfc" header, so go build ./... and
# the handwritten corpus skip them.
set -Eeuo pipefail

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
module_root="$(cd -- "${script_dir}/../../.." && pwd -P)"
mode="${1:-write}"
case "${mode}" in
  write|check) ;;
  *) printf 'usage: %s [write|check]\n' "${0##*/}" >&2; exit 2 ;;
esac

export CANDACE_BAZEL_WORKSPACE="${module_root}"
bash "${module_root}/tools/bazel.sh" build //csf/compiler/rest_codegen:template --lockfile_mode=error >&2
generator="${module_root}/bazel-bin/csf/compiler/rest_codegen/template.exe"
[[ -x "${generator}" ]] || { printf 'rest_codegen: the build produced no template.exe\n' >&2; exit 2; }

temporary="$(mktemp -d "${TMPDIR:-/tmp}/candace-rest-codegen.XXXXXX")"
trap 'rm -rf -- "${temporary}"' EXIT

"${generator}" \
  "${module_root}/csf/compiler/rest_codegen/rest.go.tmpl" \
  "${module_root}/csf/compiler/rest_codegen/hfjobs.go.tmpl" \
  "${module_root}/csf/compiler/testdata/golden/rest_client/rest_client.csf" \
  "${temporary}"

# The paths the generator names, and where the golden keeps them.
globs=(io/net/rest/rest.go io/net/hfjobs/hfjobs.go)
golden_root="${module_root}/csf/compiler/testdata/golden/rest_client"
for glob in "${globs[@]}"; do
  if [[ "${mode}" == check ]]; then
    diff -u "${golden_root}/${glob}" "${temporary}/${glob}"
  else
    cp "${temporary}/${glob}" "${golden_root}/${glob}"
  fi
done
printf 'rest_codegen: %s passed\n' "${mode}"
