load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "housekeeping",
    srcs = [
        "housekeeper_backup.go",
        "housekeeper_cache.go",
        "housekeeper_checkout.go",
        "housekeeper_disk.go",
        "housekeeper_docker.go",
        "housekeeper_processes.go",
        "housekeeper_records.go",
        "housekeeper_sessions.go",
        "housekeeping.go",
    ],
    importpath = "github.com/candacelabs/csf/services/housekeeping",
    visibility = ["//visibility:public"],
    deps = [
        "//io/ipc/docker",
        "//io/ipc/proc",
        "//io/kernel/clock",
        "//io/kernel/fs",
        "//pkg/cron",
        "//proto/candace/harness/v1:harness",
        "//services/cron",
        "//services/database",
        "//services/harness",
        "//services/harness/session",
        "//services/intake",
        "@com_github_moby_moby_api//types/container",
        "@com_github_moby_moby_client//:client",
    ],
)

go_test(
    name = "housekeeping_test",
    srcs = [
        "backup_test.go",
        "checkout_test.go",
        "housekeeping_suite_test.go",
        "housekeeping_test.go",
        "mock_generate_test.go",
        "mock_launcher_test.go",
    ],
    deps = [
        ":housekeeping",
        "//io/ipc/docker",
        "//io/ipc/proc",
        "//io/kernel/clock",
        "//pkg/eventually",
        "//proto/candace/harness/v1:harness",
        "//runtime",
        "//services/cron",
        "//services/cron/crontest",
        "//services/database",
        "//services/housekeeping/mocks",
        "@com_github_moby_moby_api//types/build",
        "@com_github_moby_moby_api//types/container",
        "@com_github_moby_moby_api//types/image",
        "@com_github_moby_moby_client//:client",
        "@com_github_onsi_ginkgo_v2//:ginkgo",
        "@com_github_onsi_gomega//:gomega",
        "@org_uber_go_mock//gomock",
    ],
)
