// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/candacelabs/csf/services/views (interfaces: IContainers)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_stack.go -package=mocks github.com/candacelabs/csf/services/views IContainers
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	docker "github.com/candacelabs/csf/io/ipc/docker"
	gomock "go.uber.org/mock/gomock"
)

// MockIContainers is a mock of IContainers interface.
type MockIContainers struct {
	ctrl     *gomock.Controller
	recorder *MockIContainersMockRecorder
	isgomock struct{}
}

// MockIContainersMockRecorder is the mock recorder for MockIContainers.
type MockIContainersMockRecorder struct {
	mock *MockIContainers
}

// NewMockIContainers creates a new mock instance.
func NewMockIContainers(ctrl *gomock.Controller) *MockIContainers {
	mock := &MockIContainers{ctrl: ctrl}
	mock.recorder = &MockIContainersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIContainers) EXPECT() *MockIContainersMockRecorder {
	return m.recorder
}

// EnsureService mocks base method.
func (m *MockIContainers) EnsureService(ctx context.Context, spec docker.ServiceSpec) (docker.ServiceState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureService", ctx, spec)
	ret0, _ := ret[0].(docker.ServiceState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnsureService indicates an expected call of EnsureService.
func (mr *MockIContainersMockRecorder) EnsureService(ctx, spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureService", reflect.TypeOf((*MockIContainers)(nil).EnsureService), ctx, spec)
}

// Exec mocks base method.
func (m *MockIContainers) Exec(ctx context.Context, name string, spec docker.ExecSpec) (docker.ExecResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exec", ctx, name, spec)
	ret0, _ := ret[0].(docker.ExecResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockIContainersMockRecorder) Exec(ctx, name, spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockIContainers)(nil).Exec), ctx, name, spec)
}

// InspectService mocks base method.
func (m *MockIContainers) InspectService(ctx context.Context, name string) (docker.ServiceState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InspectService", ctx, name)
	ret0, _ := ret[0].(docker.ServiceState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InspectService indicates an expected call of InspectService.
func (mr *MockIContainersMockRecorder) InspectService(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InspectService", reflect.TypeOf((*MockIContainers)(nil).InspectService), ctx, name)
}

// SignalService mocks base method.
func (m *MockIContainers) SignalService(ctx context.Context, name, signal string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignalService", ctx, name, signal)
	ret0, _ := ret[0].(error)
	return ret0
}

// SignalService indicates an expected call of SignalService.
func (mr *MockIContainersMockRecorder) SignalService(ctx, name, signal any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignalService", reflect.TypeOf((*MockIContainers)(nil).SignalService), ctx, name, signal)
}

// StopService mocks base method.
func (m *MockIContainers) StopService(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopService", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// StopService indicates an expected call of StopService.
func (mr *MockIContainersMockRecorder) StopService(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopService", reflect.TypeOf((*MockIContainers)(nil).StopService), ctx, name)
}
