load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "mocks",
    srcs = [
        "mock_database.go",
        "mock_pgx.go",
    ],
    importpath = "github.com/candacelabs/csf/io/ipc/db/csfpg/mocks",
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_jackc_pgx_v5//:pgx",
        "@com_github_jackc_pgx_v5//pgconn",
        "@org_uber_go_mock//gomock",
    ],
)
