// Code generated by csfc from csf/compiler/testdata/golden/github_gate/github_gate.csf; DO NOT EDIT.
//
// github_gate: a session reaches GitHub through CSF's typed GitHub tools,
// which record every call, so a gh pr, gh issue or gh api command in the
// Bash shell is refused and names the tool that replaces it.

package sessiongate

import (
	"context"
	"fmt"
	"log/slog"
	"slices"
	"strings"

	"mvdan.cc/sh/v3/syntax"

	"github.com/candacelabs/csf/csf/githubtools"
	"github.com/candacelabs/csf/services/harness/session"
)

// The gate's name and its one rule, as the event log records them.
const (
	// GateGitHub is the PreToolUse gate on Bash that refuses a gh command
	// reaching GitHub's issues, pull requests or API.
	GateGitHub = "github"
	// RuleGitHubShell is a gh pr, gh issue or gh api command.
	RuleGitHubShell Rule = "github_shell"

	mcpToolPrefix = "mcp__" + session.MCPServerName + "__"
	toolList      = "csf github -list"
)

// GithubWord is a gh noun the gate names: the first word after gh.
type GithubWord string

// The gh nouns. WordAPI reaches the API directly and names no verb.
const (
	WordPullRequest GithubWord = "pr"
	WordIssue       GithubWord = "issue"
	WordAPI         GithubWord = "api"
)

// GithubVerb is a gh verb the gate maps to one CSF tool.
type GithubVerb string

// The gh verbs that name a tool.
const (
	VerbList    GithubVerb = "list"
	VerbCreate  GithubVerb = "create"
	VerbReady   GithubVerb = "ready"
	VerbMerge   GithubVerb = "merge"
	VerbView    GithubVerb = "view"
	VerbChecks  GithubVerb = "checks"
	VerbEdit    GithubVerb = "edit"
	VerbClose   GithubVerb = "close"
	VerbReopen  GithubVerb = "reopen"
	VerbComment GithubVerb = "comment"
)

// GithubReplacement is one typed fact: replacement(Word, Verb, Tool), the CSF
// tool that replaces the gh command "gh Word Verb". The relation is a typed
// list, never a map of spellings.
type GithubReplacement struct {
	Word GithubWord
	Verb GithubVerb
	Tool string
}

// GithubReplacements is the replacement relation, in declaration order.
var GithubReplacements = []GithubReplacement{
	{Word: WordPullRequest, Verb: VerbCreate, Tool: githubtools.ToolPullsCreate},
	{Word: WordPullRequest, Verb: VerbReady, Tool: githubtools.ToolMarkPullRequestReady},
	{Word: WordPullRequest, Verb: VerbMerge, Tool: githubtools.ToolPullsMerge},
	{Word: WordPullRequest, Verb: VerbList, Tool: githubtools.ToolPullsList},
	{Word: WordPullRequest, Verb: VerbView, Tool: githubtools.ToolPullsGet},
	{Word: WordPullRequest, Verb: VerbChecks, Tool: githubtools.ToolChecksListForRef},
	{Word: WordPullRequest, Verb: VerbEdit, Tool: githubtools.ToolPullsUpdate},
	{Word: WordPullRequest, Verb: VerbClose, Tool: githubtools.ToolPullsUpdate},
	{Word: WordPullRequest, Verb: VerbComment, Tool: githubtools.ToolIssuesCreateComment},

	{Word: WordIssue, Verb: VerbCreate, Tool: githubtools.ToolIssuesCreate},
	{Word: WordIssue, Verb: VerbComment, Tool: githubtools.ToolIssuesCreateComment},
	{Word: WordIssue, Verb: VerbEdit, Tool: githubtools.ToolIssuesUpdate},
	{Word: WordIssue, Verb: VerbClose, Tool: githubtools.ToolIssuesUpdate},
	{Word: WordIssue, Verb: VerbReopen, Tool: githubtools.ToolIssuesUpdate},
	{Word: WordIssue, Verb: VerbList, Tool: githubtools.ToolIssuesListForRepo},
	{Word: WordIssue, Verb: VerbView, Tool: githubtools.ToolIssuesGet},
}

// wordOf decodes a literal token to the gh noun it names.
func wordOf(token string) (GithubWord, bool) {
	switch GithubWord(token) {
	case WordPullRequest:
		return WordPullRequest, true
	case WordIssue:
		return WordIssue, true
	case WordAPI:
		return WordAPI, true
	default:
		return "", false
	}
}

// verbOf decodes a literal token to the gh verb it names.
func verbOf(token string) (GithubVerb, bool) {
	switch GithubVerb(token) {
	case VerbList:
		return VerbList, true
	case VerbCreate:
		return VerbCreate, true
	case VerbReady:
		return VerbReady, true
	case VerbMerge:
		return VerbMerge, true
	case VerbView:
		return VerbView, true
	case VerbChecks:
		return VerbChecks, true
	case VerbEdit:
		return VerbEdit, true
	case VerbClose:
		return VerbClose, true
	case VerbReopen:
		return VerbReopen, true
	case VerbComment:
		return VerbComment, true
	default:
		return "", false
	}
}

// replacementTool is the CSF tool that replaces the gh command "gh word verb",
// or "" when no one tool does.
func replacementTool(word GithubWord, verb GithubVerb) string {
	at := slices.IndexFunc(GithubReplacements, func(replacement GithubReplacement) bool {
		return replacement.Word == word && replacement.Verb == verb
	})
	if at < 0 {
		return ""
	}
	return GithubReplacements[at].Tool
}

// GitHubFinding is one gh command a session may not run, and the tool that
// replaces it.
type GitHubFinding struct {
	Snippet string
	// Tool is the replacing tool's name; empty when no one tool replaces
	// the command, as for gh api.
	Tool string
}

// Message is the refusal the agent reads.
func (finding GitHubFinding) Message() string {
	replacement := "the CSF GitHub tools (" + toolList + " names them; each is the MCP tool " + mcpToolPrefix + "<name>)"
	if finding.Tool != "" {
		replacement = fmt.Sprintf("the MCP tool %s%s (csf github %s from a script)", mcpToolPrefix, finding.Tool, finding.Tool)
	}
	return fmt.Sprintf("%s: %q is refused in a CSF session; GitHub is reached through CSF's typed GitHub tools, which record every call. Use %s", RuleGitHubShell, finding.Snippet, replacement)
}

// FindGitHubCommands parses command as bash and returns every gh pr, gh
// issue and gh api command in it, including inside sh -c, in source order.
func FindGitHubCommands(command string) ([]GitHubFinding, error) {
	file, err := parse(command)
	if err != nil {
		return nil, err
	}
	var findings []GitHubFinding
	syntax.Walk(file, func(node syntax.Node) bool {
		call, ok := node.(*syntax.CallExpr)
		if !ok {
			return true
		}
		name, arguments := commandWords(call)
		switch {
		case name == commandGh && len(arguments) > 0:
			word, known := wordOf(arguments[0])
			if !known {
				return true
			}
			finding := GitHubFinding{Snippet: snippetOf(command, call)}
			if len(arguments) > 1 {
				if verb, ok := verbOf(arguments[1]); ok {
					finding.Tool = replacementTool(word, verb)
				}
			}
			findings = append(findings, finding)
		case shells[name]:
			if script, ok := shellScript(arguments); ok {
				nested, _ := FindGitHubCommands(script)
				findings = append(findings, nested...)
			}
		}
		return true
	})
	return findings, nil
}

func snippetOf(source string, node syntax.Node) string {
	start, end := int(node.Pos().Offset()), int(node.End().Offset())
	if start < 0 || end > len(source) || start > end {
		return ""
	}
	return strings.TrimSpace(source[start:end])
}

// GitHubCheck is the generated PreToolUse check for the github gate: it
// refuses a Bash call whose command reaches GitHub through gh, naming the CSF
// tool that replaces each command. It is a function value, not a method, so
// the gate registers it in data.
func GitHubCheck(ctx context.Context, call *gateCall) *HookOutput {
	if call.hook.ToolName != session.ToolBash {
		return nil
	}
	findings, err := FindGitHubCommands(call.hook.ToolInput.Command)
	if err != nil || len(findings) == 0 {
		return nil
	}
	messages := make([]string, 0, len(findings))
	for _, finding := range findings {
		messages = append(messages, finding.Message())
	}
	reason := "Rejected by the CSF session gate. " + strings.Join(messages, "; ")
	call.record(ctx, GateGitHub, DecisionDeny, slog.Any(keyRules, []string{string(RuleGitHubShell)}), slog.String(keyReason, reason))
	return &HookOutput{HookSpecificOutput: &HookSpecificOutput{
		HookEventName:            session.HookPreToolUse,
		PermissionDecision:       permissionDeny,
		PermissionDecisionReason: reason,
	}}
}
