# Code generated by CandaceCodegen from csf/compiler/language/generated_block.ml; DO NOT EDIT.
"""Generator-owned Markdown block kinds counted as generated by codegen.py."""

BLOCK_KINDS = ("diagram", "north_star", "components")
