// Code generated by MockGen. DO NOT EDIT.
// Source: dispatch.go
//
// Generated by this command:
//
//	mockgen -source=dispatch.go -destination=internal/mocks/dispatch.gen.go -package=csfmocks
//

// Package csfmocks is a generated GoMock package.
package csfmocks

import (
	context "context"
	reflect "reflect"

	dispatchv1 "github.com/candacelabs/csf/proto/candace/dispatch/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockIDispatch is a mock of IDispatch interface.
type MockIDispatch struct {
	ctrl     *gomock.Controller
	recorder *MockIDispatchMockRecorder
	isgomock struct{}
}

// MockIDispatchMockRecorder is the mock recorder for MockIDispatch.
type MockIDispatchMockRecorder struct {
	mock *MockIDispatch
}

// NewMockIDispatch creates a new mock instance.
func NewMockIDispatch(ctrl *gomock.Controller) *MockIDispatch {
	mock := &MockIDispatch{ctrl: ctrl}
	mock.recorder = &MockIDispatchMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDispatch) EXPECT() *MockIDispatchMockRecorder {
	return m.recorder
}

// DeclareIntent mocks base method.
func (m *MockIDispatch) DeclareIntent(ctx context.Context, request *dispatchv1.DeclareIntentRequest) (*dispatchv1.DeclareIntentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeclareIntent", ctx, request)
	ret0, _ := ret[0].(*dispatchv1.DeclareIntentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeclareIntent indicates an expected call of DeclareIntent.
func (mr *MockIDispatchMockRecorder) DeclareIntent(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeclareIntent", reflect.TypeOf((*MockIDispatch)(nil).DeclareIntent), ctx, request)
}

// Enqueue mocks base method.
func (m *MockIDispatch) Enqueue(ctx context.Context, request *dispatchv1.EnqueueSliceRequest) (*dispatchv1.EnqueueSliceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enqueue", ctx, request)
	ret0, _ := ret[0].(*dispatchv1.EnqueueSliceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Enqueue indicates an expected call of Enqueue.
func (mr *MockIDispatchMockRecorder) Enqueue(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enqueue", reflect.TypeOf((*MockIDispatch)(nil).Enqueue), ctx, request)
}

// Frontier mocks base method.
func (m *MockIDispatch) Frontier(ctx context.Context, request *dispatchv1.GetFrontierRequest) (*dispatchv1.GetFrontierResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Frontier", ctx, request)
	ret0, _ := ret[0].(*dispatchv1.GetFrontierResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Frontier indicates an expected call of Frontier.
func (mr *MockIDispatchMockRecorder) Frontier(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Frontier", reflect.TypeOf((*MockIDispatch)(nil).Frontier), ctx, request)
}

// List mocks base method.
func (m *MockIDispatch) List(ctx context.Context, request *dispatchv1.ListSlicesRequest) (*dispatchv1.ListSlicesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, request)
	ret0, _ := ret[0].(*dispatchv1.ListSlicesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockIDispatchMockRecorder) List(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockIDispatch)(nil).List), ctx, request)
}

// MarkMerged mocks base method.
func (m *MockIDispatch) MarkMerged(ctx context.Context, request *dispatchv1.MarkSliceMergedRequest) (*dispatchv1.MarkSliceMergedResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkMerged", ctx, request)
	ret0, _ := ret[0].(*dispatchv1.MarkSliceMergedResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkMerged indicates an expected call of MarkMerged.
func (mr *MockIDispatchMockRecorder) MarkMerged(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkMerged", reflect.TypeOf((*MockIDispatch)(nil).MarkMerged), ctx, request)
}

// Reprioritize mocks base method.
func (m *MockIDispatch) Reprioritize(ctx context.Context, request *dispatchv1.ReprioritizeRequest) (*dispatchv1.ReprioritizeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reprioritize", ctx, request)
	ret0, _ := ret[0].(*dispatchv1.ReprioritizeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Reprioritize indicates an expected call of Reprioritize.
func (mr *MockIDispatchMockRecorder) Reprioritize(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reprioritize", reflect.TypeOf((*MockIDispatch)(nil).Reprioritize), ctx, request)
}

// Route mocks base method.
func (m *MockIDispatch) Route(ctx context.Context, request *dispatchv1.RouteMessageRequest) (*dispatchv1.RouteMessageResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Route", ctx, request)
	ret0, _ := ret[0].(*dispatchv1.RouteMessageResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Route indicates an expected call of Route.
func (mr *MockIDispatchMockRecorder) Route(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Route", reflect.TypeOf((*MockIDispatch)(nil).Route), ctx, request)
}
