load("@rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

go_library(
    name = "docaudit_lib",
    srcs = ["main.go"],
    importpath = "github.com/candacelabs/csf/tools/docaudit",
    visibility = ["//visibility:private"],
)

go_binary(
    name = "docaudit",
    embed = [":docaudit_lib"],
    visibility = ["//visibility:public"],
)

go_test(
    name = "docaudit_test",
    srcs = ["docaudit_test.go"],
    embed = [":docaudit_lib"],
    deps = [
        "@com_github_onsi_ginkgo_v2//:ginkgo",
        "@com_github_onsi_gomega//:gomega",
    ],
)
