load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "eventually",
    srcs = [
        "eventually.go",
        "until.go",
    ],
    importpath = "github.com/candacelabs/csf/pkg/eventually",
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_onsi_gomega//:gomega",
        "@com_github_onsi_gomega//types",
    ],
)

go_test(
    name = "eventually_test",
    srcs = [
        "eventually_suite_test.go",
        "eventually_test.go",
        "export_test.go",
        "until_test.go",
    ],
    embed = [":eventually"],
    deps = [
        "@com_github_onsi_ginkgo_v2//:ginkgo",
        "@com_github_onsi_gomega//:gomega",
    ],
)
