// Code generated by MockGen. DO NOT EDIT.
// Source: ../batch.go
//
// Generated by this command:
//
//	mockgen -source=../batch.go -destination=batch.gen.go -package=jobsmock
//

// Package jobsmock is a generated GoMock package.
package jobsmock

import (
	context "context"
	reflect "reflect"

	batch "github.com/aws/aws-sdk-go-v2/service/batch"
	cloudwatchlogs "github.com/aws/aws-sdk-go-v2/service/cloudwatchlogs"
	gomock "go.uber.org/mock/gomock"
)

// MockIBatch is a mock of IBatch interface.
type MockIBatch struct {
	ctrl     *gomock.Controller
	recorder *MockIBatchMockRecorder
	isgomock struct{}
}

// MockIBatchMockRecorder is the mock recorder for MockIBatch.
type MockIBatchMockRecorder struct {
	mock *MockIBatch
}

// NewMockIBatch creates a new mock instance.
func NewMockIBatch(ctrl *gomock.Controller) *MockIBatch {
	mock := &MockIBatch{ctrl: ctrl}
	mock.recorder = &MockIBatchMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIBatch) EXPECT() *MockIBatchMockRecorder {
	return m.recorder
}

// DescribeJobs mocks base method.
func (m *MockIBatch) DescribeJobs(ctx context.Context, input *batch.DescribeJobsInput, options ...func(*batch.Options)) (*batch.DescribeJobsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, input}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DescribeJobs", varargs...)
	ret0, _ := ret[0].(*batch.DescribeJobsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeJobs indicates an expected call of DescribeJobs.
func (mr *MockIBatchMockRecorder) DescribeJobs(ctx, input any, options ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, input}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeJobs", reflect.TypeOf((*MockIBatch)(nil).DescribeJobs), varargs...)
}

// SubmitJob mocks base method.
func (m *MockIBatch) SubmitJob(ctx context.Context, input *batch.SubmitJobInput, options ...func(*batch.Options)) (*batch.SubmitJobOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, input}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SubmitJob", varargs...)
	ret0, _ := ret[0].(*batch.SubmitJobOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubmitJob indicates an expected call of SubmitJob.
func (mr *MockIBatchMockRecorder) SubmitJob(ctx, input any, options ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, input}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitJob", reflect.TypeOf((*MockIBatch)(nil).SubmitJob), varargs...)
}

// TerminateJob mocks base method.
func (m *MockIBatch) TerminateJob(ctx context.Context, input *batch.TerminateJobInput, options ...func(*batch.Options)) (*batch.TerminateJobOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, input}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "TerminateJob", varargs...)
	ret0, _ := ret[0].(*batch.TerminateJobOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TerminateJob indicates an expected call of TerminateJob.
func (mr *MockIBatchMockRecorder) TerminateJob(ctx, input any, options ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, input}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TerminateJob", reflect.TypeOf((*MockIBatch)(nil).TerminateJob), varargs...)
}

// MockICloudWatchLogs is a mock of ICloudWatchLogs interface.
type MockICloudWatchLogs struct {
	ctrl     *gomock.Controller
	recorder *MockICloudWatchLogsMockRecorder
	isgomock struct{}
}

// MockICloudWatchLogsMockRecorder is the mock recorder for MockICloudWatchLogs.
type MockICloudWatchLogsMockRecorder struct {
	mock *MockICloudWatchLogs
}

// NewMockICloudWatchLogs creates a new mock instance.
func NewMockICloudWatchLogs(ctrl *gomock.Controller) *MockICloudWatchLogs {
	mock := &MockICloudWatchLogs{ctrl: ctrl}
	mock.recorder = &MockICloudWatchLogsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICloudWatchLogs) EXPECT() *MockICloudWatchLogsMockRecorder {
	return m.recorder
}

// GetLogEvents mocks base method.
func (m *MockICloudWatchLogs) GetLogEvents(ctx context.Context, input *cloudwatchlogs.GetLogEventsInput, options ...func(*cloudwatchlogs.Options)) (*cloudwatchlogs.GetLogEventsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, input}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetLogEvents", varargs...)
	ret0, _ := ret[0].(*cloudwatchlogs.GetLogEventsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLogEvents indicates an expected call of GetLogEvents.
func (mr *MockICloudWatchLogsMockRecorder) GetLogEvents(ctx, input any, options ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, input}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLogEvents", reflect.TypeOf((*MockICloudWatchLogs)(nil).GetLogEvents), varargs...)
}
