load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "jobsmock",
    srcs = [
        "batch.gen.go",
        "database.gen.go",
        "docker.gen.go",
        "executor.gen.go",
        "generate.go",
    ],
    importpath = "github.com/candacelabs/csf/services/jobs/jobsmock",
    visibility = ["//visibility:public"],
    deps = [
        "//ipc/db/csfpg",
        "//services/jobs",
        "@com_github_aws_aws_sdk_go_v2_service_batch//:batch",
        "@com_github_aws_aws_sdk_go_v2_service_cloudwatchlogs//:cloudwatchlogs",
        "@com_github_moby_moby_client//:client",
        "@org_uber_go_mock//gomock",
    ],
)
