load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "copilot",
    srcs = [
        "address.go",
        "copilot.go",
    ],
    importpath = "github.com/candacelabs/csf/io/net/model/copilot",
    visibility = ["//visibility:public"],
    deps = [
        "//io",
        "//io/net/model",
        "//services/copilot-adapter/gen/api",
        "@com_github_google_uuid//:uuid",
    ],
)

go_test(
    name = "copilot_test",
    srcs = [
        "copilot_suite_test.go",
        "copilot_test.go",
        "mock_workbench_client_test.go",
    ],
    deps = [
        ":copilot",
        "//io/net/model",
        "//services/copilot-adapter/gen/api",
        "@com_github_google_uuid//:uuid",
        "@com_github_onsi_ginkgo_v2//:ginkgo",
        "@com_github_onsi_gomega//:gomega",
        "@org_uber_go_mock//gomock",
    ],
)
