// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/candacelabs/csf/services/housekeeping (interfaces: IContainers,IAdmission,IProcessTable)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_housekeeping.go -package=mocks github.com/candacelabs/csf/services/housekeeping IContainers,IAdmission,IProcessTable
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	fs "io/fs"
	reflect "reflect"

	docker "github.com/candacelabs/csf/ipc/docker"
	client "github.com/moby/moby/client"
	gomock "go.uber.org/mock/gomock"
)

// MockIContainers is a mock of IContainers interface.
type MockIContainers struct {
	ctrl     *gomock.Controller
	recorder *MockIContainersMockRecorder
	isgomock struct{}
}

// MockIContainersMockRecorder is the mock recorder for MockIContainers.
type MockIContainersMockRecorder struct {
	mock *MockIContainers
}

// NewMockIContainers creates a new mock instance.
func NewMockIContainers(ctrl *gomock.Controller) *MockIContainers {
	mock := &MockIContainers{ctrl: ctrl}
	mock.recorder = &MockIContainersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIContainers) EXPECT() *MockIContainersMockRecorder {
	return m.recorder
}

// BuildCachePrune mocks base method.
func (m *MockIContainers) BuildCachePrune(ctx context.Context, options client.BuildCachePruneOptions) (client.BuildCachePruneResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildCachePrune", ctx, options)
	ret0, _ := ret[0].(client.BuildCachePruneResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuildCachePrune indicates an expected call of BuildCachePrune.
func (mr *MockIContainersMockRecorder) BuildCachePrune(ctx, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildCachePrune", reflect.TypeOf((*MockIContainers)(nil).BuildCachePrune), ctx, options)
}

// ContainerList mocks base method.
func (m *MockIContainers) ContainerList(ctx context.Context, options client.ContainerListOptions) (client.ContainerListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContainerList", ctx, options)
	ret0, _ := ret[0].(client.ContainerListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContainerList indicates an expected call of ContainerList.
func (mr *MockIContainersMockRecorder) ContainerList(ctx, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContainerList", reflect.TypeOf((*MockIContainers)(nil).ContainerList), ctx, options)
}

// ContainerRemove mocks base method.
func (m *MockIContainers) ContainerRemove(ctx context.Context, id string, options client.ContainerRemoveOptions) (client.ContainerRemoveResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContainerRemove", ctx, id, options)
	ret0, _ := ret[0].(client.ContainerRemoveResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContainerRemove indicates an expected call of ContainerRemove.
func (mr *MockIContainersMockRecorder) ContainerRemove(ctx, id, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContainerRemove", reflect.TypeOf((*MockIContainers)(nil).ContainerRemove), ctx, id, options)
}

// DiskUsage mocks base method.
func (m *MockIContainers) DiskUsage(ctx context.Context, options client.DiskUsageOptions) (client.DiskUsageResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DiskUsage", ctx, options)
	ret0, _ := ret[0].(client.DiskUsageResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DiskUsage indicates an expected call of DiskUsage.
func (mr *MockIContainersMockRecorder) DiskUsage(ctx, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DiskUsage", reflect.TypeOf((*MockIContainers)(nil).DiskUsage), ctx, options)
}

// ImageList mocks base method.
func (m *MockIContainers) ImageList(ctx context.Context, options client.ImageListOptions) (client.ImageListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImageList", ctx, options)
	ret0, _ := ret[0].(client.ImageListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ImageList indicates an expected call of ImageList.
func (mr *MockIContainersMockRecorder) ImageList(ctx, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImageList", reflect.TypeOf((*MockIContainers)(nil).ImageList), ctx, options)
}

// ImagePrune mocks base method.
func (m *MockIContainers) ImagePrune(ctx context.Context, options client.ImagePruneOptions) (client.ImagePruneResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImagePrune", ctx, options)
	ret0, _ := ret[0].(client.ImagePruneResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ImagePrune indicates an expected call of ImagePrune.
func (mr *MockIContainersMockRecorder) ImagePrune(ctx, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImagePrune", reflect.TypeOf((*MockIContainers)(nil).ImagePrune), ctx, options)
}

// RunSandboxed mocks base method.
func (m *MockIContainers) RunSandboxed(ctx context.Context, spec docker.SandboxSpec) (docker.SandboxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunSandboxed", ctx, spec)
	ret0, _ := ret[0].(docker.SandboxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunSandboxed indicates an expected call of RunSandboxed.
func (mr *MockIContainersMockRecorder) RunSandboxed(ctx, spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunSandboxed", reflect.TypeOf((*MockIContainers)(nil).RunSandboxed), ctx, spec)
}

// MockIAdmission is a mock of IAdmission interface.
type MockIAdmission struct {
	ctrl     *gomock.Controller
	recorder *MockIAdmissionMockRecorder
	isgomock struct{}
}

// MockIAdmissionMockRecorder is the mock recorder for MockIAdmission.
type MockIAdmissionMockRecorder struct {
	mock *MockIAdmission
}

// NewMockIAdmission creates a new mock instance.
func NewMockIAdmission(ctrl *gomock.Controller) *MockIAdmission {
	mock := &MockIAdmission{ctrl: ctrl}
	mock.recorder = &MockIAdmissionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAdmission) EXPECT() *MockIAdmissionMockRecorder {
	return m.recorder
}

// HoldAdmission mocks base method.
func (m *MockIAdmission) HoldAdmission(reason string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HoldAdmission", reason)
}

// HoldAdmission indicates an expected call of HoldAdmission.
func (mr *MockIAdmissionMockRecorder) HoldAdmission(reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HoldAdmission", reflect.TypeOf((*MockIAdmission)(nil).HoldAdmission), reason)
}

// ReleaseAdmission mocks base method.
func (m *MockIAdmission) ReleaseAdmission() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ReleaseAdmission")
}

// ReleaseAdmission indicates an expected call of ReleaseAdmission.
func (mr *MockIAdmissionMockRecorder) ReleaseAdmission() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseAdmission", reflect.TypeOf((*MockIAdmission)(nil).ReleaseAdmission))
}

// MockIProcessTable is a mock of IProcessTable interface.
type MockIProcessTable struct {
	ctrl     *gomock.Controller
	recorder *MockIProcessTableMockRecorder
	isgomock struct{}
}

// MockIProcessTableMockRecorder is the mock recorder for MockIProcessTable.
type MockIProcessTableMockRecorder struct {
	mock *MockIProcessTable
}

// NewMockIProcessTable creates a new mock instance.
func NewMockIProcessTable(ctrl *gomock.Controller) *MockIProcessTable {
	mock := &MockIProcessTable{ctrl: ctrl}
	mock.recorder = &MockIProcessTableMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIProcessTable) EXPECT() *MockIProcessTableMockRecorder {
	return m.recorder
}

// Open mocks base method.
func (m *MockIProcessTable) Open(name string) (fs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", name)
	ret0, _ := ret[0].(fs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockIProcessTableMockRecorder) Open(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockIProcessTable)(nil).Open), name)
}

// ReadDir mocks base method.
func (m *MockIProcessTable) ReadDir(name string) ([]fs.DirEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadDir", name)
	ret0, _ := ret[0].([]fs.DirEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadDir indicates an expected call of ReadDir.
func (mr *MockIProcessTableMockRecorder) ReadDir(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadDir", reflect.TypeOf((*MockIProcessTable)(nil).ReadDir), name)
}

// ReadFile mocks base method.
func (m *MockIProcessTable) ReadFile(name string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadFile", name)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadFile indicates an expected call of ReadFile.
func (mr *MockIProcessTableMockRecorder) ReadFile(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFile", reflect.TypeOf((*MockIProcessTable)(nil).ReadFile), name)
}

// ReadLink mocks base method.
func (m *MockIProcessTable) ReadLink(name string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadLink", name)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadLink indicates an expected call of ReadLink.
func (mr *MockIProcessTableMockRecorder) ReadLink(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadLink", reflect.TypeOf((*MockIProcessTable)(nil).ReadLink), name)
}
