// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/candacelabs/csf/pkg/gotth/live (interfaces: IIdentity)
//
// Generated by this command:
//
//	mockgen -destination=mock_identity_test.go -package=live_test github.com/candacelabs/csf/pkg/gotth/live IIdentity
//

// Package live_test is a generated GoMock package.
package live_test

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIIdentity is a mock of IIdentity interface.
type MockIIdentity struct {
	ctrl     *gomock.Controller
	recorder *MockIIdentityMockRecorder
	isgomock struct{}
}

// MockIIdentityMockRecorder is the mock recorder for MockIIdentity.
type MockIIdentityMockRecorder struct {
	mock *MockIIdentity
}

// NewMockIIdentity creates a new mock instance.
func NewMockIIdentity(ctrl *gomock.Controller) *MockIIdentity {
	mock := &MockIIdentity{ctrl: ctrl}
	mock.recorder = &MockIIdentityMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIIdentity) EXPECT() *MockIIdentityMockRecorder {
	return m.recorder
}

// Subject mocks base method.
func (m *MockIIdentity) Subject() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subject")
	ret0, _ := ret[0].(string)
	return ret0
}

// Subject indicates an expected call of Subject.
func (mr *MockIIdentityMockRecorder) Subject() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subject", reflect.TypeOf((*MockIIdentity)(nil).Subject))
}
