// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/candacelabs/csf/io/ipc/proc (interfaces: ILauncher)
//
// Generated by this command:
//
//	mockgen -destination=mock_launcher_test.go -package=await_test github.com/candacelabs/csf/io/ipc/proc ILauncher
//

// Package await_test is a generated GoMock package.
package await_test

import (
	context "context"
	reflect "reflect"

	proc "github.com/candacelabs/csf/io/ipc/proc"
	gomock "go.uber.org/mock/gomock"
)

// MockILauncher is a mock of ILauncher interface.
type MockILauncher struct {
	ctrl     *gomock.Controller
	recorder *MockILauncherMockRecorder
	isgomock struct{}
}

// MockILauncherMockRecorder is the mock recorder for MockILauncher.
type MockILauncherMockRecorder struct {
	mock *MockILauncher
}

// NewMockILauncher creates a new mock instance.
func NewMockILauncher(ctrl *gomock.Controller) *MockILauncher {
	mock := &MockILauncher{ctrl: ctrl}
	mock.recorder = &MockILauncherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockILauncher) EXPECT() *MockILauncherMockRecorder {
	return m.recorder
}

// LookPath mocks base method.
func (m *MockILauncher) LookPath(name string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LookPath", name)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LookPath indicates an expected call of LookPath.
func (mr *MockILauncherMockRecorder) LookPath(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LookPath", reflect.TypeOf((*MockILauncher)(nil).LookPath), name)
}

// Run mocks base method.
func (m *MockILauncher) Run(ctx context.Context, command proc.Command) (proc.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx, command)
	ret0, _ := ret[0].(proc.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Run indicates an expected call of Run.
func (mr *MockILauncherMockRecorder) Run(ctx, command any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockILauncher)(nil).Run), ctx, command)
}

// Start mocks base method.
func (m *MockILauncher) Start(ctx context.Context, command proc.Command) (*proc.Process, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx, command)
	ret0, _ := ret[0].(*proc.Process)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Start indicates an expected call of Start.
func (mr *MockILauncherMockRecorder) Start(ctx, command any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockILauncher)(nil).Start), ctx, command)
}
