// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/candacelabs/csf/services/ouroboros/labeler (interfaces: IContainers)
//
// Generated by this command:
//
//	mockgen -destination=mock_containers_test.go -package=labeler_test github.com/candacelabs/csf/services/ouroboros/labeler IContainers
//

// Package labeler_test is a generated GoMock package.
package labeler_test

import (
	context "context"
	reflect "reflect"

	client "github.com/moby/moby/client"
	gomock "go.uber.org/mock/gomock"
)

// MockIContainers is a mock of IContainers interface.
type MockIContainers struct {
	ctrl     *gomock.Controller
	recorder *MockIContainersMockRecorder
	isgomock struct{}
}

// MockIContainersMockRecorder is the mock recorder for MockIContainers.
type MockIContainersMockRecorder struct {
	mock *MockIContainers
}

// NewMockIContainers creates a new mock instance.
func NewMockIContainers(ctrl *gomock.Controller) *MockIContainers {
	mock := &MockIContainers{ctrl: ctrl}
	mock.recorder = &MockIContainersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIContainers) EXPECT() *MockIContainersMockRecorder {
	return m.recorder
}

// ContainerInspect mocks base method.
func (m *MockIContainers) ContainerInspect(ctx context.Context, id string, options client.ContainerInspectOptions) (client.ContainerInspectResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContainerInspect", ctx, id, options)
	ret0, _ := ret[0].(client.ContainerInspectResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContainerInspect indicates an expected call of ContainerInspect.
func (mr *MockIContainersMockRecorder) ContainerInspect(ctx, id, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContainerInspect", reflect.TypeOf((*MockIContainers)(nil).ContainerInspect), ctx, id, options)
}

// ContainerList mocks base method.
func (m *MockIContainers) ContainerList(ctx context.Context, options client.ContainerListOptions) (client.ContainerListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContainerList", ctx, options)
	ret0, _ := ret[0].(client.ContainerListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContainerList indicates an expected call of ContainerList.
func (mr *MockIContainersMockRecorder) ContainerList(ctx, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContainerList", reflect.TypeOf((*MockIContainers)(nil).ContainerList), ctx, options)
}
