load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "pretty",
    srcs = ["pretty.go"],
    importpath = "github.com/candacelabs/csf/pkg/pretty",
    visibility = ["//visibility:public"],
    deps = [
        "@org_golang_google_protobuf//proto",
        "@org_golang_google_protobuf//reflect/protoreflect",
    ],
)

go_test(
    name = "pretty_test",
    srcs = ["pretty_test.go"],
    embed = [":pretty"],
    deps = [
        "//proto/candace/harness/v1:harness",
        "@com_github_onsi_ginkgo_v2//:ginkgo",
        "@com_github_onsi_gomega//:gomega",
        "@org_golang_google_protobuf//proto",
        "@org_golang_google_protobuf//types/known/timestamppb",
    ],
)
