// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cron.sql

package csfpg

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireExpiredCronOccurrence = `-- name: AcquireExpiredCronOccurrence :one
UPDATE csf_cron_occurrences
SET attempt = attempt + 1,
    lease_owner = $1,
    lease_token = $2,
    lease_until = $3,
    started_at = $4,
    finished_at = NULL,
    error_summary = NULL,
    skip_reason = NULL,
    updated_at = $4
WHERE occurrence_id = $5
  AND status = 'running'
  AND lease_until <= $4
RETURNING occurrence_id, trigger_name, scheduled_at, status, attempt, lease_owner, lease_token, lease_until, started_at, finished_at, error_summary, skip_reason, created_at, updated_at
`

type AcquireExpiredCronOccurrenceParams struct {
	LeaseOwner   *string
	LeaseToken   *string
	LeaseUntil   pgtype.Timestamptz
	ClaimedAt    pgtype.Timestamptz
	OccurrenceID string
}

// A running occurrence whose lease expired is reclaimed as the next attempt.
func (q *Queries) AcquireExpiredCronOccurrence(ctx context.Context, arg AcquireExpiredCronOccurrenceParams) (CsfCronOccurrence, error) {
	row := q.db.QueryRow(ctx, acquireExpiredCronOccurrence,
		arg.LeaseOwner,
		arg.LeaseToken,
		arg.LeaseUntil,
		arg.ClaimedAt,
		arg.OccurrenceID,
	)
	var i CsfCronOccurrence
	err := row.Scan(
		&i.OccurrenceID,
		&i.TriggerName,
		&i.ScheduledAt,
		&i.Status,
		&i.Attempt,
		&i.LeaseOwner,
		&i.LeaseToken,
		&i.LeaseUntil,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ErrorSummary,
		&i.SkipReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const advanceCronTrigger = `-- name: AdvanceCronTrigger :execrows
UPDATE csf_cron_triggers
SET next_run_at = CASE WHEN next_run_at < $1 THEN $1 ELSE next_run_at END,
    updated_at = $2
WHERE trigger_name = $3 AND enabled
`

type AdvanceCronTriggerParams struct {
	NextRunAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	TriggerName string
}

// The cursor only moves forward.
func (q *Queries) AdvanceCronTrigger(ctx context.Context, arg AdvanceCronTriggerParams) (int64, error) {
	result, err := q.db.Exec(ctx, advanceCronTrigger, arg.NextRunAt, arg.UpdatedAt, arg.TriggerName)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const disableCronTrigger = `-- name: DisableCronTrigger :exec
UPDATE csf_cron_triggers
SET enabled = FALSE, updated_at = $1
WHERE trigger_name = $2 AND enabled
`

type DisableCronTriggerParams struct {
	UpdatedAt   pgtype.Timestamptz
	TriggerName string
}

// A trigger no longer declared keeps its history and stops firing.
func (q *Queries) DisableCronTrigger(ctx context.Context, arg DisableCronTriggerParams) error {
	_, err := q.db.Exec(ctx, disableCronTrigger, arg.UpdatedAt, arg.TriggerName)
	return err
}

const finishCronOccurrence = `-- name: FinishCronOccurrence :execrows
UPDATE csf_cron_occurrences
SET status = $1,
    lease_owner = NULL,
    lease_token = NULL,
    lease_until = NULL,
    finished_at = $2,
    error_summary = $3,
    updated_at = $2
WHERE occurrence_id = $4
  AND status = 'running'
  AND lease_token = $5
  AND lease_until > $2
`

type FinishCronOccurrenceParams struct {
	Status       string
	FinishedAt   pgtype.Timestamptz
	ErrorSummary *string
	OccurrenceID string
	LeaseToken   *string
}

func (q *Queries) FinishCronOccurrence(ctx context.Context, arg FinishCronOccurrenceParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishCronOccurrence,
		arg.Status,
		arg.FinishedAt,
		arg.ErrorSummary,
		arg.OccurrenceID,
		arg.LeaseToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCronOccurrence = `-- name: GetCronOccurrence :one
SELECT occurrence_id, trigger_name, scheduled_at, status, attempt, lease_owner, lease_token, lease_until, started_at, finished_at, error_summary, skip_reason, created_at, updated_at FROM csf_cron_occurrences WHERE occurrence_id = $1
`

func (q *Queries) GetCronOccurrence(ctx context.Context, occurrenceID string) (CsfCronOccurrence, error) {
	row := q.db.QueryRow(ctx, getCronOccurrence, occurrenceID)
	var i CsfCronOccurrence
	err := row.Scan(
		&i.OccurrenceID,
		&i.TriggerName,
		&i.ScheduledAt,
		&i.Status,
		&i.Attempt,
		&i.LeaseOwner,
		&i.LeaseToken,
		&i.LeaseUntil,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ErrorSummary,
		&i.SkipReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCronTrigger = `-- name: GetCronTrigger :one
SELECT trigger_name, schedule_kind, local_hour, local_minute, weekday, month_day, interval_nanoseconds, raw_expression, timezone, interval_anchor_at, next_run_at, catch_up_policy, overlap_policy, enabled, created_at, updated_at FROM csf_cron_triggers WHERE trigger_name = $1
`

func (q *Queries) GetCronTrigger(ctx context.Context, triggerName string) (CsfCronTrigger, error) {
	row := q.db.QueryRow(ctx, getCronTrigger, triggerName)
	var i CsfCronTrigger
	err := row.Scan(
		&i.TriggerName,
		&i.ScheduleKind,
		&i.LocalHour,
		&i.LocalMinute,
		&i.Weekday,
		&i.MonthDay,
		&i.IntervalNanoseconds,
		&i.RawExpression,
		&i.Timezone,
		&i.IntervalAnchorAt,
		&i.NextRunAt,
		&i.CatchUpPolicy,
		&i.OverlapPolicy,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRunningCronOccurrence = `-- name: InsertRunningCronOccurrence :one
INSERT INTO csf_cron_occurrences (
    occurrence_id, trigger_name, scheduled_at, status, attempt,
    lease_owner, lease_token, lease_until, started_at, created_at, updated_at
) VALUES (
    $1, $2, $3, 'running', 1,
    $4, $5, $6,
    $7, $7, $7
)
RETURNING occurrence_id, trigger_name, scheduled_at, status, attempt, lease_owner, lease_token, lease_until, started_at, finished_at, error_summary, skip_reason, created_at, updated_at
`

type InsertRunningCronOccurrenceParams struct {
	OccurrenceID string
	TriggerName  string
	ScheduledAt  pgtype.Timestamptz
	LeaseOwner   *string
	LeaseToken   *string
	LeaseUntil   pgtype.Timestamptz
	ClaimedAt    pgtype.Timestamptz
}

func (q *Queries) InsertRunningCronOccurrence(ctx context.Context, arg InsertRunningCronOccurrenceParams) (CsfCronOccurrence, error) {
	row := q.db.QueryRow(ctx, insertRunningCronOccurrence,
		arg.OccurrenceID,
		arg.TriggerName,
		arg.ScheduledAt,
		arg.LeaseOwner,
		arg.LeaseToken,
		arg.LeaseUntil,
		arg.ClaimedAt,
	)
	var i CsfCronOccurrence
	err := row.Scan(
		&i.OccurrenceID,
		&i.TriggerName,
		&i.ScheduledAt,
		&i.Status,
		&i.Attempt,
		&i.LeaseOwner,
		&i.LeaseToken,
		&i.LeaseUntil,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ErrorSummary,
		&i.SkipReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertSkippedCronOccurrence = `-- name: InsertSkippedCronOccurrence :one
INSERT INTO csf_cron_occurrences (
    occurrence_id, trigger_name, scheduled_at, status, attempt,
    finished_at, skip_reason, created_at, updated_at
) VALUES (
    $1, $2, $3, 'skipped', 0,
    $4, $5, $4, $4
)
RETURNING occurrence_id, trigger_name, scheduled_at, status, attempt, lease_owner, lease_token, lease_until, started_at, finished_at, error_summary, skip_reason, created_at, updated_at
`

type InsertSkippedCronOccurrenceParams struct {
	OccurrenceID string
	TriggerName  string
	ScheduledAt  pgtype.Timestamptz
	SkippedAt    pgtype.Timestamptz
	SkipReason   *string
}

func (q *Queries) InsertSkippedCronOccurrence(ctx context.Context, arg InsertSkippedCronOccurrenceParams) (CsfCronOccurrence, error) {
	row := q.db.QueryRow(ctx, insertSkippedCronOccurrence,
		arg.OccurrenceID,
		arg.TriggerName,
		arg.ScheduledAt,
		arg.SkippedAt,
		arg.SkipReason,
	)
	var i CsfCronOccurrence
	err := row.Scan(
		&i.OccurrenceID,
		&i.TriggerName,
		&i.ScheduledAt,
		&i.Status,
		&i.Attempt,
		&i.LeaseOwner,
		&i.LeaseToken,
		&i.LeaseUntil,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ErrorSummary,
		&i.SkipReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCronTriggers = `-- name: ListCronTriggers :many

SELECT trigger_name, schedule_kind, local_hour, local_minute, weekday, month_day, interval_nanoseconds, raw_expression, timezone, interval_anchor_at, next_run_at, catch_up_policy, overlap_policy, enabled, created_at, updated_at FROM csf_cron_triggers ORDER BY trigger_name
`

// Cron: the declared triggers and their occurrences; candace/services/cron
// owns the rules. Every write that fences on a lease is one conditional
// statement, so the store takes no row lock: a stale token or an expired
// lease changes no row, and the command tag reports it. Every time is a
// parameter the service read from its clock.
func (q *Queries) ListCronTriggers(ctx context.Context) ([]CsfCronTrigger, error) {
	rows, err := q.db.Query(ctx, listCronTriggers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CsfCronTrigger{}
	for rows.Next() {
		var i CsfCronTrigger
		if err := rows.Scan(
			&i.TriggerName,
			&i.ScheduleKind,
			&i.LocalHour,
			&i.LocalMinute,
			&i.Weekday,
			&i.MonthDay,
			&i.IntervalNanoseconds,
			&i.RawExpression,
			&i.Timezone,
			&i.IntervalAnchorAt,
			&i.NextRunAt,
			&i.CatchUpPolicy,
			&i.OverlapPolicy,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredCronOccurrences = `-- name: ListExpiredCronOccurrences :many
SELECT occurrence.occurrence_id, occurrence.trigger_name, occurrence.scheduled_at, occurrence.status, occurrence.attempt, occurrence.lease_owner, occurrence.lease_token, occurrence.lease_until, occurrence.started_at, occurrence.finished_at, occurrence.error_summary, occurrence.skip_reason, occurrence.created_at, occurrence.updated_at
FROM csf_cron_occurrences AS occurrence
JOIN csf_cron_triggers AS declaration ON declaration.trigger_name = occurrence.trigger_name
WHERE declaration.enabled
  AND occurrence.status = 'running'
  AND occurrence.lease_until <= $1
ORDER BY occurrence.lease_until, occurrence.scheduled_at, occurrence.occurrence_id
LIMIT $2
`

type ListExpiredCronOccurrencesParams struct {
	ExpiredAt pgtype.Timestamptz
	RowLimit  int32
}

// Abandoned leases of enabled triggers, oldest expiry first.
func (q *Queries) ListExpiredCronOccurrences(ctx context.Context, arg ListExpiredCronOccurrencesParams) ([]CsfCronOccurrence, error) {
	rows, err := q.db.Query(ctx, listExpiredCronOccurrences, arg.ExpiredAt, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CsfCronOccurrence{}
	for rows.Next() {
		var i CsfCronOccurrence
		if err := rows.Scan(
			&i.OccurrenceID,
			&i.TriggerName,
			&i.ScheduledAt,
			&i.Status,
			&i.Attempt,
			&i.LeaseOwner,
			&i.LeaseToken,
			&i.LeaseUntil,
			&i.StartedAt,
			&i.FinishedAt,
			&i.ErrorSummary,
			&i.SkipReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentCronOccurrences = `-- name: ListRecentCronOccurrences :many
SELECT occurrence_id, trigger_name, scheduled_at, status, attempt, lease_owner, lease_token, lease_until, started_at, finished_at, error_summary, skip_reason, created_at, updated_at FROM csf_cron_occurrences
ORDER BY scheduled_at DESC, occurrence_id DESC
LIMIT $1
`

// The newest occurrences, newest first; the caller reverses them.
func (q *Queries) ListRecentCronOccurrences(ctx context.Context, rowLimit int32) ([]CsfCronOccurrence, error) {
	rows, err := q.db.Query(ctx, listRecentCronOccurrences, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CsfCronOccurrence{}
	for rows.Next() {
		var i CsfCronOccurrence
		if err := rows.Scan(
			&i.OccurrenceID,
			&i.TriggerName,
			&i.ScheduledAt,
			&i.Status,
			&i.Attempt,
			&i.LeaseOwner,
			&i.LeaseToken,
			&i.LeaseUntil,
			&i.StartedAt,
			&i.FinishedAt,
			&i.ErrorSummary,
			&i.SkipReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const liveCronOccurrence = `-- name: LiveCronOccurrence :one
SELECT occurrence_id FROM csf_cron_occurrences
WHERE trigger_name = $1
  AND status = 'running'
  AND lease_until > $2
  AND occurrence_id <> $3
LIMIT 1
`

type LiveCronOccurrenceParams struct {
	TriggerName          string
	At                   pgtype.Timestamptz
	ExcludedOccurrenceID string
}

// Another occurrence of the same trigger holding a live lease, for the
// overlap policy.
func (q *Queries) LiveCronOccurrence(ctx context.Context, arg LiveCronOccurrenceParams) (string, error) {
	row := q.db.QueryRow(ctx, liveCronOccurrence, arg.TriggerName, arg.At, arg.ExcludedOccurrenceID)
	var occurrence_id string
	err := row.Scan(&occurrence_id)
	return occurrence_id, err
}

const renewCronOccurrenceLease = `-- name: RenewCronOccurrenceLease :execrows
UPDATE csf_cron_occurrences
SET lease_until = $1, updated_at = $2
WHERE occurrence_id = $3
  AND status = 'running'
  AND lease_token = $4
  AND lease_until > $2
`

type RenewCronOccurrenceLeaseParams struct {
	LeaseUntil   pgtype.Timestamptz
	RenewedAt    pgtype.Timestamptz
	OccurrenceID string
	LeaseToken   *string
}

func (q *Queries) RenewCronOccurrenceLease(ctx context.Context, arg RenewCronOccurrenceLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, renewCronOccurrenceLease,
		arg.LeaseUntil,
		arg.RenewedAt,
		arg.OccurrenceID,
		arg.LeaseToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const skipExpiredCronOccurrence = `-- name: SkipExpiredCronOccurrence :one
UPDATE csf_cron_occurrences
SET status = 'skipped',
    lease_owner = NULL,
    lease_token = NULL,
    lease_until = NULL,
    finished_at = $1,
    error_summary = NULL,
    skip_reason = $2,
    updated_at = $1
WHERE occurrence_id = $3
  AND status = 'running'
  AND lease_until <= $1
RETURNING occurrence_id, trigger_name, scheduled_at, status, attempt, lease_owner, lease_token, lease_until, started_at, finished_at, error_summary, skip_reason, created_at, updated_at
`

type SkipExpiredCronOccurrenceParams struct {
	SkippedAt    pgtype.Timestamptz
	SkipReason   *string
	OccurrenceID string
}

func (q *Queries) SkipExpiredCronOccurrence(ctx context.Context, arg SkipExpiredCronOccurrenceParams) (CsfCronOccurrence, error) {
	row := q.db.QueryRow(ctx, skipExpiredCronOccurrence, arg.SkippedAt, arg.SkipReason, arg.OccurrenceID)
	var i CsfCronOccurrence
	err := row.Scan(
		&i.OccurrenceID,
		&i.TriggerName,
		&i.ScheduledAt,
		&i.Status,
		&i.Attempt,
		&i.LeaseOwner,
		&i.LeaseToken,
		&i.LeaseUntil,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ErrorSummary,
		&i.SkipReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCronTrigger = `-- name: UpsertCronTrigger :one
INSERT INTO csf_cron_triggers (
    trigger_name, schedule_kind, local_hour, local_minute, weekday, month_day,
    interval_nanoseconds, raw_expression, timezone, interval_anchor_at, next_run_at,
    catch_up_policy, overlap_policy, enabled, created_at, updated_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10, $11,
    $12, $13, TRUE, $14, $14
)
ON CONFLICT (trigger_name) DO UPDATE SET
    schedule_kind = EXCLUDED.schedule_kind,
    local_hour = EXCLUDED.local_hour,
    local_minute = EXCLUDED.local_minute,
    weekday = EXCLUDED.weekday,
    month_day = EXCLUDED.month_day,
    interval_nanoseconds = EXCLUDED.interval_nanoseconds,
    raw_expression = EXCLUDED.raw_expression,
    timezone = EXCLUDED.timezone,
    interval_anchor_at = EXCLUDED.interval_anchor_at,
    next_run_at = EXCLUDED.next_run_at,
    catch_up_policy = EXCLUDED.catch_up_policy,
    overlap_policy = EXCLUDED.overlap_policy,
    enabled = TRUE,
    updated_at = EXCLUDED.updated_at
RETURNING trigger_name, schedule_kind, local_hour, local_minute, weekday, month_day, interval_nanoseconds, raw_expression, timezone, interval_anchor_at, next_run_at, catch_up_policy, overlap_policy, enabled, created_at, updated_at
`

type UpsertCronTriggerParams struct {
	TriggerName         string
	ScheduleKind        string
	LocalHour           *int16
	LocalMinute         *int16
	Weekday             *int16
	MonthDay            *int16
	IntervalNanoseconds *int64
	RawExpression       *string
	Timezone            string
	IntervalAnchorAt    pgtype.Timestamptz
	NextRunAt           pgtype.Timestamptz
	CatchUpPolicy       string
	OverlapPolicy       string
	UpdatedAt           pgtype.Timestamptz
}

// A declared trigger is inserted or brought back to its declaration, enabled.
func (q *Queries) UpsertCronTrigger(ctx context.Context, arg UpsertCronTriggerParams) (CsfCronTrigger, error) {
	row := q.db.QueryRow(ctx, upsertCronTrigger,
		arg.TriggerName,
		arg.ScheduleKind,
		arg.LocalHour,
		arg.LocalMinute,
		arg.Weekday,
		arg.MonthDay,
		arg.IntervalNanoseconds,
		arg.RawExpression,
		arg.Timezone,
		arg.IntervalAnchorAt,
		arg.NextRunAt,
		arg.CatchUpPolicy,
		arg.OverlapPolicy,
		arg.UpdatedAt,
	)
	var i CsfCronTrigger
	err := row.Scan(
		&i.TriggerName,
		&i.ScheduleKind,
		&i.LocalHour,
		&i.LocalMinute,
		&i.Weekday,
		&i.MonthDay,
		&i.IntervalNanoseconds,
		&i.RawExpression,
		&i.Timezone,
		&i.IntervalAnchorAt,
		&i.NextRunAt,
		&i.CatchUpPolicy,
		&i.OverlapPolicy,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
