// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package csfpg

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimJobSubmission = `-- name: ClaimJobSubmission :one
UPDATE csf_jobs SET state = 'submitting', updated_at = now()
WHERE job_id = (SELECT candidate.job_id FROM csf_jobs AS candidate
 WHERE candidate.state = 'pending' AND candidate.managed AND candidate.executor = $1
 AND candidate.kind = ANY($2::TEXT[])
 ORDER BY candidate.created_at, candidate.job_id FOR UPDATE SKIP LOCKED LIMIT 1)
RETURNING job_id, kind, executor, budget_account, request, request_sha256, state, total_units, completed_units, managed, executor_target, executor_image, external_id, artifact_uri, reservation_usd_micros, timeout_seconds, reason, log_stream, log_cursor, inspection_error, cancellation_requested, cleanup_confirmed, trace_url, trace_export_error, trace_retry_at, log_document_id, log_projection_error, log_indexed_at, log_retry_at, created_at, updated_at
`

type ClaimJobSubmissionParams struct {
	Executor string
	Kinds    []string
}

// Remote executors: a submission is claimed and committed before the
// executor is called, because a provider without an idempotency key cannot
// be retried blindly.
func (q *Queries) ClaimJobSubmission(ctx context.Context, arg ClaimJobSubmissionParams) (CsfJob, error) {
	row := q.db.QueryRow(ctx, claimJobSubmission, arg.Executor, arg.Kinds)
	var i CsfJob
	err := row.Scan(
		&i.JobID,
		&i.Kind,
		&i.Executor,
		&i.BudgetAccount,
		&i.Request,
		&i.RequestSha256,
		&i.State,
		&i.TotalUnits,
		&i.CompletedUnits,
		&i.Managed,
		&i.ExecutorTarget,
		&i.ExecutorImage,
		&i.ExternalID,
		&i.ArtifactUri,
		&i.ReservationUsdMicros,
		&i.TimeoutSeconds,
		&i.Reason,
		&i.LogStream,
		&i.LogCursor,
		&i.InspectionError,
		&i.CancellationRequested,
		&i.CleanupConfirmed,
		&i.TraceUrl,
		&i.TraceExportError,
		&i.TraceRetryAt,
		&i.LogDocumentID,
		&i.LogProjectionError,
		&i.LogIndexedAt,
		&i.LogRetryAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const claimJobTraceDelivery = `-- name: ClaimJobTraceDelivery :one
INSERT INTO csf_job_trace_deliveries (destination, job_id, trace_id)
VALUES ($1, $2, $3)
ON CONFLICT (destination, trace_id) DO NOTHING
RETURNING trace_id
`

type ClaimJobTraceDeliveryParams struct {
	Destination string
	JobID       string
	TraceID     string
}

func (q *Queries) ClaimJobTraceDelivery(ctx context.Context, arg ClaimJobTraceDeliveryParams) (string, error) {
	row := q.db.QueryRow(ctx, claimJobTraceDelivery, arg.Destination, arg.JobID, arg.TraceID)
	var trace_id string
	err := row.Scan(&trace_id)
	return trace_id, err
}

const countJobStates = `-- name: CountJobStates :many
SELECT kind, executor, state, count(*)::BIGINT AS jobs
FROM csf_jobs WHERE kind = ANY($1::TEXT[]) GROUP BY kind, executor, state
`

type CountJobStatesRow struct {
	Kind     string
	Executor string
	State    CsfJobState
	Jobs     int64
}

func (q *Queries) CountJobStates(ctx context.Context, kinds []string) ([]CountJobStatesRow, error) {
	rows, err := q.db.Query(ctx, countJobStates, kinds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountJobStatesRow{}
	for rows.Next() {
		var i CountJobStatesRow
		if err := rows.Scan(
			&i.Kind,
			&i.Executor,
			&i.State,
			&i.Jobs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ensureJobBudget = `-- name: EnsureJobBudget :one

INSERT INTO csf_job_budgets (account, limit_usd_micros) VALUES ($1, $2)
ON CONFLICT (account) DO UPDATE SET account = EXCLUDED.account
WHERE csf_job_budgets.limit_usd_micros = EXCLUDED.limit_usd_micros
RETURNING account, limit_usd_micros, reserved_usd_micros, created_at
`

type EnsureJobBudgetParams struct {
	Account        string
	LimitUsdMicros int64
}

// The job ledger: admitted requests to external executors. Every read that
// returns jobs is restricted to the kinds its caller decodes, so one ledger
// never hands another consumer's request to the wrong decoder.
// Budget accounts are immutable after creation: a repeated ensure with a
// different limit returns no row.
func (q *Queries) EnsureJobBudget(ctx context.Context, arg EnsureJobBudgetParams) (CsfJobBudget, error) {
	row := q.db.QueryRow(ctx, ensureJobBudget, arg.Account, arg.LimitUsdMicros)
	var i CsfJobBudget
	err := row.Scan(
		&i.Account,
		&i.LimitUsdMicros,
		&i.ReservedUsdMicros,
		&i.CreatedAt,
	)
	return i, err
}

const finishJobSubmission = `-- name: FinishJobSubmission :execrows
UPDATE csf_jobs SET state = $2, external_id = $3, reason = $4, updated_at = now()
WHERE job_id = $1 AND state IN ('submitting', 'submission_unknown')
`

type FinishJobSubmissionParams struct {
	JobID      string
	State      CsfJobState
	ExternalID string
	Reason     string
}

func (q *Queries) FinishJobSubmission(ctx context.Context, arg FinishJobSubmissionParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishJobSubmission,
		arg.JobID,
		arg.State,
		arg.ExternalID,
		arg.Reason,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishJobTraceDelivery = `-- name: FinishJobTraceDelivery :one
UPDATE csf_job_trace_deliveries
SET state = $1::csf_trace_delivery_state,
 error = $2, finished_at = now()
WHERE destination = $3 AND trace_id = $4
 AND state = 'attempted'
 AND $1::csf_trace_delivery_state IN
     ('succeeded'::csf_trace_delivery_state, 'ambiguous'::csf_trace_delivery_state)
RETURNING trace_id
`

type FinishJobTraceDeliveryParams struct {
	State       CsfTraceDeliveryState
	Error       string
	Destination string
	TraceID     string
}

func (q *Queries) FinishJobTraceDelivery(ctx context.Context, arg FinishJobTraceDeliveryParams) (string, error) {
	row := q.db.QueryRow(ctx, finishJobTraceDelivery,
		arg.State,
		arg.Error,
		arg.Destination,
		arg.TraceID,
	)
	var trace_id string
	err := row.Scan(&trace_id)
	return trace_id, err
}

const getJob = `-- name: GetJob :one
SELECT job_id, kind, executor, budget_account, request, request_sha256, state, total_units, completed_units, managed, executor_target, executor_image, external_id, artifact_uri, reservation_usd_micros, timeout_seconds, reason, log_stream, log_cursor, inspection_error, cancellation_requested, cleanup_confirmed, trace_url, trace_export_error, trace_retry_at, log_document_id, log_projection_error, log_indexed_at, log_retry_at, created_at, updated_at FROM csf_jobs WHERE job_id = $1 AND kind = ANY($2::TEXT[])
`

type GetJobParams struct {
	JobID string
	Kinds []string
}

func (q *Queries) GetJob(ctx context.Context, arg GetJobParams) (CsfJob, error) {
	row := q.db.QueryRow(ctx, getJob, arg.JobID, arg.Kinds)
	var i CsfJob
	err := row.Scan(
		&i.JobID,
		&i.Kind,
		&i.Executor,
		&i.BudgetAccount,
		&i.Request,
		&i.RequestSha256,
		&i.State,
		&i.TotalUnits,
		&i.CompletedUnits,
		&i.Managed,
		&i.ExecutorTarget,
		&i.ExecutorImage,
		&i.ExternalID,
		&i.ArtifactUri,
		&i.ReservationUsdMicros,
		&i.TimeoutSeconds,
		&i.Reason,
		&i.LogStream,
		&i.LogCursor,
		&i.InspectionError,
		&i.CancellationRequested,
		&i.CleanupConfirmed,
		&i.TraceUrl,
		&i.TraceExportError,
		&i.TraceRetryAt,
		&i.LogDocumentID,
		&i.LogProjectionError,
		&i.LogIndexedAt,
		&i.LogRetryAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJobBudget = `-- name: GetJobBudget :one
SELECT account, limit_usd_micros, reserved_usd_micros, created_at FROM csf_job_budgets WHERE account = $1
`

func (q *Queries) GetJobBudget(ctx context.Context, account string) (CsfJobBudget, error) {
	row := q.db.QueryRow(ctx, getJobBudget, account)
	var i CsfJobBudget
	err := row.Scan(
		&i.Account,
		&i.LimitUsdMicros,
		&i.ReservedUsdMicros,
		&i.CreatedAt,
	)
	return i, err
}

const getJobTraceDelivery = `-- name: GetJobTraceDelivery :one
SELECT destination, trace_id, job_id, state, error, created_at, finished_at FROM csf_job_trace_deliveries
WHERE destination = $1 AND trace_id = $2
`

type GetJobTraceDeliveryParams struct {
	Destination string
	TraceID     string
}

func (q *Queries) GetJobTraceDelivery(ctx context.Context, arg GetJobTraceDeliveryParams) (CsfJobTraceDelivery, error) {
	row := q.db.QueryRow(ctx, getJobTraceDelivery, arg.Destination, arg.TraceID)
	var i CsfJobTraceDelivery
	err := row.Scan(
		&i.Destination,
		&i.TraceID,
		&i.JobID,
		&i.State,
		&i.Error,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const insertJob = `-- name: InsertJob :one
INSERT INTO csf_jobs
 (job_id, kind, executor, budget_account, request, request_sha256, total_units, managed,
  executor_target, executor_image, artifact_uri, reservation_usd_micros, timeout_seconds)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING job_id, kind, executor, budget_account, request, request_sha256, state, total_units, completed_units, managed, executor_target, executor_image, external_id, artifact_uri, reservation_usd_micros, timeout_seconds, reason, log_stream, log_cursor, inspection_error, cancellation_requested, cleanup_confirmed, trace_url, trace_export_error, trace_retry_at, log_document_id, log_projection_error, log_indexed_at, log_retry_at, created_at, updated_at
`

type InsertJobParams struct {
	JobID                string
	Kind                 string
	Executor             string
	BudgetAccount        string
	Request              []byte
	RequestSha256        string
	TotalUnits           int64
	Managed              bool
	ExecutorTarget       string
	ExecutorImage        string
	ArtifactUri          string
	ReservationUsdMicros int64
	TimeoutSeconds       int32
}

func (q *Queries) InsertJob(ctx context.Context, arg InsertJobParams) (CsfJob, error) {
	row := q.db.QueryRow(ctx, insertJob,
		arg.JobID,
		arg.Kind,
		arg.Executor,
		arg.BudgetAccount,
		arg.Request,
		arg.RequestSha256,
		arg.TotalUnits,
		arg.Managed,
		arg.ExecutorTarget,
		arg.ExecutorImage,
		arg.ArtifactUri,
		arg.ReservationUsdMicros,
		arg.TimeoutSeconds,
	)
	var i CsfJob
	err := row.Scan(
		&i.JobID,
		&i.Kind,
		&i.Executor,
		&i.BudgetAccount,
		&i.Request,
		&i.RequestSha256,
		&i.State,
		&i.TotalUnits,
		&i.CompletedUnits,
		&i.Managed,
		&i.ExecutorTarget,
		&i.ExecutorImage,
		&i.ExternalID,
		&i.ArtifactUri,
		&i.ReservationUsdMicros,
		&i.TimeoutSeconds,
		&i.Reason,
		&i.LogStream,
		&i.LogCursor,
		&i.InspectionError,
		&i.CancellationRequested,
		&i.CleanupConfirmed,
		&i.TraceUrl,
		&i.TraceExportError,
		&i.TraceRetryAt,
		&i.LogDocumentID,
		&i.LogProjectionError,
		&i.LogIndexedAt,
		&i.LogRetryAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertJobMeasurement = `-- name: InsertJobMeasurement :execrows
INSERT INTO csf_job_measurements (job_id, metric, step, value, recorded_at, evidence_hash) VALUES ($1,$2,$3,$4,$5,$6)
ON CONFLICT (job_id, metric, step) DO UPDATE SET metric = EXCLUDED.metric
WHERE csf_job_measurements.value = EXCLUDED.value
`

type InsertJobMeasurementParams struct {
	JobID        string
	Metric       string
	Step         int64
	Value        float64
	RecordedAt   pgtype.Timestamptz
	EvidenceHash string
}

// A replayed identical value counts one row; a conflicting one counts none.
func (q *Queries) InsertJobMeasurement(ctx context.Context, arg InsertJobMeasurementParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertJobMeasurement,
		arg.JobID,
		arg.Metric,
		arg.Step,
		arg.Value,
		arg.RecordedAt,
		arg.EvidenceHash,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertJobMetricDefinition = `-- name: InsertJobMetricDefinition :execrows
INSERT INTO csf_job_metric_definitions (job_id, name, unit, description) VALUES ($1,$2,$3,$4)
ON CONFLICT (job_id, name) DO UPDATE SET name = EXCLUDED.name
WHERE csf_job_metric_definitions.unit = EXCLUDED.unit
AND csf_job_metric_definitions.description = EXCLUDED.description
`

type InsertJobMetricDefinitionParams struct {
	JobID       string
	Name        string
	Unit        string
	Description string
}

// A replayed identical definition counts one row; a changed one counts none.
func (q *Queries) InsertJobMetricDefinition(ctx context.Context, arg InsertJobMetricDefinitionParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertJobMetricDefinition,
		arg.JobID,
		arg.Name,
		arg.Unit,
		arg.Description,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const latestJobMeasurements = `-- name: LatestJobMeasurements :many
SELECT DISTINCT ON (metric) job_id, metric, step, value, recorded_at, evidence_hash FROM csf_job_measurements
WHERE job_id = $1 ORDER BY metric, step DESC
`

func (q *Queries) LatestJobMeasurements(ctx context.Context, jobID string) ([]CsfJobMeasurement, error) {
	rows, err := q.db.Query(ctx, latestJobMeasurements, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CsfJobMeasurement{}
	for rows.Next() {
		var i CsfJobMeasurement
		if err := rows.Scan(
			&i.JobID,
			&i.Metric,
			&i.Step,
			&i.Value,
			&i.RecordedAt,
			&i.EvidenceHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const latestJobProgress = `-- name: LatestJobProgress :many
SELECT DISTINCT ON (kind, executor) kind, executor, total_units, completed_units, updated_at
FROM csf_jobs WHERE kind = ANY($1::TEXT[])
ORDER BY kind, executor, created_at DESC, job_id
`

type LatestJobProgressRow struct {
	Kind           string
	Executor       string
	TotalUnits     int64
	CompletedUnits int64
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) LatestJobProgress(ctx context.Context, kinds []string) ([]LatestJobProgressRow, error) {
	rows, err := q.db.Query(ctx, latestJobProgress, kinds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LatestJobProgressRow{}
	for rows.Next() {
		var i LatestJobProgressRow
		if err := rows.Scan(
			&i.Kind,
			&i.Executor,
			&i.TotalUnits,
			&i.CompletedUnits,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobMetricDefinitions = `-- name: ListJobMetricDefinitions :many
SELECT job_id, name, unit, description FROM csf_job_metric_definitions WHERE job_id = $1 ORDER BY name
`

func (q *Queries) ListJobMetricDefinitions(ctx context.Context, jobID string) ([]CsfJobMetricDefinition, error) {
	rows, err := q.db.Query(ctx, listJobMetricDefinitions, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CsfJobMetricDefinition{}
	for rows.Next() {
		var i CsfJobMetricDefinition
		if err := rows.Scan(
			&i.JobID,
			&i.Name,
			&i.Unit,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobs = `-- name: ListJobs :many
SELECT job_id, kind, executor, budget_account, request, request_sha256, state, total_units, completed_units, managed, executor_target, executor_image, external_id, artifact_uri, reservation_usd_micros, timeout_seconds, reason, log_stream, log_cursor, inspection_error, cancellation_requested, cleanup_confirmed, trace_url, trace_export_error, trace_retry_at, log_document_id, log_projection_error, log_indexed_at, log_retry_at, created_at, updated_at FROM csf_jobs WHERE kind = ANY($1::TEXT[])
ORDER BY created_at DESC, job_id LIMIT $2
`

type ListJobsParams struct {
	Kinds    []string
	RowLimit int32
}

func (q *Queries) ListJobs(ctx context.Context, arg ListJobsParams) ([]CsfJob, error) {
	rows, err := q.db.Query(ctx, listJobs, arg.Kinds, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CsfJob{}
	for rows.Next() {
		var i CsfJob
		if err := rows.Scan(
			&i.JobID,
			&i.Kind,
			&i.Executor,
			&i.BudgetAccount,
			&i.Request,
			&i.RequestSha256,
			&i.State,
			&i.TotalUnits,
			&i.CompletedUnits,
			&i.Managed,
			&i.ExecutorTarget,
			&i.ExecutorImage,
			&i.ExternalID,
			&i.ArtifactUri,
			&i.ReservationUsdMicros,
			&i.TimeoutSeconds,
			&i.Reason,
			&i.LogStream,
			&i.LogCursor,
			&i.InspectionError,
			&i.CancellationRequested,
			&i.CleanupConfirmed,
			&i.TraceUrl,
			&i.TraceExportError,
			&i.TraceRetryAt,
			&i.LogDocumentID,
			&i.LogProjectionError,
			&i.LogIndexedAt,
			&i.LogRetryAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockJob = `-- name: LockJob :one
SELECT job_id, kind, executor, budget_account, request, request_sha256, state, total_units, completed_units, managed, executor_target, executor_image, external_id, artifact_uri, reservation_usd_micros, timeout_seconds, reason, log_stream, log_cursor, inspection_error, cancellation_requested, cleanup_confirmed, trace_url, trace_export_error, trace_retry_at, log_document_id, log_projection_error, log_indexed_at, log_retry_at, created_at, updated_at FROM csf_jobs WHERE job_id = $1 AND kind = ANY($2::TEXT[]) FOR UPDATE
`

type LockJobParams struct {
	JobID string
	Kinds []string
}

func (q *Queries) LockJob(ctx context.Context, arg LockJobParams) (CsfJob, error) {
	row := q.db.QueryRow(ctx, lockJob, arg.JobID, arg.Kinds)
	var i CsfJob
	err := row.Scan(
		&i.JobID,
		&i.Kind,
		&i.Executor,
		&i.BudgetAccount,
		&i.Request,
		&i.RequestSha256,
		&i.State,
		&i.TotalUnits,
		&i.CompletedUnits,
		&i.Managed,
		&i.ExecutorTarget,
		&i.ExecutorImage,
		&i.ExternalID,
		&i.ArtifactUri,
		&i.ReservationUsdMicros,
		&i.TimeoutSeconds,
		&i.Reason,
		&i.LogStream,
		&i.LogCursor,
		&i.InspectionError,
		&i.CancellationRequested,
		&i.CleanupConfirmed,
		&i.TraceUrl,
		&i.TraceExportError,
		&i.TraceRetryAt,
		&i.LogDocumentID,
		&i.LogProjectionError,
		&i.LogIndexedAt,
		&i.LogRetryAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockJobBudget = `-- name: LockJobBudget :one
SELECT account, limit_usd_micros, reserved_usd_micros, created_at FROM csf_job_budgets WHERE account = $1 FOR UPDATE
`

// The first statement of every admission transaction: it serializes
// admissions against one account, including concurrent retries.
func (q *Queries) LockJobBudget(ctx context.Context, account string) (CsfJobBudget, error) {
	row := q.db.QueryRow(ctx, lockJobBudget, account)
	var i CsfJobBudget
	err := row.Scan(
		&i.Account,
		&i.LimitUsdMicros,
		&i.ReservedUsdMicros,
		&i.CreatedAt,
	)
	return i, err
}

const lockJobExecutor = `-- name: LockJobExecutor :one
SELECT pg_try_advisory_xact_lock(67545231, hashtext($1::TEXT)) AS acquired
`

// Host executors: one transaction-scoped lock per executor serializes host
// reconciliation, even across overlapping deploys.
func (q *Queries) LockJobExecutor(ctx context.Context, executor string) (bool, error) {
	row := q.db.QueryRow(ctx, lockJobExecutor, executor)
	var acquired bool
	err := row.Scan(&acquired)
	return acquired, err
}

const markInterruptedJobSubmissions = `-- name: MarkInterruptedJobSubmissions :exec
UPDATE csf_jobs SET state = 'submission_unknown', reason = $1, updated_at = now()
WHERE state = 'submitting' AND executor = $2
AND updated_at < now() - make_interval(secs => $3::INTEGER)
`

type MarkInterruptedJobSubmissionsParams struct {
	Reason       string
	Executor     string
	GraceSeconds int32
}

func (q *Queries) MarkInterruptedJobSubmissions(ctx context.Context, arg MarkInterruptedJobSubmissionsParams) error {
	_, err := q.db.Exec(ctx, markInterruptedJobSubmissions, arg.Reason, arg.Executor, arg.GraceSeconds)
	return err
}

const nextHostJob = `-- name: NextHostJob :one
SELECT job_id, kind, executor, budget_account, request, request_sha256, state, total_units, completed_units, managed, executor_target, executor_image, external_id, artifact_uri, reservation_usd_micros, timeout_seconds, reason, log_stream, log_cursor, inspection_error, cancellation_requested, cleanup_confirmed, trace_url, trace_export_error, trace_retry_at, log_document_id, log_projection_error, log_indexed_at, log_retry_at, created_at, updated_at FROM csf_jobs
WHERE executor = $1 AND managed AND NOT cleanup_confirmed
AND kind = ANY($2::TEXT[])
ORDER BY (state = 'pending'), created_at, job_id LIMIT 1 FOR UPDATE
`

type NextHostJobParams struct {
	Executor string
	Kinds    []string
}

func (q *Queries) NextHostJob(ctx context.Context, arg NextHostJobParams) (CsfJob, error) {
	row := q.db.QueryRow(ctx, nextHostJob, arg.Executor, arg.Kinds)
	var i CsfJob
	err := row.Scan(
		&i.JobID,
		&i.Kind,
		&i.Executor,
		&i.BudgetAccount,
		&i.Request,
		&i.RequestSha256,
		&i.State,
		&i.TotalUnits,
		&i.CompletedUnits,
		&i.Managed,
		&i.ExecutorTarget,
		&i.ExecutorImage,
		&i.ExternalID,
		&i.ArtifactUri,
		&i.ReservationUsdMicros,
		&i.TimeoutSeconds,
		&i.Reason,
		&i.LogStream,
		&i.LogCursor,
		&i.InspectionError,
		&i.CancellationRequested,
		&i.CleanupConfirmed,
		&i.TraceUrl,
		&i.TraceExportError,
		&i.TraceRetryAt,
		&i.LogDocumentID,
		&i.LogProjectionError,
		&i.LogIndexedAt,
		&i.LogRetryAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const nextUnarchivedJob = `-- name: NextUnarchivedJob :one
SELECT job_id, kind, executor, budget_account, request, request_sha256, state, total_units, completed_units, managed, executor_target, executor_image, external_id, artifact_uri, reservation_usd_micros, timeout_seconds, reason, log_stream, log_cursor, inspection_error, cancellation_requested, cleanup_confirmed, trace_url, trace_export_error, trace_retry_at, log_document_id, log_projection_error, log_indexed_at, log_retry_at, created_at, updated_at FROM csf_jobs WHERE executor = $1
 AND kind = ANY($2::TEXT[])
 AND state IN ('succeeded', 'failed', 'cancelled')
 AND cleanup_confirmed
 AND log_document_id = '' AND log_retry_at <= now()
ORDER BY created_at DESC LIMIT 1
`

type NextUnarchivedJobParams struct {
	Executor string
	Kinds    []string
}

func (q *Queries) NextUnarchivedJob(ctx context.Context, arg NextUnarchivedJobParams) (CsfJob, error) {
	row := q.db.QueryRow(ctx, nextUnarchivedJob, arg.Executor, arg.Kinds)
	var i CsfJob
	err := row.Scan(
		&i.JobID,
		&i.Kind,
		&i.Executor,
		&i.BudgetAccount,
		&i.Request,
		&i.RequestSha256,
		&i.State,
		&i.TotalUnits,
		&i.CompletedUnits,
		&i.Managed,
		&i.ExecutorTarget,
		&i.ExecutorImage,
		&i.ExternalID,
		&i.ArtifactUri,
		&i.ReservationUsdMicros,
		&i.TimeoutSeconds,
		&i.Reason,
		&i.LogStream,
		&i.LogCursor,
		&i.InspectionError,
		&i.CancellationRequested,
		&i.CleanupConfirmed,
		&i.TraceUrl,
		&i.TraceExportError,
		&i.TraceRetryAt,
		&i.LogDocumentID,
		&i.LogProjectionError,
		&i.LogIndexedAt,
		&i.LogRetryAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const nextUntracedJob = `-- name: NextUntracedJob :one
SELECT job_id, kind, executor, budget_account, request, request_sha256, state, total_units, completed_units, managed, executor_target, executor_image, external_id, artifact_uri, reservation_usd_micros, timeout_seconds, reason, log_stream, log_cursor, inspection_error, cancellation_requested, cleanup_confirmed, trace_url, trace_export_error, trace_retry_at, log_document_id, log_projection_error, log_indexed_at, log_retry_at, created_at, updated_at FROM csf_jobs WHERE executor = $1
 AND kind = ANY($2::TEXT[])
 AND state IN ('succeeded', 'failed', 'cancelled')
 AND (NOT managed OR cleanup_confirmed)
 AND trace_url = '' AND trace_retry_at <= now()
ORDER BY created_at DESC LIMIT 1
`

type NextUntracedJobParams struct {
	Executor string
	Kinds    []string
}

func (q *Queries) NextUntracedJob(ctx context.Context, arg NextUntracedJobParams) (CsfJob, error) {
	row := q.db.QueryRow(ctx, nextUntracedJob, arg.Executor, arg.Kinds)
	var i CsfJob
	err := row.Scan(
		&i.JobID,
		&i.Kind,
		&i.Executor,
		&i.BudgetAccount,
		&i.Request,
		&i.RequestSha256,
		&i.State,
		&i.TotalUnits,
		&i.CompletedUnits,
		&i.Managed,
		&i.ExecutorTarget,
		&i.ExecutorImage,
		&i.ExternalID,
		&i.ArtifactUri,
		&i.ReservationUsdMicros,
		&i.TimeoutSeconds,
		&i.Reason,
		&i.LogStream,
		&i.LogCursor,
		&i.InspectionError,
		&i.CancellationRequested,
		&i.CleanupConfirmed,
		&i.TraceUrl,
		&i.TraceExportError,
		&i.TraceRetryAt,
		&i.LogDocumentID,
		&i.LogProjectionError,
		&i.LogIndexedAt,
		&i.LogRetryAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const pollableJobs = `-- name: PollableJobs :many
SELECT job_id, kind, executor, budget_account, request, request_sha256, state, total_units, completed_units, managed, executor_target, executor_image, external_id, artifact_uri, reservation_usd_micros, timeout_seconds, reason, log_stream, log_cursor, inspection_error, cancellation_requested, cleanup_confirmed, trace_url, trace_export_error, trace_retry_at, log_document_id, log_projection_error, log_indexed_at, log_retry_at, created_at, updated_at FROM csf_jobs WHERE executor = $1 AND external_id <> ''
AND kind = ANY($2::TEXT[])
AND (state IN ('queued', 'running', 'cancelling')
 OR (state IN ('succeeded', 'failed', 'cancelled') AND updated_at > now() - interval '10 minutes'))
ORDER BY updated_at, job_id LIMIT $3
`

type PollableJobsParams struct {
	Executor string
	Kinds    []string
	RowLimit int32
}

// Terminal jobs stay pollable briefly so trailing log pages are drained.
func (q *Queries) PollableJobs(ctx context.Context, arg PollableJobsParams) ([]CsfJob, error) {
	rows, err := q.db.Query(ctx, pollableJobs, arg.Executor, arg.Kinds, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CsfJob{}
	for rows.Next() {
		var i CsfJob
		if err := rows.Scan(
			&i.JobID,
			&i.Kind,
			&i.Executor,
			&i.BudgetAccount,
			&i.Request,
			&i.RequestSha256,
			&i.State,
			&i.TotalUnits,
			&i.CompletedUnits,
			&i.Managed,
			&i.ExecutorTarget,
			&i.ExecutorImage,
			&i.ExternalID,
			&i.ArtifactUri,
			&i.ReservationUsdMicros,
			&i.TimeoutSeconds,
			&i.Reason,
			&i.LogStream,
			&i.LogCursor,
			&i.InspectionError,
			&i.CancellationRequested,
			&i.CleanupConfirmed,
			&i.TraceUrl,
			&i.TraceExportError,
			&i.TraceRetryAt,
			&i.LogDocumentID,
			&i.LogProjectionError,
			&i.LogIndexedAt,
			&i.LogRetryAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordJobProgress = `-- name: RecordJobProgress :exec
UPDATE csf_jobs SET completed_units = GREATEST(completed_units, $1::BIGINT),
 state = $2, reason = $3, updated_at = now()
WHERE job_id = $4
`

type RecordJobProgressParams struct {
	CompletedUnits int64
	State          CsfJobState
	Reason         string
	JobID          string
}

func (q *Queries) RecordJobProgress(ctx context.Context, arg RecordJobProgressParams) error {
	_, err := q.db.Exec(ctx, recordJobProgress,
		arg.CompletedUnits,
		arg.State,
		arg.Reason,
		arg.JobID,
	)
	return err
}

const requestJobCancellation = `-- name: RequestJobCancellation :one
UPDATE csf_jobs SET cancellation_requested = true,
 state = CASE WHEN state = 'pending' THEN 'cancelled'::csf_job_state ELSE state END,
 cleanup_confirmed = CASE WHEN state = 'pending' AND managed THEN true ELSE cleanup_confirmed END,
 updated_at = now()
WHERE job_id = $1 AND kind = ANY($2::TEXT[]) RETURNING job_id, kind, executor, budget_account, request, request_sha256, state, total_units, completed_units, managed, executor_target, executor_image, external_id, artifact_uri, reservation_usd_micros, timeout_seconds, reason, log_stream, log_cursor, inspection_error, cancellation_requested, cleanup_confirmed, trace_url, trace_export_error, trace_retry_at, log_document_id, log_projection_error, log_indexed_at, log_retry_at, created_at, updated_at
`

type RequestJobCancellationParams struct {
	JobID string
	Kinds []string
}

func (q *Queries) RequestJobCancellation(ctx context.Context, arg RequestJobCancellationParams) (CsfJob, error) {
	row := q.db.QueryRow(ctx, requestJobCancellation, arg.JobID, arg.Kinds)
	var i CsfJob
	err := row.Scan(
		&i.JobID,
		&i.Kind,
		&i.Executor,
		&i.BudgetAccount,
		&i.Request,
		&i.RequestSha256,
		&i.State,
		&i.TotalUnits,
		&i.CompletedUnits,
		&i.Managed,
		&i.ExecutorTarget,
		&i.ExecutorImage,
		&i.ExternalID,
		&i.ArtifactUri,
		&i.ReservationUsdMicros,
		&i.TimeoutSeconds,
		&i.Reason,
		&i.LogStream,
		&i.LogCursor,
		&i.InspectionError,
		&i.CancellationRequested,
		&i.CleanupConfirmed,
		&i.TraceUrl,
		&i.TraceExportError,
		&i.TraceRetryAt,
		&i.LogDocumentID,
		&i.LogProjectionError,
		&i.LogIndexedAt,
		&i.LogRetryAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const reserveJobBudget = `-- name: ReserveJobBudget :execrows
UPDATE csf_job_budgets SET reserved_usd_micros = reserved_usd_micros + $1::BIGINT
WHERE account = $2
AND limit_usd_micros - reserved_usd_micros >= $1::BIGINT
`

type ReserveJobBudgetParams struct {
	Amount  int64
	Account string
}

func (q *Queries) ReserveJobBudget(ctx context.Context, arg ReserveJobBudgetParams) (int64, error) {
	result, err := q.db.Exec(ctx, reserveJobBudget, arg.Amount, arg.Account)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setJobInspectionError = `-- name: SetJobInspectionError :exec
UPDATE csf_jobs SET inspection_error = $2 WHERE job_id = $1
`

type SetJobInspectionErrorParams struct {
	JobID           string
	InspectionError string
}

func (q *Queries) SetJobInspectionError(ctx context.Context, arg SetJobInspectionErrorParams) error {
	_, err := q.db.Exec(ctx, setJobInspectionError, arg.JobID, arg.InspectionError)
	return err
}

const setJobLogArchive = `-- name: SetJobLogArchive :exec
UPDATE csf_jobs SET log_document_id = $2,
 log_projection_error = $3, log_indexed_at = $4,
 log_retry_at = now() + interval '1 minute' WHERE job_id = $1
`

type SetJobLogArchiveParams struct {
	JobID              string
	LogDocumentID      string
	LogProjectionError string
	LogIndexedAt       pgtype.Timestamptz
}

func (q *Queries) SetJobLogArchive(ctx context.Context, arg SetJobLogArchiveParams) error {
	_, err := q.db.Exec(ctx, setJobLogArchive,
		arg.JobID,
		arg.LogDocumentID,
		arg.LogProjectionError,
		arg.LogIndexedAt,
	)
	return err
}

const setJobLogCursor = `-- name: SetJobLogCursor :exec
UPDATE csf_jobs SET log_cursor = $2 WHERE job_id = $1
`

type SetJobLogCursorParams struct {
	JobID     string
	LogCursor string
}

func (q *Queries) SetJobLogCursor(ctx context.Context, arg SetJobLogCursorParams) error {
	_, err := q.db.Exec(ctx, setJobLogCursor, arg.JobID, arg.LogCursor)
	return err
}

const setJobTrace = `-- name: SetJobTrace :exec
UPDATE csf_jobs SET trace_url = $2, trace_export_error = $3,
 trace_retry_at = now() + interval '1 minute' WHERE job_id = $1
`

type SetJobTraceParams struct {
	JobID            string
	TraceUrl         string
	TraceExportError string
}

func (q *Queries) SetJobTrace(ctx context.Context, arg SetJobTraceParams) error {
	_, err := q.db.Exec(ctx, setJobTrace, arg.JobID, arg.TraceUrl, arg.TraceExportError)
	return err
}

const updateJobExecution = `-- name: UpdateJobExecution :exec
UPDATE csf_jobs SET state = $2, external_id = $3, reason = $4, log_stream = $5,
 cleanup_confirmed = $6, inspection_error = '',
 updated_at = CASE WHEN state <> $2 THEN now() ELSE updated_at END
WHERE job_id = $1
`

type UpdateJobExecutionParams struct {
	JobID            string
	State            CsfJobState
	ExternalID       string
	Reason           string
	LogStream        string
	CleanupConfirmed bool
}

// The update time moves only when the state does.
func (q *Queries) UpdateJobExecution(ctx context.Context, arg UpdateJobExecutionParams) error {
	_, err := q.db.Exec(ctx, updateJobExecution,
		arg.JobID,
		arg.State,
		arg.ExternalID,
		arg.Reason,
		arg.LogStream,
		arg.CleanupConfirmed,
	)
	return err
}
