// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package csfpg

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type CsfJobState string

const (
	CsfJobStatePending           CsfJobState = "pending"
	CsfJobStateSubmitting        CsfJobState = "submitting"
	CsfJobStateQueued            CsfJobState = "queued"
	CsfJobStateRunning           CsfJobState = "running"
	CsfJobStateSucceeded         CsfJobState = "succeeded"
	CsfJobStateFailed            CsfJobState = "failed"
	CsfJobStateCancelling        CsfJobState = "cancelling"
	CsfJobStateCancelled         CsfJobState = "cancelled"
	CsfJobStateSubmissionUnknown CsfJobState = "submission_unknown"
)

func (e *CsfJobState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CsfJobState(s)
	case string:
		*e = CsfJobState(s)
	default:
		return fmt.Errorf("unsupported scan type for CsfJobState: %T", src)
	}
	return nil
}

type NullCsfJobState struct {
	CsfJobState CsfJobState
	Valid       bool // Valid is true if CsfJobState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCsfJobState) Scan(value interface{}) error {
	if value == nil {
		ns.CsfJobState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CsfJobState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCsfJobState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CsfJobState), nil
}

type CsfProjectionStatus string

const (
	CsfProjectionStatusPending   CsfProjectionStatus = "pending"
	CsfProjectionStatusRunning   CsfProjectionStatus = "running"
	CsfProjectionStatusSucceeded CsfProjectionStatus = "succeeded"
	CsfProjectionStatusFailed    CsfProjectionStatus = "failed"
)

func (e *CsfProjectionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CsfProjectionStatus(s)
	case string:
		*e = CsfProjectionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CsfProjectionStatus: %T", src)
	}
	return nil
}

type NullCsfProjectionStatus struct {
	CsfProjectionStatus CsfProjectionStatus
	Valid               bool // Valid is true if CsfProjectionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCsfProjectionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CsfProjectionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CsfProjectionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCsfProjectionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CsfProjectionStatus), nil
}

type CsfSliceState string

const (
	CsfSliceStateQueued    CsfSliceState = "queued"
	CsfSliceStateRunning   CsfSliceState = "running"
	CsfSliceStatePreempted CsfSliceState = "preempted"
	CsfSliceStateMerged    CsfSliceState = "merged"
	CsfSliceStateFailed    CsfSliceState = "failed"
	CsfSliceStateCanceled  CsfSliceState = "canceled"
)

func (e *CsfSliceState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CsfSliceState(s)
	case string:
		*e = CsfSliceState(s)
	default:
		return fmt.Errorf("unsupported scan type for CsfSliceState: %T", src)
	}
	return nil
}

type NullCsfSliceState struct {
	CsfSliceState CsfSliceState
	Valid         bool // Valid is true if CsfSliceState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCsfSliceState) Scan(value interface{}) error {
	if value == nil {
		ns.CsfSliceState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CsfSliceState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCsfSliceState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CsfSliceState), nil
}

type CsfTraceDeliveryState string

const (
	CsfTraceDeliveryStateAttempted CsfTraceDeliveryState = "attempted"
	CsfTraceDeliveryStateSucceeded CsfTraceDeliveryState = "succeeded"
	CsfTraceDeliveryStateAmbiguous CsfTraceDeliveryState = "ambiguous"
)

func (e *CsfTraceDeliveryState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CsfTraceDeliveryState(s)
	case string:
		*e = CsfTraceDeliveryState(s)
	default:
		return fmt.Errorf("unsupported scan type for CsfTraceDeliveryState: %T", src)
	}
	return nil
}

type NullCsfTraceDeliveryState struct {
	CsfTraceDeliveryState CsfTraceDeliveryState
	Valid                 bool // Valid is true if CsfTraceDeliveryState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCsfTraceDeliveryState) Scan(value interface{}) error {
	if value == nil {
		ns.CsfTraceDeliveryState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CsfTraceDeliveryState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCsfTraceDeliveryState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CsfTraceDeliveryState), nil
}

type CsfAgentConfiguration struct {
	AgentID                        string
	Revision                       int64
	LangfuseEndpointUrl            string
	LangfusePublicKeySecretRef     string
	LangfuseSecretKeySecretRef     string
	OpensearchEndpointUrl          string
	OpensearchIndex                string
	OpensearchEmbeddingModel       string
	OpensearchCredentialsSecretRef string
	UpdatedAt                      pgtype.Timestamptz
}

type CsfCronOccurrence struct {
	OccurrenceID string
	TriggerName  string
	ScheduledAt  pgtype.Timestamptz
	Status       string
	Attempt      int32
	LeaseOwner   *string
	LeaseToken   *string
	LeaseUntil   pgtype.Timestamptz
	StartedAt    pgtype.Timestamptz
	FinishedAt   pgtype.Timestamptz
	ErrorSummary *string
	SkipReason   *string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type CsfCronTrigger struct {
	TriggerName         string
	ScheduleKind        string
	LocalHour           *int16
	LocalMinute         *int16
	Weekday             *int16
	MonthDay            *int16
	IntervalNanoseconds *int64
	RawExpression       *string
	Timezone            string
	IntervalAnchorAt    pgtype.Timestamptz
	NextRunAt           pgtype.Timestamptz
	CatchUpPolicy       string
	OverlapPolicy       string
	Enabled             bool
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

type CsfDispatchControl struct {
	Sequence   int64
	Action     string
	SliceID    *string
	Reason     string
	RecordedAt pgtype.Timestamptz
}

type CsfDocument struct {
	ContentHash string
	ByteSize    int64
	ArtifactRef string
	CreatedAt   pgtype.Timestamptz
}

type CsfEdge struct {
	FromNodeID string
	ToNodeID   string
	Relation   string
	AuthorKind string
	AuthorRef  string
	Rationale  string
	CreatedAt  pgtype.Timestamptz
}

type CsfEvalReplay struct {
	Build         string
	SuiteVersion  int32
	Ticket        int64
	Node          string
	AssignmentID  string
	ToolCalls     int64
	Episodes      int64
	Recall        float64
	CostUsdMicros int64
	Seconds       int64
	RecordedAt    pgtype.Timestamptz
}

type CsfEvalScore struct {
	Build        string
	SuiteVersion int32
	StartedAt    pgtype.Timestamptz
	FinishedAt   pgtype.Timestamptz
}

type CsfEvalSuite struct {
	Version    int32
	SelectedAt pgtype.Timestamptz
	Suite      []byte
}

type CsfIntent struct {
	IntentID  string
	SliceID   *string
	Intent    []byte
	CreatedAt pgtype.Timestamptz
}

type CsfJob struct {
	JobID                 string
	Kind                  string
	Executor              string
	BudgetAccount         string
	Request               []byte
	RequestSha256         string
	State                 CsfJobState
	TotalUnits            int64
	CompletedUnits        int64
	Managed               bool
	ExecutorTarget        string
	ExecutorImage         string
	ExternalID            string
	ArtifactUri           string
	ReservationUsdMicros  int64
	TimeoutSeconds        int32
	Reason                string
	LogStream             string
	LogCursor             string
	InspectionError       string
	CancellationRequested bool
	CleanupConfirmed      bool
	TraceUrl              string
	TraceExportError      string
	TraceRetryAt          pgtype.Timestamptz
	LogDocumentID         string
	LogProjectionError    string
	LogIndexedAt          pgtype.Timestamptz
	LogRetryAt            pgtype.Timestamptz
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

type CsfJobBudget struct {
	Account           string
	LimitUsdMicros    int64
	ReservedUsdMicros int64
	CreatedAt         pgtype.Timestamptz
}

type CsfJobMeasurement struct {
	JobID        string
	Metric       string
	Step         int64
	Value        float64
	RecordedAt   pgtype.Timestamptz
	EvidenceHash string
}

type CsfJobMetricDefinition struct {
	JobID       string
	Name        string
	Unit        string
	Description string
}

type CsfJobTraceDelivery struct {
	Destination string
	TraceID     string
	JobID       string
	State       CsfTraceDeliveryState
	Error       string
	CreatedAt   pgtype.Timestamptz
	FinishedAt  pgtype.Timestamptz
}

type CsfMeterInvariant struct {
	MeasuredOn string
	CommitSha  string
	Name       string
	Satisfied  int32
	Checked    int32
	Mode       string
	OwnerSlice string
}

type CsfMeterMeasurement struct {
	MeasuredOn string
	CommitSha  string
	Name       string
	Ordinal    int32
	Measures   string
	Now        string
	Target     string
	Source     string
	MovedBy    []byte
}

type CsfNode struct {
	NodeID              string
	Kind                string
	SymbolKey           string
	Title               string
	Statement           string
	ParentNodeID        *string
	AuthorKind          string
	AuthorRef           string
	CitationContentHash *string
	CitationSourceID    *string
	CitationRevision    *string
	CitationChunkID     *string
	CitationStartByte   *int64
	CitationEndByte     *int64
	TextProjectionRef   *string
	VectorProjectionRef *string
	CreatedAt           pgtype.Timestamptz
}

type CsfOuroborosFinding struct {
	Miner    string
	Rule     string
	Subject  string
	Item     string
	Severity string
	Scope    string
	Finding  []byte
	FoundAt  pgtype.Timestamptz
}

type CsfOuroborosFixer struct {
	AssignmentID   string
	Ticket         int64
	Proposal       string
	Miner          string
	Model          string
	StartedAt      pgtype.Timestamptz
	FinishedAt     pgtype.Timestamptz
	Outcome        string
	PullRequestUrl string
	CostUsdMicros  int64
	InputTokens    int64
	OutputTokens   int64
	Seconds        int64
}

type CsfOuroborosItem struct {
	Miner    string
	Item     string
	ByteSize int64
	MinedAt  pgtype.Timestamptz
}

type CsfOuroborosMerge struct {
	PullRequest    int64
	HeadSha        string
	AuthorSessions string
	Merger         string
	Merged         bool
	ExitCode       int32
	Reason         string
	RecordedAt     pgtype.Timestamptz
}

type CsfOuroborosProposal struct {
	Ticket    int64
	Proposal  string
	Miner     string
	Corpus    string
	Instances []byte
	Verdict   string
	Reason    string
	CheckedAt pgtype.Timestamptz
}

type CsfOuroborosSeries struct {
	Series      string
	Day         string
	Value       *float64
	Low         *float64
	High        *float64
	Numerator   int64
	Denominator int64
	ComputedAt  pgtype.Timestamptz
}

type CsfProjectionTask struct {
	SourceID        string
	Revision        string
	Status          CsfProjectionStatus
	Attempts        int32
	LeaseGeneration int64
	LeaseUntil      pgtype.Timestamptz
	NextAttemptAt   pgtype.Timestamptz
	LastError       string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type CsfSlice struct {
	SliceID        string
	Sequence       int64
	Title          string
	Recipe         []byte
	TouchSet       []byte
	Provenance     []byte
	State          CsfSliceState
	AssignmentID   string
	PullRequestUrl string
	Attempts       int32
	Checkpoint     string
	Error          string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type CsfSliceEdge struct {
	FromSliceID string
	ToSliceID   string
	Relation    string
}

type CsfSourceRevision struct {
	SourceID             string
	Revision             string
	ContentHash          string
	RawSourceContentHash *string
	SourceUri            string
	Title                string
	MediaType            string
	License              string
	RetrievedAt          pgtype.Timestamptz
}
