// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scoreboard.sql

package csfpg

import (
	"context"
)

const deleteMeterInvariants = `-- name: DeleteMeterInvariants :execrows
DELETE FROM csf_meter_invariants
WHERE measured_on = $1 AND commit_sha = $2
`

type DeleteMeterInvariantsParams struct {
	MeasuredOn string
	CommitSha  string
}

// One reading is (measured_on, commit_sha): the verb deletes the reading's rows
// and inserts them again, so a rerun replaces the measurement rather than
// colliding with it.
func (q *Queries) DeleteMeterInvariants(ctx context.Context, arg DeleteMeterInvariantsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMeterInvariants, arg.MeasuredOn, arg.CommitSha)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteMeterMeasurements = `-- name: DeleteMeterMeasurements :execrows
DELETE FROM csf_meter_measurements
WHERE measured_on = $1 AND commit_sha = $2
`

type DeleteMeterMeasurementsParams struct {
	MeasuredOn string
	CommitSha  string
}

func (q *Queries) DeleteMeterMeasurements(ctx context.Context, arg DeleteMeterMeasurementsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMeterMeasurements, arg.MeasuredOn, arg.CommitSha)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertMeterInvariant = `-- name: InsertMeterInvariant :one
INSERT INTO csf_meter_invariants (measured_on, commit_sha, name, satisfied, checked, mode, owner_slice)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING measured_on, commit_sha, name, satisfied, checked, mode, owner_slice
`

type InsertMeterInvariantParams struct {
	MeasuredOn string
	CommitSha  string
	Name       string
	Satisfied  int32
	Checked    int32
	Mode       string
	OwnerSlice string
}

func (q *Queries) InsertMeterInvariant(ctx context.Context, arg InsertMeterInvariantParams) (CsfMeterInvariant, error) {
	row := q.db.QueryRow(ctx, insertMeterInvariant,
		arg.MeasuredOn,
		arg.CommitSha,
		arg.Name,
		arg.Satisfied,
		arg.Checked,
		arg.Mode,
		arg.OwnerSlice,
	)
	var i CsfMeterInvariant
	err := row.Scan(
		&i.MeasuredOn,
		&i.CommitSha,
		&i.Name,
		&i.Satisfied,
		&i.Checked,
		&i.Mode,
		&i.OwnerSlice,
	)
	return i, err
}

const insertMeterMeasurement = `-- name: InsertMeterMeasurement :one
INSERT INTO csf_meter_measurements (measured_on, commit_sha, name, ordinal, measures, now, target, source, moved_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING measured_on, commit_sha, name, ordinal, measures, now, target, source, moved_by
`

type InsertMeterMeasurementParams struct {
	MeasuredOn string
	CommitSha  string
	Name       string
	Ordinal    int32
	Measures   string
	Now        string
	Target     string
	Source     string
	MovedBy    []byte
}

func (q *Queries) InsertMeterMeasurement(ctx context.Context, arg InsertMeterMeasurementParams) (CsfMeterMeasurement, error) {
	row := q.db.QueryRow(ctx, insertMeterMeasurement,
		arg.MeasuredOn,
		arg.CommitSha,
		arg.Name,
		arg.Ordinal,
		arg.Measures,
		arg.Now,
		arg.Target,
		arg.Source,
		arg.MovedBy,
	)
	var i CsfMeterMeasurement
	err := row.Scan(
		&i.MeasuredOn,
		&i.CommitSha,
		&i.Name,
		&i.Ordinal,
		&i.Measures,
		&i.Now,
		&i.Target,
		&i.Source,
		&i.MovedBy,
	)
	return i, err
}

const listMeterInvariants = `-- name: ListMeterInvariants :many
SELECT measured_on, commit_sha, name, satisfied, checked, mode, owner_slice FROM csf_meter_invariants
WHERE measured_on = $1 AND commit_sha = $2
ORDER BY name
`

type ListMeterInvariantsParams struct {
	MeasuredOn string
	CommitSha  string
}

func (q *Queries) ListMeterInvariants(ctx context.Context, arg ListMeterInvariantsParams) ([]CsfMeterInvariant, error) {
	rows, err := q.db.Query(ctx, listMeterInvariants, arg.MeasuredOn, arg.CommitSha)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CsfMeterInvariant{}
	for rows.Next() {
		var i CsfMeterInvariant
		if err := rows.Scan(
			&i.MeasuredOn,
			&i.CommitSha,
			&i.Name,
			&i.Satisfied,
			&i.Checked,
			&i.Mode,
			&i.OwnerSlice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMeterMeasurements = `-- name: ListMeterMeasurements :many
SELECT measured_on, commit_sha, name, ordinal, measures, now, target, source, moved_by FROM csf_meter_measurements
WHERE measured_on = $1 AND commit_sha = $2
ORDER BY ordinal
`

type ListMeterMeasurementsParams struct {
	MeasuredOn string
	CommitSha  string
}

func (q *Queries) ListMeterMeasurements(ctx context.Context, arg ListMeterMeasurementsParams) ([]CsfMeterMeasurement, error) {
	rows, err := q.db.Query(ctx, listMeterMeasurements, arg.MeasuredOn, arg.CommitSha)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CsfMeterMeasurement{}
	for rows.Next() {
		var i CsfMeterMeasurement
		if err := rows.Scan(
			&i.MeasuredOn,
			&i.CommitSha,
			&i.Name,
			&i.Ordinal,
			&i.Measures,
			&i.Now,
			&i.Target,
			&i.Source,
			&i.MovedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
