// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/candacelabs/csf/io/net (interfaces: IListener)
//
// Generated by this command:
//
//	mockgen -destination=mock_listener_test.go -package=views_test github.com/candacelabs/csf/io/net IListener
//

// Package views_test is a generated GoMock package.
package views_test

import (
	context "context"
	net "net"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIListener is a mock of IListener interface.
type MockIListener struct {
	ctrl     *gomock.Controller
	recorder *MockIListenerMockRecorder
	isgomock struct{}
}

// MockIListenerMockRecorder is the mock recorder for MockIListener.
type MockIListenerMockRecorder struct {
	mock *MockIListener
}

// NewMockIListener creates a new mock instance.
func NewMockIListener(ctrl *gomock.Controller) *MockIListener {
	mock := &MockIListener{ctrl: ctrl}
	mock.recorder = &MockIListenerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIListener) EXPECT() *MockIListenerMockRecorder {
	return m.recorder
}

// Listen mocks base method.
func (m *MockIListener) Listen(ctx context.Context, network, address string) (net.Listener, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Listen", ctx, network, address)
	ret0, _ := ret[0].(net.Listener)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Listen indicates an expected call of Listen.
func (mr *MockIListenerMockRecorder) Listen(ctx, network, address any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Listen", reflect.TypeOf((*MockIListener)(nil).Listen), ctx, network, address)
}
