#!/usr/bin/env bash
# rho-delta.sh: rho_delta(code) := |delta-claimed bytes| / |bytes| over tracked
# text files at a revision (default origin/main). PROVENANCE directive
# (source monorepo #392); target rho_delta -> 1 is milestone 5.
#
# delta-claimed = a file that declares a generator: a "Code generated ... DO NOT
# EDIT" header, a *.pb.go / *_cgen.md / *.gen.go name, or a path under
# docs/generated/. This is an UPPER BOUND on delta: claims_delta, not
# regenerate(g,I) = x, which only each generator can prove. The gate that
# re-runs generators is tools/check-generated.sh.
#
# Usage: rho-delta.sh [REPO] [REV]
set -Eeuo pipefail
repo=${1:-$(git rev-parse --show-toplevel)}
rev=${2:-origin/main}
total=0; delta=0; files=0; dfiles=0
while IFS= read -r path; do
  case "$path" in
    *.png|*.jpg|*.jpeg|*.gif|*.webp|*.pdf|*.woff|*.woff2|*.ttf|*.ico|*.gz|*.zip|*.bin|*.lock) continue ;;
  esac
  bytes=$(git -C "$repo" cat-file -s "$rev:$path")
  total=$((total + bytes)); files=$((files + 1))
  claimed=0
  case "$path" in
    *.pb.go|*_liquid.pb.go|*_cgen.md|*.gen.go|*_generated.go|docs/generated/*|*/docs/generated/*|*/gen/*) claimed=1 ;;
  esac
  if [[ $claimed -eq 0 ]]; then
    if git -C "$repo" show "$rev:$path" | head -n 5 | grep -q -E 'Code generated .*DO NOT EDIT|^<!-- generated |^# Generated by|%% Generated from'; then claimed=1; fi
  fi
  if [[ $claimed -eq 1 ]]; then delta=$((delta + bytes)); dfiles=$((dfiles + 1)); fi
done < <(git -C "$repo" ls-tree -r --name-only "$rev")
printf 'rev=%s files=%d delta_claimed_files=%d bytes=%d delta_claimed_bytes=%d rho_delta_upper=%.4f\n' \
  "$(git -C "$repo" rev-parse --short "$rev")" "$files" "$dfiles" "$total" "$delta" "$(python3 -c "print($delta/$total)")"
