// Code generated by protoc-gen-liquidproto. DO NOT EDIT.
// versions:
// 	protoc-gen-liquidproto v0.1.0
// 	protoc                 v7.35.1
// source: records.proto

package ouroborosv1

import (
	fmt "fmt"
	liquidproto "github.com/candacelabs/csf/pkg/liquidproto"
	regexp "regexp"
)

var (
	_liquidFactRelationRe0 = regexp.MustCompile("^[a-z][a-z0-9_]{0,63}$")
	_liquidFindingRuleRe0  = regexp.MustCompile("^[a-z][a-z0-9_]{0,63}$")
)

// ValidateSpan checks this message's annotated fields; it does not recurse.
// A failed predicate returns *liquidproto.Error. Nil input also returns an error.
func ValidateSpan(message *Span) error {
	if message == nil {
		return fmt.Errorf("ValidateSpan: nil *Span")
	}
	if !(len(message.Source) > 0 && len(message.Source) <= 4096) {
		return &liquidproto.Error{
			Message:   "candace.ouroboros.v1.Span",
			Field:     "source",
			Predicate: "len(this) > 0 && len(this) <= 4096",
			Value:     message.Source,
		}
	}
	if !(message.Line >= 0) {
		return &liquidproto.Error{
			Message:   "candace.ouroboros.v1.Span",
			Field:     "line",
			Predicate: "this >= 0",
			Value:     message.Line,
		}
	}
	return nil
}

// ValidateFact checks this message's annotated fields; it does not recurse.
// A failed predicate returns *liquidproto.Error. Nil input also returns an error.
func ValidateFact(message *Fact) error {
	if message == nil {
		return fmt.Errorf("ValidateFact: nil *Fact")
	}
	if !(_liquidFactRelationRe0.MatchString(message.Relation)) {
		return &liquidproto.Error{
			Message:   "candace.ouroboros.v1.Fact",
			Field:     "relation",
			Predicate: "matches(this, `^[a-z][a-z0-9_]{0,63}$`)",
			Value:     message.Relation,
		}
	}
	return nil
}

// ValidateFinding checks this message's annotated fields; it does not recurse.
// A failed predicate returns *liquidproto.Error. Nil input also returns an error.
func ValidateFinding(message *Finding) error {
	if message == nil {
		return fmt.Errorf("ValidateFinding: nil *Finding")
	}
	if !(len(message.Miner) > 0 && len(message.Miner) <= 80) {
		return &liquidproto.Error{
			Message:   "candace.ouroboros.v1.Finding",
			Field:     "miner",
			Predicate: "len(this) > 0 && len(this) <= 80",
			Value:     message.Miner,
		}
	}
	if !(_liquidFindingRuleRe0.MatchString(message.Rule)) {
		return &liquidproto.Error{
			Message:   "candace.ouroboros.v1.Finding",
			Field:     "rule",
			Predicate: "matches(this, `^[a-z][a-z0-9_]{0,63}$`)",
			Value:     message.Rule,
		}
	}
	return nil
}

// ValidateLabel checks this message's annotated fields; it does not recurse.
// A failed predicate returns *liquidproto.Error. Nil input also returns an error.
func ValidateLabel(message *Label) error {
	if message == nil {
		return fmt.Errorf("ValidateLabel: nil *Label")
	}
	if !(len(message.Instance) > 0 && len(message.Instance) <= 256) {
		return &liquidproto.Error{
			Message:   "candace.ouroboros.v1.Label",
			Field:     "instance",
			Predicate: "len(this) > 0 && len(this) <= 256",
			Value:     message.Instance,
		}
	}
	if !(len(message.Source) > 0 && len(message.Source) <= 256) {
		return &liquidproto.Error{
			Message:   "candace.ouroboros.v1.Label",
			Field:     "source",
			Predicate: "len(this) > 0 && len(this) <= 256",
			Value:     message.Source,
		}
	}
	return nil
}

// ValidateLabelRequest checks this message's annotated fields; it does not recurse.
// A failed predicate returns *liquidproto.Error. Nil input also returns an error.
func ValidateLabelRequest(message *LabelRequest) error {
	if message == nil {
		return fmt.Errorf("ValidateLabelRequest: nil *LabelRequest")
	}
	if !(message.Ticket > 0) {
		return &liquidproto.Error{
			Message:   "candace.ouroboros.v1.LabelRequest",
			Field:     "ticket",
			Predicate: "this > 0",
			Value:     message.Ticket,
		}
	}
	if !(len(message.Proposal) > 0 && len(message.Proposal) <= 128) {
		return &liquidproto.Error{
			Message:   "candace.ouroboros.v1.LabelRequest",
			Field:     "proposal",
			Predicate: "len(this) > 0 && len(this) <= 128",
			Value:     message.Proposal,
		}
	}
	if !(len(message.Miner) > 0 && len(message.Miner) <= 80) {
		return &liquidproto.Error{
			Message:   "candace.ouroboros.v1.LabelRequest",
			Field:     "miner",
			Predicate: "len(this) > 0 && len(this) <= 80",
			Value:     message.Miner,
		}
	}
	if !(len(message.Reason) <= 4096) {
		return &liquidproto.Error{
			Message:   "candace.ouroboros.v1.LabelRequest",
			Field:     "reason",
			Predicate: "len(this) <= 4096",
			Value:     message.Reason,
		}
	}
	if !(len(message.Repository) <= 256) {
		return &liquidproto.Error{
			Message:   "candace.ouroboros.v1.LabelRequest",
			Field:     "repository",
			Predicate: "len(this) <= 256",
			Value:     message.Repository,
		}
	}
	return nil
}

// ValidateBacktest checks this message's annotated fields; it does not recurse.
// A failed predicate returns *liquidproto.Error. Nil input also returns an error.
func ValidateBacktest(message *Backtest) error {
	if message == nil {
		return fmt.Errorf("ValidateBacktest: nil *Backtest")
	}
	if !(message.Families >= 1) {
		return &liquidproto.Error{
			Message:   "candace.ouroboros.v1.Backtest",
			Field:     "families",
			Predicate: "this >= 1",
			Value:     message.Families,
		}
	}
	return nil
}

// ValidateMutant checks this message's annotated fields; it does not recurse.
// A failed predicate returns *liquidproto.Error. Nil input also returns an error.
func ValidateMutant(message *Mutant) error {
	if message == nil {
		return fmt.Errorf("ValidateMutant: nil *Mutant")
	}
	if !(len(message.Kind) > 0 && len(message.Kind) <= 32) {
		return &liquidproto.Error{
			Message:   "candace.ouroboros.v1.Mutant",
			Field:     "kind",
			Predicate: "len(this) > 0 && len(this) <= 32",
			Value:     message.Kind,
		}
	}
	if !(len(message.Description) > 0 && len(message.Description) <= 1024) {
		return &liquidproto.Error{
			Message:   "candace.ouroboros.v1.Mutant",
			Field:     "description",
			Predicate: "len(this) > 0 && len(this) <= 1024",
			Value:     message.Description,
		}
	}
	return nil
}

// ValidateMutation checks this message's annotated fields; it does not recurse.
// A failed predicate returns *liquidproto.Error. Nil input also returns an error.
func ValidateMutation(message *Mutation) error {
	if message == nil {
		return fmt.Errorf("ValidateMutation: nil *Mutation")
	}
	if !(len(message.Miner) > 0 && len(message.Miner) <= 80) {
		return &liquidproto.Error{
			Message:   "candace.ouroboros.v1.Mutation",
			Field:     "miner",
			Predicate: "len(this) > 0 && len(this) <= 80",
			Value:     message.Miner,
		}
	}
	if !(message.Killed >= 0) {
		return &liquidproto.Error{
			Message:   "candace.ouroboros.v1.Mutation",
			Field:     "killed",
			Predicate: "this >= 0",
			Value:     message.Killed,
		}
	}
	if !(message.Survived >= 0) {
		return &liquidproto.Error{
			Message:   "candace.ouroboros.v1.Mutation",
			Field:     "survived",
			Predicate: "this >= 0",
			Value:     message.Survived,
		}
	}
	if !(message.Excluded >= 0) {
		return &liquidproto.Error{
			Message:   "candace.ouroboros.v1.Mutation",
			Field:     "excluded",
			Predicate: "this >= 0",
			Value:     message.Excluded,
		}
	}
	return nil
}

// ValidateProposedLabel checks this message's annotated fields; it does not recurse.
// A failed predicate returns *liquidproto.Error. Nil input also returns an error.
func ValidateProposedLabel(message *ProposedLabel) error {
	if message == nil {
		return fmt.Errorf("ValidateProposedLabel: nil *ProposedLabel")
	}
	if !(message.Ticket > 0) {
		return &liquidproto.Error{
			Message:   "candace.ouroboros.v1.ProposedLabel",
			Field:     "ticket",
			Predicate: "this > 0",
			Value:     message.Ticket,
		}
	}
	if !(len(message.Instance) > 0 && len(message.Instance) <= 256) {
		return &liquidproto.Error{
			Message:   "candace.ouroboros.v1.ProposedLabel",
			Field:     "instance",
			Predicate: "len(this) > 0 && len(this) <= 256",
			Value:     message.Instance,
		}
	}
	return nil
}
