// Code generated by MockGen. DO NOT EDIT.
// Source: tickets.go
//
// Generated by this command:
//
//	mockgen -source=tickets.go -destination=mocks/mock_tickets.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	ouroboros "github.com/candacelabs/csf/services/ouroboros"
	gomock "go.uber.org/mock/gomock"
)

// MockITickets is a mock of ITickets interface.
type MockITickets struct {
	ctrl     *gomock.Controller
	recorder *MockITicketsMockRecorder
	isgomock struct{}
}

// MockITicketsMockRecorder is the mock recorder for MockITickets.
type MockITicketsMockRecorder struct {
	mock *MockITickets
}

// NewMockITickets creates a new mock instance.
func NewMockITickets(ctrl *gomock.Controller) *MockITickets {
	mock := &MockITickets{ctrl: ctrl}
	mock.recorder = &MockITicketsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITickets) EXPECT() *MockITicketsMockRecorder {
	return m.recorder
}

// Comment mocks base method.
func (m *MockITickets) Comment(ctx context.Context, number int64, body string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Comment", ctx, number, body)
	ret0, _ := ret[0].(error)
	return ret0
}

// Comment indicates an expected call of Comment.
func (mr *MockITicketsMockRecorder) Comment(ctx, number, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Comment", reflect.TypeOf((*MockITickets)(nil).Comment), ctx, number, body)
}

// ListMiningTickets mocks base method.
func (m *MockITickets) ListMiningTickets(ctx context.Context) ([]ouroboros.Ticket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMiningTickets", ctx)
	ret0, _ := ret[0].([]ouroboros.Ticket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMiningTickets indicates an expected call of ListMiningTickets.
func (mr *MockITicketsMockRecorder) ListMiningTickets(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMiningTickets", reflect.TypeOf((*MockITickets)(nil).ListMiningTickets), ctx)
}

// ListReadyPullRequests mocks base method.
func (m *MockITickets) ListReadyPullRequests(ctx context.Context) ([]ouroboros.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListReadyPullRequests", ctx)
	ret0, _ := ret[0].([]ouroboros.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListReadyPullRequests indicates an expected call of ListReadyPullRequests.
func (mr *MockITicketsMockRecorder) ListReadyPullRequests(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListReadyPullRequests", reflect.TypeOf((*MockITickets)(nil).ListReadyPullRequests), ctx)
}

// PullRequest mocks base method.
func (m *MockITickets) PullRequest(ctx context.Context, number int64) (ouroboros.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PullRequest", ctx, number)
	ret0, _ := ret[0].(ouroboros.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PullRequest indicates an expected call of PullRequest.
func (mr *MockITicketsMockRecorder) PullRequest(ctx, number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PullRequest", reflect.TypeOf((*MockITickets)(nil).PullRequest), ctx, number)
}

// PullRequestSessions mocks base method.
func (m *MockITickets) PullRequestSessions(ctx context.Context, number int64) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PullRequestSessions", ctx, number)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PullRequestSessions indicates an expected call of PullRequestSessions.
func (mr *MockITicketsMockRecorder) PullRequestSessions(ctx, number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PullRequestSessions", reflect.TypeOf((*MockITickets)(nil).PullRequestSessions), ctx, number)
}

// Reference mocks base method.
func (m *MockITickets) Reference(ctx context.Context, number int64) (ouroboros.ReferenceKind, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reference", ctx, number)
	ret0, _ := ret[0].(ouroboros.ReferenceKind)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Reference indicates an expected call of Reference.
func (mr *MockITicketsMockRecorder) Reference(ctx, number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reference", reflect.TypeOf((*MockITickets)(nil).Reference), ctx, number)
}

// Repository mocks base method.
func (m *MockITickets) Repository() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Repository")
	ret0, _ := ret[0].(string)
	return ret0
}

// Repository indicates an expected call of Repository.
func (mr *MockITicketsMockRecorder) Repository() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Repository", reflect.TypeOf((*MockITickets)(nil).Repository))
}

// TicketComments mocks base method.
func (m *MockITickets) TicketComments(ctx context.Context, number int64) ([]ouroboros.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TicketComments", ctx, number)
	ret0, _ := ret[0].([]ouroboros.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TicketComments indicates an expected call of TicketComments.
func (mr *MockITicketsMockRecorder) TicketComments(ctx, number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TicketComments", reflect.TypeOf((*MockITickets)(nil).TicketComments), ctx, number)
}
