// Code generated by MockGen. DO NOT EDIT.
// Source: store.go
//
// Generated by this command:
//
//	mockgen -source=store.go -destination=mocks/mock_store.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	ouroboros "github.com/candacelabs/csf/services/ouroboros"
	gomock "go.uber.org/mock/gomock"
)

// MockIStore is a mock of IStore interface.
type MockIStore struct {
	ctrl     *gomock.Controller
	recorder *MockIStoreMockRecorder
	isgomock struct{}
}

// MockIStoreMockRecorder is the mock recorder for MockIStore.
type MockIStoreMockRecorder struct {
	mock *MockIStore
}

// NewMockIStore creates a new mock instance.
func NewMockIStore(ctrl *gomock.Controller) *MockIStore {
	mock := &MockIStore{ctrl: ctrl}
	mock.recorder = &MockIStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIStore) EXPECT() *MockIStoreMockRecorder {
	return m.recorder
}

// FindingsSince mocks base method.
func (m *MockIStore) FindingsSince(ctx context.Context, since time.Time) ([]ouroboros.Finding, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindingsSince", ctx, since)
	ret0, _ := ret[0].([]ouroboros.Finding)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindingsSince indicates an expected call of FindingsSince.
func (mr *MockIStoreMockRecorder) FindingsSince(ctx, since any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindingsSince", reflect.TypeOf((*MockIStore)(nil).FindingsSince), ctx, since)
}

// FixersForTicket mocks base method.
func (m *MockIStore) FixersForTicket(ctx context.Context, ticket int64) ([]ouroboros.Fixer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FixersForTicket", ctx, ticket)
	ret0, _ := ret[0].([]ouroboros.Fixer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FixersForTicket indicates an expected call of FixersForTicket.
func (mr *MockIStoreMockRecorder) FixersForTicket(ctx, ticket any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FixersForTicket", reflect.TypeOf((*MockIStore)(nil).FixersForTicket), ctx, ticket)
}

// FixersStartedSince mocks base method.
func (m *MockIStore) FixersStartedSince(ctx context.Context, since time.Time) ([]ouroboros.Fixer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FixersStartedSince", ctx, since)
	ret0, _ := ret[0].([]ouroboros.Fixer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FixersStartedSince indicates an expected call of FixersStartedSince.
func (mr *MockIStoreMockRecorder) FixersStartedSince(ctx, since any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FixersStartedSince", reflect.TypeOf((*MockIStore)(nil).FixersStartedSince), ctx, since)
}

// Item mocks base method.
func (m *MockIStore) Item(ctx context.Context, miner, item string) (ouroboros.Item, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Item", ctx, miner, item)
	ret0, _ := ret[0].(ouroboros.Item)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Item indicates an expected call of Item.
func (mr *MockIStoreMockRecorder) Item(ctx, miner, item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Item", reflect.TypeOf((*MockIStore)(nil).Item), ctx, miner, item)
}

// ItemsMinedSince mocks base method.
func (m *MockIStore) ItemsMinedSince(ctx context.Context, since time.Time) ([]ouroboros.Item, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ItemsMinedSince", ctx, since)
	ret0, _ := ret[0].([]ouroboros.Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ItemsMinedSince indicates an expected call of ItemsMinedSince.
func (mr *MockIStoreMockRecorder) ItemsMinedSince(ctx, since any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ItemsMinedSince", reflect.TypeOf((*MockIStore)(nil).ItemsMinedSince), ctx, since)
}

// Merge mocks base method.
func (m *MockIStore) Merge(ctx context.Context, pullRequest int64, headSHA string) (ouroboros.Merge, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Merge", ctx, pullRequest, headSHA)
	ret0, _ := ret[0].(ouroboros.Merge)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Merge indicates an expected call of Merge.
func (mr *MockIStoreMockRecorder) Merge(ctx, pullRequest, headSHA any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Merge", reflect.TypeOf((*MockIStore)(nil).Merge), ctx, pullRequest, headSHA)
}

// Proposal mocks base method.
func (m *MockIStore) Proposal(ctx context.Context, ticket int64, proposal string) (ouroboros.ProposalRecord, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Proposal", ctx, ticket, proposal)
	ret0, _ := ret[0].(ouroboros.ProposalRecord)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Proposal indicates an expected call of Proposal.
func (mr *MockIStoreMockRecorder) Proposal(ctx, ticket, proposal any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Proposal", reflect.TypeOf((*MockIStore)(nil).Proposal), ctx, ticket, proposal)
}

// ProposalsNeedingLabels mocks base method.
func (m *MockIStore) ProposalsNeedingLabels(ctx context.Context) ([]ouroboros.ProposalRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProposalsNeedingLabels", ctx)
	ret0, _ := ret[0].([]ouroboros.ProposalRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProposalsNeedingLabels indicates an expected call of ProposalsNeedingLabels.
func (mr *MockIStoreMockRecorder) ProposalsNeedingLabels(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProposalsNeedingLabels", reflect.TypeOf((*MockIStore)(nil).ProposalsNeedingLabels), ctx)
}

// RecentFindings mocks base method.
func (m *MockIStore) RecentFindings(ctx context.Context, limit int) ([]ouroboros.Finding, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecentFindings", ctx, limit)
	ret0, _ := ret[0].([]ouroboros.Finding)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RecentFindings indicates an expected call of RecentFindings.
func (mr *MockIStoreMockRecorder) RecentFindings(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecentFindings", reflect.TypeOf((*MockIStore)(nil).RecentFindings), ctx, limit)
}

// RecentFixers mocks base method.
func (m *MockIStore) RecentFixers(ctx context.Context, limit int) ([]ouroboros.Fixer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecentFixers", ctx, limit)
	ret0, _ := ret[0].([]ouroboros.Fixer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RecentFixers indicates an expected call of RecentFixers.
func (mr *MockIStoreMockRecorder) RecentFixers(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecentFixers", reflect.TypeOf((*MockIStore)(nil).RecentFixers), ctx, limit)
}

// RecentMerges mocks base method.
func (m *MockIStore) RecentMerges(ctx context.Context, limit int) ([]ouroboros.Merge, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecentMerges", ctx, limit)
	ret0, _ := ret[0].([]ouroboros.Merge)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RecentMerges indicates an expected call of RecentMerges.
func (mr *MockIStoreMockRecorder) RecentMerges(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecentMerges", reflect.TypeOf((*MockIStore)(nil).RecentMerges), ctx, limit)
}

// RecordFindings mocks base method.
func (m *MockIStore) RecordFindings(ctx context.Context, findings []ouroboros.Finding) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordFindings", ctx, findings)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RecordFindings indicates an expected call of RecordFindings.
func (mr *MockIStoreMockRecorder) RecordFindings(ctx, findings any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordFindings", reflect.TypeOf((*MockIStore)(nil).RecordFindings), ctx, findings)
}

// RecordFixer mocks base method.
func (m *MockIStore) RecordFixer(ctx context.Context, fixer ouroboros.Fixer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordFixer", ctx, fixer)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordFixer indicates an expected call of RecordFixer.
func (mr *MockIStoreMockRecorder) RecordFixer(ctx, fixer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordFixer", reflect.TypeOf((*MockIStore)(nil).RecordFixer), ctx, fixer)
}

// RecordItem mocks base method.
func (m *MockIStore) RecordItem(ctx context.Context, item ouroboros.Item) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordItem", ctx, item)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordItem indicates an expected call of RecordItem.
func (mr *MockIStoreMockRecorder) RecordItem(ctx, item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordItem", reflect.TypeOf((*MockIStore)(nil).RecordItem), ctx, item)
}

// RecordMerge mocks base method.
func (m *MockIStore) RecordMerge(ctx context.Context, merge ouroboros.Merge) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordMerge", ctx, merge)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordMerge indicates an expected call of RecordMerge.
func (mr *MockIStoreMockRecorder) RecordMerge(ctx, merge any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordMerge", reflect.TypeOf((*MockIStore)(nil).RecordMerge), ctx, merge)
}

// RecordProposal mocks base method.
func (m *MockIStore) RecordProposal(ctx context.Context, record ouroboros.ProposalRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordProposal", ctx, record)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordProposal indicates an expected call of RecordProposal.
func (mr *MockIStoreMockRecorder) RecordProposal(ctx, record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordProposal", reflect.TypeOf((*MockIStore)(nil).RecordProposal), ctx, record)
}

// RecordSeries mocks base method.
func (m *MockIStore) RecordSeries(ctx context.Context, point ouroboros.Point) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordSeries", ctx, point)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordSeries indicates an expected call of RecordSeries.
func (mr *MockIStoreMockRecorder) RecordSeries(ctx, point any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordSeries", reflect.TypeOf((*MockIStore)(nil).RecordSeries), ctx, point)
}

// RunningFixers mocks base method.
func (m *MockIStore) RunningFixers(ctx context.Context) ([]ouroboros.Fixer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunningFixers", ctx)
	ret0, _ := ret[0].([]ouroboros.Fixer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunningFixers indicates an expected call of RunningFixers.
func (mr *MockIStoreMockRecorder) RunningFixers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunningFixers", reflect.TypeOf((*MockIStore)(nil).RunningFixers), ctx)
}

// Series mocks base method.
func (m *MockIStore) Series(ctx context.Context, series string) ([]ouroboros.Point, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Series", ctx, series)
	ret0, _ := ret[0].([]ouroboros.Point)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Series indicates an expected call of Series.
func (mr *MockIStoreMockRecorder) Series(ctx, series any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Series", reflect.TypeOf((*MockIStore)(nil).Series), ctx, series)
}

// UpdateFixer mocks base method.
func (m *MockIStore) UpdateFixer(ctx context.Context, fixer ouroboros.Fixer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFixer", ctx, fixer)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFixer indicates an expected call of UpdateFixer.
func (mr *MockIStoreMockRecorder) UpdateFixer(ctx, fixer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFixer", reflect.TypeOf((*MockIStore)(nil).UpdateFixer), ctx, fixer)
}
