load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "proc",
    srcs = [
        "group_other.go",
        "group_unix.go",
        "launcher.go",
        "process.go",
    ],
    importpath = "github.com/candacelabs/csf/ipc/proc",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/boundedbuffer",
        "//pkg/boundedbuffer/v1:boundedbuffer",
        "//runtime/config",
        "@com_github_creack_pty//:pty",
    ],
)

go_test(
    name = "proc_test",
    srcs = [
        "launcher_test.go",
        "launcher_unit_test.go",
        "proc_suite_test.go",
    ],
    embed = [":proc"],
    deps = [
        "@com_github_onsi_ginkgo_v2//:ginkgo",
        "@com_github_onsi_gomega//:gomega",
    ] + select({
        "@rules_go//go/platform:android": [
            "//pkg/eventually",
            "@org_uber_go_goleak//:goleak",
        ],
        "@rules_go//go/platform:linux": [
            "//pkg/eventually",
            "@org_uber_go_goleak//:goleak",
        ],
        "//conditions:default": [],
    }),
)
