// Code generated by protoc-gen-liquidproto. DO NOT EDIT.
// versions:
// 	protoc-gen-liquidproto v0.1.0
// 	protoc                 v7.35.1
// source: candace/harness/v1/costs.proto

package harnessv1

import (
	fmt "fmt"
	liquidproto "github.com/candacelabs/csf/pkg/liquidproto"
)

// ValidateTokenCounts checks this message's annotated fields; it does not recurse.
// A failed predicate returns *liquidproto.Error. Nil input also returns an error.
func ValidateTokenCounts(message *TokenCounts) error {
	if message == nil {
		return fmt.Errorf("ValidateTokenCounts: nil *TokenCounts")
	}
	if !(message.UncachedInput >= 0) {
		return &liquidproto.Error{
			Message:   "candace.harness.v1.TokenCounts",
			Field:     "uncached_input",
			Predicate: "this >= 0",
			Value:     message.UncachedInput,
		}
	}
	if !(message.CacheWrite >= 0) {
		return &liquidproto.Error{
			Message:   "candace.harness.v1.TokenCounts",
			Field:     "cache_write",
			Predicate: "this >= 0",
			Value:     message.CacheWrite,
		}
	}
	if !(message.CacheRead >= 0) {
		return &liquidproto.Error{
			Message:   "candace.harness.v1.TokenCounts",
			Field:     "cache_read",
			Predicate: "this >= 0",
			Value:     message.CacheRead,
		}
	}
	if !(message.Output >= 0) {
		return &liquidproto.Error{
			Message:   "candace.harness.v1.TokenCounts",
			Field:     "output",
			Predicate: "this >= 0",
			Value:     message.Output,
		}
	}
	return nil
}

// ValidateMeasuredInput checks this message's annotated fields; it does not recurse.
// A failed predicate returns *liquidproto.Error. Nil input also returns an error.
func ValidateMeasuredInput(message *MeasuredInput) error {
	if message == nil {
		return fmt.Errorf("ValidateMeasuredInput: nil *MeasuredInput")
	}
	if !(len(message.Name) > 0) {
		return &liquidproto.Error{
			Message:   "candace.harness.v1.MeasuredInput",
			Field:     "name",
			Predicate: "len(this) > 0",
			Value:     message.Name,
		}
	}
	if !(message.N >= 0) {
		return &liquidproto.Error{
			Message:   "candace.harness.v1.MeasuredInput",
			Field:     "n",
			Predicate: "this >= 0",
			Value:     message.N,
		}
	}
	return nil
}

// ValidateHypervisorParameter checks this message's annotated fields; it does not recurse.
// A failed predicate returns *liquidproto.Error. Nil input also returns an error.
func ValidateHypervisorParameter(message *HypervisorParameter) error {
	if message == nil {
		return fmt.Errorf("ValidateHypervisorParameter: nil *HypervisorParameter")
	}
	if !(len(message.Name) > 0) {
		return &liquidproto.Error{
			Message:   "candace.harness.v1.HypervisorParameter",
			Field:     "name",
			Predicate: "len(this) > 0",
			Value:     message.Name,
		}
	}
	return nil
}
